### ISSUE TITLE
Enhancement: Solid and sparse fill lines should connect at the end of every other line

### ISSUE THREAD

**Issue by mikeq3** [Ultimaker/CuraEngine#10]
Solid and sparse fill lines should connect at the end of every other line. Right now you have a small travel between alternating lines. You should have those travels be an extrusion like in skeinforge. This way you have better bonding to the walls.

**Comment by BagelOrb** [comment]
The standard infill is grid infill. If we would perform an extrusion over the travel along the perimeter, between two infill lines, then parts of the inset of the inner perimeter will get *double the filament*! You would get overextrusion.

**Comment by BagelOrb** [comment]
The above comment means that no such pattern is possible for grid infill. For lines infill there is the ZigZag pattern now.
