### ISSUE TITLE
Flavour name in gcode file for volumetric RepRap

### ISSUE THREAD

**Issue by Dim3nsioneer** [Ultimaker/CuraEngine#100]
For Ultigcode the flavour is written into the gcode file with a comment line. I propose to let the CuraEngine write a similar comment line for the volumetric RepRap flavour. This helps for determine the type of retraction (Cura or FW) in retraction-related plugins. Also other plugins may profit if they deal with flavour-dependent gcode.

edit: on second thought it might be useful to have such a comment line for any flavour...

**Comment by BagelOrb** [comment]
The flavour is currently prepended by the front-end.

**Comment by Dim3nsioneer** [comment]
Please feel free to move the issue there.

**Comment by BagelOrb** [comment]
I think it should be implemented in the back-end though. I will have to consort Daid.

**Comment by Ghostkeeper** [comment]
@Dim3nsioneer, a request. @BagelOrb fixed this in commits 41a1db1e55766141abf6ea7befa5a37bc09736c0, 5ede92fb1b71bbcaee9deab13b7ec962506aedc6 and 68602df6ee0cb46d949d4ddfd0c5a48620d5b933, but we have no way to actually test this since no volumetric RepRap machine is in working order here at Ultimaker. Perhaps you could try this for us?

**Comment by BagelOrb** [comment]
@Ghostkeeper what is to be tested? Machines other than UM2 don't require the flavour to be in the header of the gcode file.
Furthermore we already use comments in the gcode, so I can't imagine the comment containing the gcode flavour could cause the firmware to fail in any printer but an UM2.

The feature was introduced to make future dependency on gcode flavour possible. Both the firmware and post processing plugins might benefit from dependency on the gcode flavour tag.

**Comment by Dim3nsioneer** [comment]
@BagelOrb @Ghostkeeper I'm a bit busy these days. If you can test or check it in some way by yourselves I would appreciate it. If everything else fails, please come back to me for testing. Thanks.

**Comment by Ghostkeeper** [comment]
Ah, right. Seems I read too quickly over the original issue. Well, the flavour is written at the start of all g-code now, so plug-ins could use this to detect the printer.
