### ISSUE TITLE
Unnecessary extruder swaps with Ooze shield and Wipe&Prime tower

### ISSUE THREAD

**Issue by Dim3nsioneer** [Ultimaker/CuraEngine#101]
If you do a dual extrusion print with Cura (checked with 14.05-RC4) where Ooze shield and Wipe&Prime tower are used, CuraEngine performs an extruder swap on each layer neglecting if such a swap is actually needed by the model. This leads to unnecessary mixing effect of the two extruded materials and increases print time.
I suggest a check by Cura if extruder swapping is necessary on each layer and if not, then ooze shield and Wipe&Prime tower are printed with the same material/extruder as the previous layer.
In the meantime I try to implement a work-around with a Cura plugin.

**Comment by innovo3d** [comment]
Hey David, have you made any advancements on this?  I'm printing with two extruders and also noticing this unnecessary extruder swap.  Ooze shield should only be with one extruder for every layer, not two.

**Comment by daid** [comment]
I think @BagelOrb worked this out for the new Cura as soon as that comes with dual extrusion.

**Comment by innovo3d** [comment]
@BagelOrb, you may want to add a "prime" after switching extruders, it can either be extruding in the air outside of the ooze shield or doing another layer on top of the ooze shield.

**Comment by BagelOrb** [comment]
That is what the prime tower is for..
Op 22 okt. 2015 22:25 schreef "Adam Rumjahn" <notifications@github.com>:

**Comment by BagelOrb** [comment]
Priming in thin air seems a bit dangerous, but it does seem like a valid technique, the way you describe it.
You should make a separate feature request issue for this.

I assume the wiper has a fixed position on the printer. Either the position should be calibrated by the firmware or hardcoded into a Cura profile. The gcode commands to perform the wipe on the wiper should be part of the switch gcode commands.
