### ISSUE TITLE
[3.6.0] Cannot reconnect to the Robo 3D C2 printer after wifi network went down

### ISSUE THREAD

**Issue by tkocou** [Ultimaker/CuraEngine#1011]
**Application Version**
3.6.0

**Platform**
Linux

**Qt**
N/A

**PyQt**
N/A

**Display Driver**
N/A

**Steps to Reproduce**
N/A

**Actual Results**
N/A

**Expected results**
N/A

**Additional Information**
I experienced a wifi network failure after CURA started a very long print. After fixing the network, the C2 printer acquired a new IP address. However, CURA was using the old IP address. While I could program a static IP into the router for the C2 printer, doing so would defeat the purpose of using DHCP. 
A network update function for CURA would be a nice to have feature. And BTW,  the print came out fine as the gcode was stored on OctoPrint in the C2 printer.

**Comment by Ghostkeeper** [comment]
This is a bug report about the OctoPrint plug-in into Cura, submitted to the repository for CuraEngine. I suggest you submit your bug here: https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues
