### ISSUE TITLE
PolygonUtilsTest fails on ARM

### ISSUE THREAD

**Issue by ggardet** [Ultimaker/CuraEngine#1040]
**Application Version**
3.6.5

**Platform**
Occurs on aarch64, armv7 and armv6

**Qt**
no

**PyQt**
no

**Display Driver**
none

**Steps to Reproduce**
Build and run the test suite on ARM

**Actual Results**
```
test 9
      Start  9: PolygonUtilsTest

9: Test command: /home/abuild/rpmbuild/BUILD/CuraEngine-3.6.5/build/PolygonUtilsTest
9: Test timeout computed to be: 10000000
9: .................................F...F..F....F
9: 
 9/12 Test  #9: PolygonUtilsTest .................***Failed    0.01 sec
```

**Expected results**
Test should pass.

**Additional Information**

**Comment by Ghostkeeper** [comment]
That's because we don't target ARM right now. If you can debug these issues a pull request would be welcome though. I'm not planning to maintain ARM builds as well.
