### ISSUE TITLE
Memory leaks in cura::AdaptiveLayerHeights::calculateLayers()

### ISSUE THREAD

**Issue by doubleXnine** [Ultimaker/CuraEngine#1061]
I think there are memory leaks in cura::AdaptiveLayerHeights::calculateLayers(), the AdaptiveLayer object allocated using new operator is not deleted, and it occurs three times in this member function. I use CuraEngine 3.6.0 now, and the allocating is at line 70, 164, 183 in AdaptiveLayerHeight.cpp.

**Application Version**
CuraEngine 3.6.0, but I found it still exists in the latest version

**Comment by Ghostkeeper** [comment]
Yeah indeed that is useless. Thanks.
