### ISSUE TITLE
Possibility to add polar coordinate space?

### ISSUE THREAD

**Issue by BKLronin** [Ultimaker/CuraEngine#1081]
As the title says, can someone tell me if it is technical possible to replace the cartesian space with a polar space? 

Thank you in advance.

**Comment by smartavionics** [comment]
Hello @BKLronin . Not sure what you mean there. Are you referring to the input space (i.e. replace models 
specified as x/y/z with mag/deg/?) or the output space (some form of polar coordinate version of gcode)?

**Comment by BKLronin** [comment]
Hello @smartavionics,

I mean placing normal models that have been created in xyz on  a polar space so that the resulting gcode would be natively  in polar coordinates without post processing? So that the engine directly outputs into polar. Postprocessing needs a lot of segmentation and a lot of small moves increasing the file size to GB on larger models.

**Comment by smartavionics** [comment]
OK, so do you have a syntax for polar gcode?

**Comment by BKLronin** [comment]
I got the general transformation from my debug python program. That would be without segmentation. 

```
def polar(x,y):
        #radius calculate
        radius = math.sqrt(x ** 2 + y ** 2)
        #angle calculate
        angle = math.atan2(y, x) * 180.0 / math.pi        

        return radius, angle
```

**Comment by smartavionics** [comment]
Sure, but the slicer's output is going to be the input to a printer and that printer (presumably) has a language it understands. Do you have any info on that or is this all just speculation?

**Comment by BKLronin** [comment]
The printer runs the klipper firmware so a standard X,Y,Z Gcode in marlin flavor is sufficient. Iḿ trying to implement this with Kevin O Connor from the KLipper project currently but Iḿ more the mechanical engineer than a programmer so my programming skills are limited and Kevins time is as well. I got a full working polar printer for testing and the ability to debug the firmware itself with incoming gcode.

**Comment by smartavionics** [comment]
Ah, OK. Well, I can say with 99.9999% certainty that Ultimaker won't be interested in working on this but I may well look into it when there is a printer language  definition or at least a good description of how the printer expects the input to look like.

**Comment by BKLronin** [comment]
Thank you very much for your assistance. It seems to work now on the firmware level :)
