### ISSUE TITLE
Will the infill path ever exit the polygon?

### ISSUE THREAD

**Issue by rgov** [Ultimaker/CuraEngine#1085]
I used CuraEngine to generate the infill on a polygon shaped like a skull and crossbones, and then plotted the traversal path of the extruder from the generated GCode:

![image](https://user-images.githubusercontent.com/108767/60049625-a7746b00-969c-11e9-85f1-6ad4221fc790.png)

I notice that the extruder's path never exits the bounds of the polygon, even when not extruding filament. Is this always true, even when such a path would be more efficient?

**Comment by smartavionics** [comment]
Depends on whether combing is enabled. If combing is not enabled, travel moves will be direct so they may cross the boundaries of the polygon.

**Comment by rgov** [comment]
That's awesome, thanks! Here's with combing disabled:

<img width="307" alt="image" src="https://user-images.githubusercontent.com/108767/60116806-c29bb500-9746-11e9-8c05-3db722e2bcd9.png">
