### ISSUE TITLE
Wrong order of brim lines

### ISSUE THREAD

**Issue by Dim3nsioneer** [Ultimaker/CuraEngine#110]
The present CuraEngine (of Cura 14.06.1) seems (still / again?) to generate the brim lines in the wrong order, i.e. it starts right from the surface of the object... Example: Check it with a cylindrical object without bottom, e.g. https://www.youmagine.com/documents/6347/download.

**Comment by BagelOrb** [comment]
In Cura 15.02.1 this problem doesn't seem to occur anymore
