### ISSUE TITLE
Feature request: Opening a Cura project must have the option to ignore project settings

### ISSUE THREAD

**Issue by niculaegeorge** [Ultimaker/CuraEngine#1101]
When opening a Cura <3mf> project we are greeted with the summary window of the cura project file. Currently for the profile settings, in the drop-down list to the right, the actions we have are "Update existing" and "Create new". It is critical to also have the option "Ignore settings" or "Use current", meaning it completely ignores the profile settings inside the project file and uses the last used settings in Cura. This ensures consistency in workflow by not having to mess with your tweaked settings each time you want to update a project and you don't want to create a new profile each time you open that project. The logic is this: You don't want the project to update your profile settings in Cura. Quite the opposite! You want the last used and tweaked settings in Cura to update the profile settings inside the project. The other way around! Therefore ignoring the embedded settings in the project <3mf> file is crucial. You open the project, ignore profile settings in it, and then just save it. Done! Your project profile settings have been updated with ease.

**Comment by Ghostkeeper** [comment]
When opening a 3MF file it'll ask the user whether it wants to load it as a project with all of its profiles or just load the models from the 3MF files. That's precisely what this feature request asks.

Perhaps you've made it "always load as a project" in the preferences screen or by checking the "don't ask me this again" check mark.
