### ISSUE TITLE
can curaEngine load .curaprofile?

### ISSUE THREAD

**Issue by BrentHuang** [Ultimaker/CuraEngine#1143]
**Application Version**

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by Ghostkeeper** [comment]
No, it can't. Cura profiles contain Python formulas which need a Python interpreter to be resolved. We are not planning to support that in our debug command line interface.
