### ISSUE TITLE
XML file display problem，for example, I want to see what cura. XML looks like. I don't know how to do it.

### ISSUE THREAD

**Issue by LittleLittleFish** [Ultimaker/CuraEngine#1145]
**Application Version**

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by Ghostkeeper** [comment]
You can open them with a text editor. XML files are human-readable. Or in the browser. See for instance the [generic_pla](https://github.com/Ultimaker/fdm_materials/blob/master/generic_pla.xml.fdm_material) file.
