### ISSUE TITLE
Cannot slice stl model global settings missing

### ISSUE THREAD

**Issue by averter** [Ultimaker/CuraEngine#1159]
**Application Version**
3.1.0 

**Platform**
Linux Mint Cinnamon 19.2

**Steps to Reproduce**
1. Download `prusa_i3.def.json`, `prusa_i3_extruder_0.def.json`, `fdmextruder.def.json` and `fdmprinter.def.json` to Desktop from [definitions directory](https://github.com/Ultimaker/Cura/tree/master/resources/definitions) and [extruders directory](https://github.com/Ultimaker/Cura/tree/master/resources/extruders)
2. run `CuraEngine slice -v -j ~/Desktop/prusa_i3.def.json -o "test.gcode" -e0 -s infill_line_distance=0 -e0 -l "test.stl"`

**Actual Results**
1. Should return an error `[ERROR] Trying to retrieve unregistered setting with no value given: 'max_feedrate_z_override'`.

**Expected results**
1. I've tried to add the missing variable as `-s max_feedrate_z_override=0` but then another variable is amiss. This keeps happening continuously.
2. I've found that the missing variables are in [tests/test_global_settings.txt](https://github.com/Ultimaker/CuraEngine/blob/e6caed5012412b416670be81361eb59cf7310be4/tests/test_global_settings.txt) but am not sure of how to include them automatically in the command line

**Additional Information**
I am new to CuraEngine so apologies if the question has a rather obvious answer, but I couldn't find more info online.

**Comment by averter** [comment]
I've also tried to use the aforementioned settings files for the Cura 3.1.0 branch, but the result is the same. I've seen that there are other similar issues for this error but I don't quite understand what is wrong (probably because I am new to the Cura project) and how to fix it.

**Comment by rburema** [comment]
(Please note that in general, we only support the latest version.)

For I understand correctly that you download the definitions from the master branch and then try to apply them to an older version of the engine? I can tell, because 'max_feedrate_z_override' was removed for 4.2 as far as I can tell (not in the current engine anymore).

You should make sure the version (of the Cura repo) of the definitions and the version of the CuraEngine are the same. If you're trying to run the engine at 3.1, you should get the definitions of Cura 3.1

**Comment by averter** [comment]
Thanks @rburema. I did use Cura 3.1 definitions and now it is working. 
I have one final question though (I hope it makes sense). I'm using CuraEngine mainly to determine the volume and printing time of a given model for certain combination of three parameters. The parameters are the layer height, the infill density and the speed of the print. My question is what settings need to be changed in the settings JSON file based on the above parameters? So far I've associated layer height with a `resolution` setting, infill density with an `infill_sparse_density` and the speed with a `speed_print` setting. Are there other settings beyond these three that are changed when the properties are updated on cura material profiles? Thank you in advance.

**Comment by rburema** [comment]
The settings `infill_sparse_density` and `speed_print` are correct, `resolution` is a category though, you probably want `layer_height`.

However! There's a large number of things that depend on those settings. Resolving those dependencies is part of the point of the front-end.

I'd suggest building a plugin for the front-end if you're going to need the same.

**Comment by averter** [comment]
Yes, I meant `layer_height``not resolution - thanks for pointing that out.
When you say "a large number of things" do you mean other settings? For example, I think that the `speed_print` also affects these other settings: speed_wall_x, speed_roofing, speed_support_infill, speed_support, speed_prime_tower, speed_infill, speed_wall_0, bridge_skin_material_flow, speed_topbottom. Is there a way to know what these dependencies are to build such a plugin? Should I ask it in the Cura front-end github for example?

**Comment by Ghostkeeper** [comment]
> So far I've associated layer height with a resolution setting, infill density with an infill_sparse_density and the speed with a speed_print setting.

Actually if you're calling CuraEngine via the command line you won't be able to use `speed_print` or `infill_sparse_density`, but you need to use the leaf settings, so `speed_infill` and such and `infill_line_distance`. CuraEngine only listens to settings that have no child settings. So yeah you'd need to override all of them.

> Is there a way to know what these dependencies are to build such a plugin? Should I ask it in the Cura front-end github for example?

You can take a look at our [example plug-ins](https://github.com/Ultimaker?utf8=✓&q=UraniumExample) or indeed ask it in the Cura Github page.
