### ISSUE TITLE
compile issue about CuraEngine 15.04.6

### ISSUE THREAD

**Issue by Yzhao1125** [Ultimaker/CuraEngine#1180]
**Application Version**
CuraEngine 15.04.6

**Platform**
Ubuntu 18.04

**Actual Results**
when run the following command:
cmake . -G "CodeBlocks - Unix Makefiles"
the response shows that the project does not appear to contain CMakeLists.txt 
I'd like to compile CuraEngine 15.04.6, and there is only a Makefile under /CuraEngine-15.04.6. Could anyone tell me how to compile it sucessfully? Thank you

**Comment by Ghostkeeper** [comment]
CuraEngine 15.04 didn't have CMake support yet. To compile, you run the Makefile by simply executing this command:

    make

We've fixed this issue in version 15.06.
