### ISSUE TITLE
Cura Engine 13.06.4: Index out of Range

### ISSUE THREAD

**Issue by mrseeker** [Ultimaker/CuraEngine#12]
I am experiencing this problem with high-poly objects. They seem to exceed the maximum size set by the vector, causing half of the object to be loaded into memory, while the other half gets thrown into limbo.

Possible options would be either:
A. Expand memory of the vector
B. Better memory usage (dont use Vector but Array)
C. Create a x64-based version that can use more than 4Gb.

output.txt:
```
(<type 'exceptions.IndexError'>, IndexError('list index out of range',), <traceback object at 0x04AAC0A8>)
Cura_SteamEngine version 13.06.4
Loading # from disk...
Reading mesh from binary blob with 782664 vertexes
Loaded from disk in 0.109s
Analyzing and optimizing model...
Face counts: 260888 -> 260508 99.9%
Vertex counts: 782664 -> 130249 16.6%
Optimize model 1.063s
Slicing model...
Closing down
```

**Comment by BagelOrb** [comment]
I suppose the problem is solved?
