### ISSUE TITLE
Feature Request: Tree Infill

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [Ultimaker/CuraEngine#1208]
Requesting infill type where tree supports are printed inside the body of the model such that the tips of the branches internally intersect portions of the body which exceed a specified overhanging angle.

This would optimise the amount of material used because branches can come from the wall sides instead of the floor.

Settings can include the same kinds of settings for tree supports.

The image below illustrates what I'm proposing. The red lines indicate the outer shell of the object, and the orange lines is the infill.

![tree-infill](https://user-images.githubusercontent.com/9839187/75100672-baba3c00-5585-11ea-9626-8500a7873fbe.PNG)

**Comment by mahtDFR** [comment]
Thanks for the suggestion. After some discussion we decided this is not a development priority for us right now, so it's deferred.

**Comment by Ghostkeeper** [comment]
The best alternative right now is to use Gradual Infill. It works very similarly to this suggestion and is more generic to work with each pattern.

**Comment by Daniel-Khodabakhsh** [comment]
Thanks for considering my suggestion!
Would I be able to submit a pull request for this? May take me a while to get ramped up on the code base but I can give it a try.

**Comment by Ghostkeeper** [comment]
Yeah. You'd need to look mainly into the code base for CuraEngine, but then also add a setting to `resources/fdmprinter.def.json` in the Cura repository so that it can be activated.

**Comment by Ghostkeeper** [comment]
Actually, it's probably better to allow Infill Support to work properly with Tree Support.

**Comment by Daniel-Khodabakhsh** [comment]
Thanks for adding lightning infill. Closing this ticket.
