### ISSUE TITLE
curaengine 4.5.0 upgrade failed

### ISSUE THREAD

**Issue by chenrui333** [Ultimaker/CuraEngine#1226]
relates to https://github.com/Homebrew/homebrew-core/pull/51406

**Comment by nallath** [comment]
Uh? I don't understand what you want us to do here.

**Comment by Ghostkeeper** [comment]
Your build fails since it's calling `make` directly on our source code. You need to use CMake first, ensure that it found all of its dependencies, and then call `make`.
