### ISSUE TITLE
Print time incorrect; minutes are always zero

### ISSUE THREAD

**Issue by marciot** [Ultimaker/CuraEngine#1233]
**Application Version**

CuraEngine, master branch

**Platform**

Linux, CuraEngine command line compiled with gcc (ENABLE_ARCUS off)

**Qt**

N/A

**PyQt**

N/A

**Display Driver**

N/A

**Steps to Reproduce**

1. Slice a file that takes more than an hour to print.
2. Inspect the console log, compare the "Print time (s)" to "Print time (hr|min|s)"
3. Notice these do not match

**Actual Results**

```
Print time (s): 87813
Print time (hr|min|s): 24h 0m 23s
```

**Expected results**

```
Print time (s): 87813
Print time (hr|min|s): 24h 23m 33s
```

**Additional Information**

It seems the minutes are being shown as seconds, and the minutes are always zero in "Print time (hr|min|s)"

For the example above, here is the time computation:

```
(24h * 60 * 60) + (23m * 60) + 33s =
86400s + 1380s + 33s =
87813s
```

**Comment by rburema** [comment]
Since I just merged your PR, this issue can be closed.
