### ISSUE TITLE
[4.6.0] slicer produces gap in wall

### ISSUE THREAD

**Issue by sjoerdtimmer** [Ultimaker/CuraEngine#1245]
**Application Version**
4.6 but I've seen it in the past too

**Platform**
All

**Display Driver**
Not important

**Steps to Reproduce**
Download Roller_insert_485.stl from https://www.thingiverse.com/thing:3209211/files
Slice wit 0.25 initial layer and 0.2 layer height

**Actual Results**
Layer 66 is disconnected from the previous layer except for a few small points where the wall touches the infill of the layer below. 

**Expected results**
Some extra plastic needs to be printed in layers 65 and below to make the model part above it connect to it. 

**Additional Information**
Skin expand settings don't fix this because there is no skin to expand. Maybe a concept like roof-wall should be introduced which counts as skin when generating the expanded skin area.
Alternate extra wall and print thin walls also don't affect this behaviour.

My current work-around is to set skin wall count to 5 but that shouldn't be necessary and for large models it would be very wasteful.

**Comment by smartavionics** [comment]
A common solution to this problem is to include in the model a skin across the hole so that the smaller diameter upper part is not printed on air. After printing, the skin across the hole is removed.

Here is an example of doing that...

![Screenshot_2020-04-27_21-38-24](https://user-images.githubusercontent.com/585618/80418548-8178b200-88cf-11ea-8f9d-49acb1e90649.png)

![Screenshot_2020-04-27_21-38-37](https://user-images.githubusercontent.com/585618/80418539-7faeee80-88cf-11ea-921f-e449cd5d777a.png)

**Comment by sjoerdtimmer** [comment]
It's certainly possible to work around this,
but wouldn't it be nice if cura sliced it correctly in the first place?

**Comment by smartavionics** [comment]
How do you mean correctly? That model, like a lot of models is not really suitable for fdm printing. If you look at the mesh you can see it is made from two, overlapping, volumes. Using the cura mesh tools you can split the model into separate parts and then it does actually become easier to print...

![Screenshot_2020-04-28_09-03-41](https://user-images.githubusercontent.com/585618/80463147-ad2b8480-892f-11ea-87ad-938624d3d49c.png)


![Screenshot_2020-04-28_09-07-39](https://user-images.githubusercontent.com/585618/80463190-c3d1db80-892f-11ea-9b9a-e456a7613e00.png)

**Comment by sjoerdtimmer** [comment]
Sorry, my bad. Because it looked solid in the preview I had assumed that the model was correct.
