### ISSUE TITLE
what is top_reference_wall_idx/bottom_reference_wall_idx ?

### ISSUE THREAD

**Issue by sscoder-3d** [Ultimaker/CuraEngine#1247]
"class SkinInfillAreaComputation" has two member top_reference_wall_idx and bottom_reference_wall_idx。

1. what are geometric distribution ？ 
2. why need them ？

**Comment by Ghostkeeper** [comment]
Imagine an L shaped model, standing upright on your build plate. This has a few bits of skin that are adjacent to infill: The skin that is used to close the top side of the horizontal part of the L.

The skin is not just generated directly underneath the air. Cura makes the skin there continue underneath the walls of the top part of the L. This makes the corner stronger. The skin is generated using one of the inner walls of the part above it. These two fields refer to which wall to use (starting counting from outside to inside) as starting point for splitting the skin off from the infill.
