### ISSUE TITLE
failed to read config

### ISSUE THREAD

**Issue by RFranta** [Ultimaker/CuraEngine#125]
I tried to use several config files and output is everytime the same: 
Default config 'default.cfg' not used
Config(testConfig.ini): Line 1: No key value pair found
Failed to read config 'testConfig.ini'
Failed to load model: testModel.stl

Everytime No key value found and failed to read config. I tried several files exported by Cura, but it still doesnt work. I am using Cygwin (or command line) in Win7. Example of command:
./CuraEngine.exe -c testConfig.ini -o outputFile.gcode inputFile.stl

**Comment by debakantasandha** [comment]
Hi Daid,
I'm using Cura-15.04.3 and using CuraEngine.exe  -o outputFile.gcode inputFile.stl command in CMD command prompt.
Getting Default config 'default.cfg' not used message along with GNU Affero General Public License.
Please guide us to overcome this issue and give the exact command to generate a gcode file from stl, obj files etc.

Thanks
Debakanta
