### ISSUE TITLE
Cura Z-lift in more places.

### ISSUE THREAD

**Issue by thantik** [Ultimaker/CuraEngine#126]
would you be willing to change Cura so that it z-lifts in more places than it currently does?  I'm getting a lot of instances where Cura will do a fast travel over infill, and make a horrible grinding noise as it passes the infill.  Any way to attach z-lift so that it happens any time filament is retracted?

**Comment by BagelOrb** [comment]
Please do!

**Comment by Dolpin** [comment]
I currently experience the same bug on with curaEngine. It does a z-hop when retracting, but moves over infill without performing a z hop. This causes the nozzle to travel very fast over the infill, which causes a lot of stress on the mechanism. I would expect that the z-hop will be performed on every travel move.

This is a g-code showing the issue:

G1 F1800 E566.46388
G1 Z1.600
G0 F7800 X-26.215 Y-8.119
G1 Z0.600
G1 F1800 E570.96388
G1 F1740 X-26.635 Y-9.132 E571.01859
G1 X-27.302 Y-10.003 E571.07332
G1 X-28.173 Y-10.671 E571.12808
G1 X-29.187 Y-11.090 E571.18282
G1 X-30.274 Y-11.233 E571.23752
G1 X-31.361 Y-11.090 E571.29221
G1 X-32.375 Y-10.671 E571.34695
G1 X-33.245 Y-10.003 E571.40167
G1 X-33.913 Y-9.132 E571.45644
G1 X-34.333 Y-8.119 E571.51115
G1 X-34.476 Y-7.031 E571.56589
G1 X-34.333 Y-5.944 E571.62059
G1 X-33.913 Y-4.930 E571.67535
G1 X-33.245 Y-4.060 E571.73007
G1 X-32.375 Y-3.392 E571.78480
G1 X-31.361 Y-2.973 E571.83953
G1 X-30.274 Y-2.829 E571.89424
G1 X-29.187 Y-2.973 E571.94894
G1 X-28.173 Y-3.392 E572.00368
G1 X-27.302 Y-4.060 E572.05844
G1 X-26.635 Y-4.930 E572.11313
G1 X-26.215 Y-5.944 E572.16789
G1 X-26.072 Y-7.031 E572.22259
G1 X-26.215 Y-8.119 E572.27734
G0 F7800 X3.496 Y26.738
G1 F1740 X2.828 Y27.609 E572.33210
G1 X2.409 Y28.623 E572.38684

**Comment by CCS86** [comment]
I think the idea with combing is to keep the nozzle in contact with the
print to prevent oozing, and has never lifted.

I'd say that it only causes stress if you are over extruding.

If a combing lift is implemented, it should be optional.

**Comment by Dolpin** [comment]
The nozzle only keeps in contact when printing top or bottom layers, also creating scars in this process of travelling without lift

The nozzle does not keep in contact with the print when printing infill 

I do not print 100% infill but mostly between 25 and 60% depending on the structural strength. The nozzle actually drags over the infill all the way from one side to the other at a fast speed without any lift

**Comment by BagelOrb** [comment]
Some of the problems of the original poster are solved by the following commit: https://github.com/Ultimaker/CuraEngine/pull/245

In combination with https://github.com/Ultimaker/CuraEngine/pull/247 

You should set combing to false and retraction to true.

**Comment by Dolpin** [comment]
Combing is off and retraction is on in my settings.

With the new update on commit 247 this issue should be solved indeed, because the filament will always retract on travel moves (greater then the set distance) and this then also applies for retractions when printing infill. 

I shal l check with the latest update

Verstuurd vanaf mijn iPad

**Comment by BagelOrb** [comment]
Keep in mind you should update to at least commit https://github.com/Ultimaker/CuraEngine/commit/8a2ca6230519ecda45a434a9bf85f640827d986e

There I've solved some issue where there would be too many z hops.

**Comment by Dolpin** [comment]
Ok, I will wait for the next release which includes this commit

Verstuurd vanaf mijn iPad
