### ISSUE TITLE
ERROR: Trying to retrieve setting with no value given: 'machine_extruder_count'

### ISSUE THREAD

**Issue by emrem6** [Ultimaker/CuraEngine#1263]
**Application Version**
last Version

**Platform**
Ubuntu

**Steps to Reproduce**
Input in Commandline:
 ./build/CuraEngine slice -v -j ./definitions/fdmextruder.def.json -o test.gcode -l candice-holder.stl 

**Actual Results**
[ERROR] Trying to retrieve setting with no value given: 'machine_extruder_count'

**Expected results**
GCODE should be generated

**Additional Information**

**Comment by rburema** [comment]
Use `fdmprinter.def.json`, not `fdmextruder.def.json`.

(Also, for real printing, you might want to use your own printers' definition, not the 'base' one.)
