### ISSUE TITLE
Subvolume division of 3D model

### ISSUE THREAD

**Issue by abtionlove** [Ultimaker/CuraEngine#1270]
Does the latest version of curaengine have the function of decomposing 3D model, dividing sub volume and slicing?

**Comment by nallath** [comment]
Could you explain what you mean a bit more extensive? I can think of a number of different interpretations.

**Comment by abtionlove** [comment]
> 您能解释一下您的意思吗？我可以想到许多不同的解释。

Whether curaengine divides the complex 3D model into subvolumes, and then processes the subvolumes separately.

**Comment by nallath** [comment]
It can't do this automatically, but you can do this by using "modifier meshes". An example of that can be seen on https://www.youtube.com/watch?v=PUwf79wySUY

**Comment by abtionlove** [comment]
> It can't do this automatically, but you can do this by using "modifier meshes". An example of that can be seen on https://www.youtube.com/watch?v=PUwf79wySUY

Hello, first of all, thank you. Can you elaborate? I can't understand. I can't open the website you gave me.

**Comment by nallath** [comment]
Can you access this? https://support.ultimaker.com/hc/en-us/articles/360013370140-How-to-adjust-print-settings-of-a-part-of-my-model-in-Ultimaker-Cura

**Comment by abtionlove** [comment]
> Can you access this? https://support.ultimaker.com/hc/en-us/articles/360013370140-How-to-adjust-print-settings-of-a-part-of-my-model-in-Ultimaker-Cura

Yes, thank you very much
