### ISSUE TITLE
Does CuraEngine ignore objects outside build plate?

### ISSUE THREAD

**Issue by CutAs** [Ultimaker/CuraEngine#1274]
Before I put my 3D printer for torture, I have a special case where I'm not in control of the actual size of the object, and it sometimes goes out of bounds. I don't specifically care if that will result in an error of the shape itself. 

Cura GUI would not slice such object but CuraEngine does. I'm wondering if it will just print what fits on the buildplate or will it start bashing the motors against the wall/give errors? 

Thanks for saving my hardware.

**Comment by BagelOrb** [comment]
CuraEngine does not care about the limitations of the printer. It will start bashing the print head into the sides of the printer. Beware!
