### ISSUE TITLE
[ERROR] Couldn't find extruder.def.json file for extruder 0

### ISSUE THREAD

**Issue by callmebg** [Ultimaker/CuraEngine#1292]
Help me，please！
When i build and run curaengine.exe in terminal, i get some bugs. I sure the json and stl exist.
What should i do? 
or Who can give me a project that can run successfully in vs 2017?
![TIM图片20200714211419](https://user-images.githubusercontent.com/30586666/87430604-0b573200-c618-11ea-9013-ed7d4558df8a.png)

**Comment by rburema** [comment]
You should be able to get those definition (.json) files from the main Cura repository for different printers. Replicate the folder structure found there (`./definitions`, `./extruders`), and you should be good. This is because the fdmprinter file refers to fdmextruder (file).

**Comment by callmebg** [comment]
> 
> 
> You should be able to get those definition (.json) files from the main Cura repository for different printers. Replicate the folder structure found there (`./definitions`, `./extruders`), and you should be good. This is because the fdmprinter file refers to fdmextruder (file).

cool！it works！thank you
