### ISSUE TITLE
Assigning extruders for different feature types

### ISSUE THREAD

**Issue by paleajed** [Ultimaker/CuraEngine#130]
Wouldnt it be interesting to be able to assign a certain extruder to the different components of a print (support, raft, ooze shield come to mind)?
I am trying to print decent PVA supports with my Felix 3.0 dual-extruder setup and since there is only one extruder choice setting for support, the raft and ooze shield are printed with the same extruder.
As for the raft, when printed in PVA, its too flexible and the PLA used for the main piece on top doesnt stick well enough, thus defeating the purpose of using a raft.
As for the ooze shield, the PVA is too flexible and doesnt hold back the ooze as well as a more rigid PLA shield.  Also building an ooze shield in support material makes it necessary to switch extruders every layer.  If it were made in the main material, layers without other support material would not need a switch to happen!

It would be a godsend to be able to set these extruder assignments, and since its probably not a big change to the code (Im a programmer myself also) I hope itll be possible to make this happen!

**Comment by BagelOrb** [comment]
Implemented
