### ISSUE TITLE
cura-engine can't slice this stl file

### ISSUE THREAD

**Issue by hyuntoe** [Ultimaker/CuraEngine#132]
https://www.dropbox.com/s/3bw1ecoo8z3yo9q/le_fabshop_stretchlet_mini.stl?dl=0

I tried various version of cura,
only success on cura 12.07 for windows

failed on below versions
cura 14.xx for windows : 
cura 14.xx for linux
cura 13.xx for windows : can't load modeling

in cura-made gcode, 1~4 layer is empty. so can't print at my mendel.

I checked stl file by solid inspector on sketchup14 and meshlab

test it please.
I attatched my dropbox's link.

**Comment by BagelOrb** [comment]
Could you provide a better link to the model? This one is not working.
(I'm closing this issue untill then)
