### ISSUE TITLE
CuraEngine 4.5.0 built on Raspberry Pi gives errors

### ISSUE THREAD

**Issue by jorythompson** [Ultimaker/CuraEngine#1327]
I have built CuraEngine 4.5.0 for Raspbian 10 (Buster)
When I try to run it from the command line, I get the following error(s):

pi@repetier:~/CuraEngine-4.5.0/build $ ./CuraEngine -p -v -c "/home/pi/.local/share/RepetierHost/cura.ini" -s posx=0 -s posy=0 -o "/home/pi/.local/share/RepetierHost/composition.gcode" "/home/pi/.local/share/RepetierHost/composition0.stl"

Cura_SteamEngine version master
Copyright (C) 2019 Ultimaker

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
[ERROR] Unknown command: -p
[ERROR] Command called:
[ERROR] ./CuraEngine [ERROR] -p [ERROR] -v [ERROR] -c [ERROR] /home/pi/.local/share/RepetierHost/cura.ini [ERROR] -s [ERROR] posx=0 [ERROR] -s [ERROR] posy=0 [ERROR] -o [ERROR] /home/pi/.local/share/RepetierHost/composition.gcode [ERROR] /home/pi/.local/share/RepetierHost/composition0.stl [ERROR]

usage:
CuraEngine help
        Show this help message

CuraEngine connect <host>[:<port>] [-j <settings.def.json>]
  --connect <host>[:<port>]
        Connect to <host> via a command socket,
        instead of passing information via the command line
  -v
        Increase the verbose level (show log messages).
  -m<thread_count>
        Set the desired number of threads. Supports only a single digit.

CuraEngine slice [-v] [-p] [-j <settings.json>] [-s <settingkey>=<value>] [-g] [-e<extruder_nr>] [-o <output.gcode>] [-l <model.stl>] [--next]
  -v
        Increase the verbose level (show log messages).
  -m<thread_count>
        Set the desired number of threads.
  -p
        Log progress information.
  -j
        Load settings.def.json file to register all settings and their defaults.
  -s <setting>=<value>
        Set a setting to a value for the last supplied object,

**Comment by nallath** [comment]
I don't know what ini file you are providing, but CuraEngine hasn't supported ini files since 2.1 (2-3 years i think?) 

This is also what the log is telling you. You need to provide default settings with a definition file. You can read a bit more about it on https://github.com/Ultimaker/CuraEngine/#running
