### ISSUE TITLE
Problem: starting top skin in the middle infill cells

### ISSUE THREAD

**Issue by fjriosp** [Ultimaker/CuraEngine#135]
I've had some issues printing simple parts like a small cube over a bigger one.

With a low infill (10%) there appears some gaps where the cubes intersects, inspecting the gcode generated by Cura I found that the top layer starts to print in the air (over a gap in the infill) causing the filament to drop down and making a gap in the surface of the part.

This is the part:
![part](https://cloud.githubusercontent.com/assets/6414473/4782885/b6128036-5d0b-11e4-8c5d-c82f42c0dd7e.png)

This is the GCode generated by Cura (tested in 14.09 and devel versions):
![cura_gcode](https://cloud.githubusercontent.com/assets/6414473/4782887/cfe4d6ee-5d0b-11e4-9eec-80691694eaa4.png)
![cura_gcode2](https://cloud.githubusercontent.com/assets/6414473/4782888/cfe844f0-5d0b-11e4-8503-ee54cff1a7f1.png)

And this is my proposal:
![cura_gcode_proposed](https://cloud.githubusercontent.com/assets/6414473/4782889/db113cce-5d0b-11e4-8db0-68fbbf3dd157.png)
![cura_gcode2_proposed](https://cloud.githubusercontent.com/assets/6414473/4782890/db129e52-5d0b-11e4-85b6-dd495568a456.png)

Thanks a lot.

**Comment by cscott** [comment]
Perimeter around the infill sounds reasonable.  Also, I believe that Cura usually draws the infill here *before* that perimeter.  It would be better in this case to draw the special "infill perimeter" *first*, so that it provides an edge for the infill to adhere to.

**Comment by BagelOrb** [comment]
It is hard to not let the infill perimeter overlap with the outer perimeters...

**Comment by BagelOrb** [comment]
![img_20150420_135923994](https://cloud.githubusercontent.com/assets/8895761/7229641/511d0170-e766-11e4-95a4-c532215d9ad6.jpg)

Just need to add the option in the frontend...
