### ISSUE TITLE
Absolute extruder coordinates should be reset and not grow unbounded.

### ISSUE THREAD

**Issue by ambrop72** [Ultimaker/CuraEngine#14]
The E coordinates should be reset occasionally so as not to grow too large and cause precision problems. Suppose the firmware parses the E coordinates into a single-precision float, and the extruder has 800 steps/mm. When the E coordinate is above 21 meters (2^24*(1mm/800)), the firmware will effectively round it to 2 steps (or 4, 8, etc. as the numbers grow larger).

**Comment by mtnbkrrick** [comment]
> I think the G92 should be reset must faster. Or the 5 digit resolution is overkill.
> The G92 E0 is handled in the planner and will not cause micro-delays.

I am getting micro delays every-time it does a G92 E0 and it leaves a zit.  Any thoughts for a way around this?
