### ISSUE TITLE
Tree Support: Support Floor missing every second layer

### ISSUE THREAD

**Issue by ThomasRahm** [Ultimaker/CuraEngine#1402]
**Application Version**
4.7.1

**Platform**
Windows 10

**Steps to Reproduce**
Slice a model with Tree Support and Support Floor enabled.

**Actual Results**
Every second layer does not contain a Support Floor

**Expected results**
Every layer up to Support Floor Thickness worth of layers should have a support floor.

**Additional Information**
![grafik](https://user-images.githubusercontent.com/67757218/106661364-672bdd00-65a1-11eb-8463-89bb5eb25a64.png)

PS. I found the issue and will link a pull request shortly.

**Comment by Ghostkeeper** [comment]
Hmm, I'm getting different layers, but a problem nonetheless, indeed! Only seems to happen with linear patterns, not concentric.

![image](https://user-images.githubusercontent.com/2448634/107359895-895bb880-6ad5-11eb-9e22-7d16f9e272b7.png)
