### ISSUE TITLE
how to build CuraEngine4.8 in VS2017

### ISSUE THREAD

**Issue by lixiaodao1234** [Ultimaker/CuraEngine#1450]
**Application Version**

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by lixiaodao1234** [comment]
please help me

**Comment by jellespijker** [comment]
Take a look at the documentation about running Cura from source: https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source-on-Windows
