### ISSUE TITLE
brew install CuraEngine - can't find or open JSON file

### ISSUE THREAD

**Issue by NGK98** [Ultimaker/CuraEngine#1456]
My team and I are mechanical engineers and are not software strong, but need to build an automation for our 3D printing workflow. I am trying to get CuraEngine set up on my mac (MacOS Catalina, version: 10.15.7). I used brew install CuraEngine (trying to get around a libArcus issue I am having https://github.com/Ultimaker/libArcus/issues/118). When running the CuraEngine slice command the following output happens where I am getting errors about finding and opening the JSON file but then it looks like it is still able to produce the gcode.. Can someone tell me if this is working??

**Terminal**
Natalie@Nats-MBP Cura % CuraEngine slice -v -j resources/definitions/ultimaker2_extended.def.json -l ~/Desktop/Scan1.stl -o ~/Desktop/outputGcode1.gcode

Cura_SteamEngine version master
Copyright (C) 2020 Ultimaker

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
[WARNING] Unrecognized data type in JSON setting machine_disallowed_areas
[WARNING] Unrecognized data type in JSON setting nozzle_disallowed_areas
[WARNING] Unrecognized data type in JSON setting machine_head_with_fans_polygon
[WARNING] JSON setting material_print_temperature has no default_value!
[WARNING] JSON setting material_bed_temperature has no default_value!
[WARNING] JSON setting material_bed_temperature_layer_0 has no default_value!
[WARNING] JSON setting material_standby_temperature has no default_value!
[WARNING] JSON setting extruder_prime_pos_y has no default_value!
[WARNING] JSON setting extruder_prime_pos_x has no default_value!
[WARNING] JSON setting relative_extrusion has no default_value!
[ERROR] Couldn't find definition file with ID: ultimaker2_extruder_0
[ERROR] Couldn't open JSON file: 
[WARNING] JSON setting machine_start_gcode has no default_value!
[WARNING] JSON setting machine_end_gcode has no default_value!
[WARNING] Unrecognized data type in JSON setting machine_head_with_fans_polygon
[WARNING] JSON setting gantry_height has no default_value!
[WARNING] Unrecognized data type in JSON setting machine_disallowed_areas
[ERROR] Couldn't find definition file with ID: ultimaker2_extended_extruder_0
[ERROR] Couldn't open JSON file: 
[WARNING] Mesh has disconnected faces!
loading '/Users/user/Desktop/Scan1.stl' took 0.038 seconds
Loaded from disk in 0.062s
[WARNING]  -s mesh_position_y="0" -s center_object="false" -s small_feature_speed_factor_0="50" -s small_feature_speed_factor="50" -s wipe_hop_speed="10" -s wipe_pause="0" -s wipe_retraction_prime_speed="2" -s wipe_retraction_extra_prime_amount="0" -s wipe_retraction_enable="true" -s clean_between_layers="false" -s bridge_skin_density_3="80" -s bridge_skin_density_2="75" -s bridge_skin_material_flow_2="100" -s bridge_skin_speed_2="25" -s bridge_enable_more_layers="true" -s bridge_skin_density="100" -s bridge_skin_material_flow="60" -s bridge_wall_material_flow="50" -s bridge_wall_coast="100" -s bridge_sparse_infill_max_density="0" -s bridge_skin_support_threshold="50" -s bridge_settings_enabled="false" -s adaptive_layer_height_threshold="0.2" -s wireframe_straight_before_down="20" -s wireframe_drag_along="0.6" -s wireframe_top_jump="0.6" -s wireframe_up_half_speed="0.3" -s wireframe_flat_delay="0.1" -s wireframe_bottom_delay="0" -s wireframe_flow_connection="100" -s wireframe_printspeed_up="5" -s wireframe_printspeed_bottom="5" -s wireframe_enabled="false" -s magic_fuzzy_skin_enabled="false" -s support_conical_min_width="5" -s support_conical_angle="30" -s adaptive_layer_height_variation="0.1" -s cross_infill_density_image="" -s coasting_speed="90" -s coasting_min_volume="0.8" -s coasting_enable="false" -s conical_overhang_hole_size="0" -s conical_overhang_enabled="false" -s wireframe_printspeed_flat="5" -s draft_shield_height_limitation="full" -s draft_shield_dist="10" -s draft_shield_enabled="false" -s support_zag_skip_count="5" -s support_skip_some_zags="false" -s minimum_polygon_circumference="1" -s material_flow_temp_graph="[[3.5,200],[7.0,240]]" -s infill_enable_travel_optimization="false" -s roofing_angles="[ ]" -s roofing_pattern="lines" -s roofing_line_width="0.4" -s slicing_tolerance="middle" -s smooth_spiralized_contours="true" -s magic_spiralize="false" -s magic_mesh_surface_mode="normal" -s mold_angle="40" -s mold_roof_height="0.5" -s layer_height="0.1" -s material_break_preparation_retracted_position="-16" -s infill_mesh="false" -s support_extruder_nr_layer_0="0" -s meshfix_maximum_travel_resolution="1" -s flow_rate_extrusion_offset_factor="100" -s acceleration_wall_x="3000" -s carve_multiple_volumes="true" -s switch_extruder_extra_prime_amount="0" -s machine_nozzle_temp_enabled="true" -s material_maximum_park_duration="300" -s skirt_brim_speed="30" -s switch_extruder_retraction_amount="20" -s ooze_shield_dist="2" -s machine_endstop_positive_direction_x="false" -s ooze_shield_angle="60" -s support_line_width="0.4" -s ooze_shield_enabled="false" -s mesh_position_x="0" -s prime_tower_position_y="200" -s bridge_wall_min_length="5" -s prime_tower_position_x="200" -s raft_surface_acceleration="3000" -s raft_base_line_width="0.8" -s machine_nozzle_heat_up_speed="2" -s material_flush_purge_length="60" -s raft_interface_line_spacing="0.9" -s raft_interface_thickness="0.15" -s speed_topbottom="30" -s raft_smoothing="5" -s brim_replaces_support="true" -s print_sequence="all_at_once" -s acceleration_support_infill="3000" -s brim_gap="0" -s raft_surface_layers="2" -s skirt_brim_minimal_length="250" -s mold_width="5" -s adhesion_extruder_nr="0" -s extruder_prime_pos_y="0" -s meshfix_keep_open_polygons="false" -s prime_blob_enable="false" -s support_mesh_drop_down="true" -s extruder_prime_pos_z="0" -s support_tower_roof_angle="65" -s support_tower_diameter="3" -s support_use_towers="true" -s minimum_roof_area="1" -s jerk_topbottom="20" -s remove_empty_first_layers="true" -s prime_tower_size="20" -s support_mesh="false" -s support_roof_pattern="concentric" -s support_bottom_line_distance="0.4" -s support_interface_skip_height="0.3" -s support_bottom_enable="false" -s minimum_support_area="0" -s support_roof_height="1" -s material_bed_temperature_layer_0="60" -s support_infill_sparse_thickness="0.1" -s wireframe_fall_down="0.5" -s support_offset="0" -s wipe_hop_amount="1" -s support_join_distance="2" -s support_bottom_stair_step_min_slope="10" -s support_bottom_stair_step_width="5" -s support_xy_distance_overhang="0.2" -s machine_nozzle_tip_outer_diameter="1" -s min_infill_area="0" -s support_xy_overrides_z="z_overrides_xy" -s support_xy_distance="0.7" -s machine_steps_per_mm_e="1600" -s material_crystallinity="false" -s support_bottom_distance="0.1" -s support_brim_enable="false" -s support_infill_angles="[ ]" -s raft_base_fan_speed="0" -s support_tree_collision_resolution="0.4" -s support_tree_branch_diameter_angle="5" -s machine_steps_per_mm_y="50" -s support_tree_branch_diameter="2" -s support_tree_branch_distance="1" -s machine_max_jerk_z="0.4" -s support_tree_angle="40" -s support_structure="normal" -s support_enable="false" -s cool_min_layer_time="5" -s cool_min_layer_time_fan_speed_max="10" -s meshfix_maximum_deviation="0.025" -s wall_overhang_angle="90" -s cool_fan_enabled="true" -s cool_fan_speed_max="100" -s wipe_move_distance="20" -s cool_fan_speed_min="100" -s support_bottom_extruder_nr="0" -s jerk_wall_0="20" -s retraction_hop="1" -s material_print_temp_wait="true" -s support_roof_angles="[ ]" -s switch_extruder_retraction_speed="20" -s acceleration_roofing="3000" -s retraction_hop_enabled="false" -s wall_x_extruder_nr="-1" -s switch_extruder_prime_speed="20" -s build_volume_temperature="0" -s extruder_prime_pos_x="0" -s layer_start_y="0" -s machine_min_cool_heat_time_window="50" -s layer_start_x="0" -s raft_interface_speed="15" -s support_meshes_present="false" -s travel_avoid_distance="0.625" -s acceleration_infill="3000" -s travel_avoid_supports="false" -s raft_surface_speed="20" -s machine_height="305" -s travel_retract_before_outer_wall="false" -s material_flow_layer_0="100" -s retraction_combing="all" -s support_fan_enable="false" -s retraction_extrusion_window="4.5" -s skirt_line_count="1" -s retraction_count_max="90" -s retraction_min_travel="1.5" -s retraction_extra_prime_amount="0" -s cool_min_speed="10" -s z_seam_type="sharpest_corner" -s retraction_prime_speed="25" -s retraction_amount="6.5" -s support_line_distance="2.66" -s retraction_enable="true" -s mold_enabled="false" -s skin_edge_support_layers="4" -s support_type="everywhere" -s jerk_travel_layer_0="20" -s wireframe_roof_inset="3" -s material_anti_ooze_retracted_position="-4" -s hole_xy_offset="0" -s jerk_print_layer_0="20" -s jerk_travel="30" -s skin_outline_count="1" -s jerk_prime_tower="20" -s jerk_support_bottom="20" -s raft_interface_fan_speed="0" -s jerk_roofing="20" -s jerk_wall_x="20" -s jerk_infill="20" -s jerk_enabled="false" -s wipe_brush_pos_x="100" -s machine_nozzle_id="unknown" -s acceleration_travel_layer_0="3000" -s gradual_support_infill_steps="0" -s ironing_enabled="false" -s support_bottom_material_flow="100" -s acceleration_travel="5000" -s wireframe_roof_drag_along="0.8" -s material_break_preparation_speed="2" -s material_end_of_filament_purge_length="20" -s acceleration_support_bottom="3000" -s support_roof_offset="0" -s acceleration_support_roof="3000" -s acceleration_topbottom="3000" -s acceleration_wall_0="3000" -s support_roof_extruder_nr="0" -s acceleration_enabled="false" -s speed_equalize_flow_max="150" -s draft_shield_height="10" -s z_seam_x="100" -s machine_always_write_active_tool="false" -s retraction_combing_max_distance="0" -s speed_equalize_flow_enabled="false" -s speed_z_hop="10" -s infill_mesh_order="0" -s support_angle="50" -s raft_base_speed="15" -s layer_0_z_overlap="0.22" -s ironing_pattern="zigzag" -s speed_travel="120" -s support_infill_extruder_nr="0" -s speed_prime_tower="60" -s material_extrusion_cool_down_speed="0.7" -s speed_support_bottom="40" -s max_extrusion_before_wipe="10" -s raft_base_line_spacing="1.6" -s speed_support_infill="60" -s support_bottom_stair_step_height="0.3" -s brim_outside_only="true" -s material_standby_temperature="150" -s speed_roofing="25" -s wireframe_nozzle_clearance="1" -s speed_infill="60" -s meshfix_union_all_remove_holes="false" -s mesh_rotation_matrix="[[1,0,0], [0,1,0], [0,0,1]]" -s machine_max_acceleration_z="100" -s support_wall_count="1" -s flow_rate_max_extrusion_offset="0" -s material_diameter="2.85" -s top_skin_expand_distance="1" -s acceleration_ironing="3000" -s prime_tower_flow="100" -s bridge_fan_speed="100" -s support_material_flow="100" -s roofing_material_flow="100" -s raft_base_jerk="20" -s retract_at_layer_change="false" -s machine_buildplate_type="glass" -s speed_wall_x="60" -s alternate_carve_order="true" -s machine_max_feedrate_y="300" -s support_roof_material_flow="100" -s wipe_retraction_retract_speed="3" -s multiple_mesh_overlap="0.15" -s skin_material_flow="100" -s min_skin_width_for_expansion="0" -s wall_x_material_flow="100" -s infill_pattern="grid" -s connect_skin_polygons="false" -s material_break_preparation_temperature="50" -s bridge_skin_speed="15" -s skirt_brim_material_flow="100" -s infill_material_flow="100" -s machine_max_jerk_e="5" -s raft_margin="15" -s material_end_of_filament_purge_speed="0.5" -s material_print_temperature_layer_0="215" -s top_bottom_extruder_nr="-1" -s wipe_retraction_amount="1" -s material_break_temperature="50" -s speed_travel_layer_0="60" -s z_seam_corner="z_seam_corner_inner" -s support_conical_enabled="false" -s material_anti_ooze_retraction_speed="5" -s raft_interface_line_width="0.7" -s infill_offset_x="0" -s gantry_height="1e+11" -s material_surface_energy="100" -s material_final_print_temperature="195" -s material_break_retracted_position="-50" -s material_initial_print_temperature="200" -s roofing_layer_count="0" -s speed_slowdown_layers="2" -s default_material_print_temperature="210" -s raft_surface_line_spacing="0.4" -s material_no_load_move_factor="0.94086" -s adaptive_layer_height_variation_step="0.01" -s raft_surface_jerk="20" -s infill_support_angle="40" -s meshfix_union_all="true" -s material_bed_temp_prepend="true" -s infill_before_walls="true" -s raft_airgap="0.3" -s material_flush_purge_speed="0.5" -s machine_show_variants="false" -s gradual_infill_steps="0" -s machine_nozzle_size="0.4" -s raft_interface_jerk="20" -s material_shrinkage_percentage="100" -s adhesion_type="brim" -s support_brim_line_count="20" -s cool_fan_speed_0="0" -s infill_support_enabled="false" -s infill_angles="[ ]" -s retraction_retract_speed="25" -s zig_zaggify_infill="false" -s infill_extruder_nr="-1" -s sub_div_rad_add="0.4" -s bottom_skin_preshrink="1" -s top_skin_preshrink="1" -s wireframe_flow_flat="100" -s speed_print_layer_0="30" -s default_material_bed_temperature="60" -s limit_support_retractions="true" -s machine_max_acceleration_e="10000" -s speed_ironing="20" -s bridge_fan_speed_3="0" -s wireframe_roof_outer_delay="0.2" -s ironing_inset="0.35" -s wall_min_flow="0" -s ironing_flow="10" -s infill_sparse_thickness="0.1" -s machine_extruders_shared_nozzle_initial_retraction="0" -s extruder_prime_pos_abs="false" -s material_adhesion_tendency="10" -s ironing_line_spacing="0.1" -s ironing_only_highest_layer="false" -s raft_surface_line_width="0.4" -s support_bottom_angles="[ ]" -s speed_support_roof="40" -s skin_no_small_gaps_heuristic="false" -s machine_steps_per_mm_z="50" -s skin_angles="[ ]" -s alternate_extra_perimeter="false" -s support_roof_enable="false" -s top_bottom_pattern_0="lines" -s wall_0_material_flow="100" -s raft_base_thickness="0.3" -s retraction_hop_after_extruder_switch="true" -s support_top_distance="0.1" -s wall_line_width_x="0.4" -s roofing_extruder_nr="-1" -s skirt_gap="3" -s retraction_hop_after_extruder_switch_height="1" -s acceleration_prime_tower="3000" -s wireframe_height="3" -s cross_support_density_image="" -s z_seam_relative="false" -s bottom_skin_expand_distance="1" -s bridge_skin_speed_3="15" -s magic_fuzzy_skin_point_dist="0.8" -s filter_out_tiny_gaps="true" -s machine_max_acceleration_x="9000" -s z_seam_y="100" -s machine_name="Ultimaker 2 Extended" -s adaptive_layer_height_enabled="false" -s support_connect_zigzags="true" -s jerk_support_roof="20" -s machine_extruder_count="1" -s xy_offset_layer_0="0" -s xy_offset="0" -s wall_min_flow_retract="false" -s anti_overhang_mesh="false" -s jerk_skirt_brim="20" -s machine_heat_zone_length="16" -s material_print_temperature="210" -s travel_compensate_overlapping_walls_0_enabled="true" -s machine_minimum_feedrate="0" -s optimize_wall_printing_order="false" -s machine_heated_bed="true" -s machine_use_extruder_offset_to_offset_coords="true" -s machine_shape="rectangular" -s wipe_hop_enable="true" -s zig_zaggify_support="false" -s material_bed_temp_wait="true" -s machine_depth="223" -s infill_multiplier="1" -s initial_layer_line_width_factor="100" -s machine_start_gcode="G28 ;Home
G1 Z15.0 F6000 ;Move the platform down 15mm
;Prime the extruder
G92 E0
G1 F200 E3
G92 E0" -s relative_extrusion="false" -s wall_0_inset="0" -s wall_0_wipe_dist="0.2" -s wireframe_printspeed_down="5" -s material_print_temp_prepend="true" -s machine_max_feedrate_z="40" -s wall_line_count="2" -s infill_line_distance="2" -s minimum_bottom_area="1" -s wall_0_extruder_nr="-1" -s support_supported_skin_fan_speed="100" -s infill_wall_line_count="0" -s support_initial_layer_line_distance="2.66" -s machine_firmware_retract="false" -s layer_height_0="0.3" -s travel_avoid_other_parts="true" -s acceleration_print_layer_0="3000" -s cross_infill_pocket_size="2" -s wall_line_width_0="0.4" -s machine_end_gcode="M104 S0
M140 S0
;Retract the filament
G92 E1
G1 E-1 F300
G28 X0 Y0
M84" -s machine_center_is_zero="false" -s extruders_enabled_count="1" -s wireframe_top_delay="0" -s machine_endstop_positive_direction_y="false" -s retraction_hop_only_when_collides="false" -s machine_feeder_wheel_diameter="10" -s magic_fuzzy_skin_outside_only="false" -s infill_line_width="0.4" -s support_bottom_line_width="0.4" -s machine_steps_per_mm_x="50" -s machine_max_jerk_xy="20" -s cutting_mesh="false" -s mesh_position_z="0" -s conical_overhang_angle="50" -s infill_overlap_mm="0.04" -s travel_compensate_overlapping_walls_x_enabled="true" -s machine_nozzle_head_distance="3" -s small_feature_max_length="0" -s skin_overlap_mm="0.02" -s machine_width="223" -s machine_max_feedrate_x="300" -s infill_randomize_start_location="false" -s top_layers="8" -s support_tower_maximum_supported_diameter="3" -s machine_acceleration="3000" -s fill_outline_gaps="false" -s cool_fan_full_layer="2" -s top_bottom_pattern="lines" -s skirt_brim_line_width="0.4" -s magic_fuzzy_skin_thickness="0.3" -s meshfix_extensive_stitching="false" -s material_flow_dependent_temperature="false" -s bottom_layers="6" -s infill_offset_y="0" -s brim_line_count="20" -s support_roof_line_distance="0.4" -s prime_tower_line_width="0.4" -s machine_max_feedrate_e="45" -s prime_tower_min_volume="6" -s material_bed_temperature="60" -s bridge_wall_speed="15" -s support_bottom_offset="0" -s prime_tower_brim_enable="false" -s gradual_infill_step_height="1.5" -s cool_lift_head="false" -s machine_extruders_share_heater="false" -s speed_wall_0="30" -s outer_inset_first="false" -s prime_tower_enable="false" -s raft_surface_thickness="0.1" -s prime_tower_wipe_enabled="true" -s fill_perimeter_gaps="everywhere" -s wipe_repeat_count="5" -s meshfix_maximum_resolution="0.5" -s gradual_support_infill_step_height="1" -s acceleration_skirt_brim="3000" -s machine_max_acceleration_y="9000" -s wall_overhang_speed_factor="100" -s jerk_support_infill="20" -s raft_surface_fan_speed="0" -s raft_interface_acceleration="3000" -s connect_infill_polygons="true" -s skin_line_width="0.4" -s raft_base_acceleration="3000" -s material_guid="" -s support_bottom_pattern="concentric" -s support_pattern="zigzag" -s coasting_volume="0.064" -s machine_endstop_positive_direction_z="true" -s infill_wipe_dist="0.04" -s material_break_speed="25" -s support_roof_line_width="0.4" -s machine_nozzle_cool_down_speed="2" -s support_bottom_height="1" -s machine_extruders_share_nozzle="false" -s machine_nozzle_expansion_angle="45" -s machine_heated_build_volume="false" -s jerk_ironing="20" -s wireframe_roof_fall_down="2" -s wireframe_strategy="compensate" -s machine_gcode_flavor="UltiGCode" -s bridge_skin_material_flow_3="110" -s bridge_fan_speed_2="0" -s initial_bottom_layers="6" -e0 -s machine_extruder_cooling_fan_number="0" -s extruder_prime_pos_x="0" -s machine_extruder_end_pos_y="0" -s machine_extruder_end_pos_abs="false" -s machine_extruder_start_pos_y="0" -s extruder_prime_pos_z="0" -s machine_extruder_start_pos_x="0" -s machine_extruder_start_pos_abs="false" -s machine_extruder_end_pos_x="0" -s machine_nozzle_offset_y="0" -s extruder_nr="0" -s machine_nozzle_size="0.4" -s extruder_prime_pos_y="0" -s machine_extruder_start_code="" -s machine_nozzle_offset_x="0" -s machine_extruder_end_code="" -s material_diameter="2.85" -s machine_nozzle_id="unknown" -g -e0 -l "0" -s machine_extruder_cooling_fan_number="0" -s extruder_prime_pos_x="0" -s machine_extruder_end_pos_y="0" -s machine_extruder_end_pos_abs="false" -s machine_extruder_start_pos_y="0" -s extruder_prime_pos_z="0" -s machine_extruder_start_pos_x="0" -s machine_extruder_start_pos_abs="false" -s machine_extruder_end_pos_x="0" -s machine_nozzle_offset_y="0" -s extruder_nr="0" -s machine_nozzle_size="0.4" -s extruder_prime_pos_y="0" -s machine_extruder_start_code="" -s machine_nozzle_offset_x="0" -s machine_extruder_end_code="" -s material_diameter="2.85" -s machine_nozzle_id="unknown"
Progress: start accomplished in 0.000s
Starting slice...
Slicing model...
slice of mesh took 0.130 seconds
slice make polygons took 0.033 seconds
Progress: slice accomplished in 0.164s
Starting layerparts...
Progress: layerparts accomplished in 0.104s
Starting inset+skin...
Layer count: 1047
Progress: inset+skin accomplished in 7.785s
Starting support...
Processing platform adhesion
Progress: support accomplished in 1.292s
Starting export...
Progress: export accomplished in 13.583s
Total time elapsed 22.95s.
Gcode header after slicing:
;FLAVOR:UltiGCode
;TIME:100390
;MATERIAL:207745
;MATERIAL2:0
;NOZZLE_DIAMETER:0.4
;MINX:63.692
;MINY:60.138
;MINZ:0.3
;MAXX:159.045
;MAXY:170.137
;MAXZ:104.9
End of gcode header.
Print time (s): 100390
Print time (hr|min|s): 27h 53m 10s
Filament (mm^3): 207745

**Comment by Ghostkeeper** [comment]
The warnings here are to be expected. CuraEngine doesn't know about all of the data types that Cura uses for its settings. In particular, Cura's front end needs to use a couple of settings to determine the disallowed areas. Those settings are lists of coordinates and CuraEngine doesn't understand them. CuraEngine also doesn't need to use them though (which is why we never implemented parsing those) so it's all good.

A bit more of a concern is that CuraEngine is not able to parse the `"value"` of these settings. Those are Python expressions and CuraEngine has no Python interpreter built-in.  It only uses `"default_value"`. It is warning you that you have a setting override in `ultimaker2.def.json` which is useless because it has no `"default_value"`. It'll continue to slice because it uses the default from `fdmprinter.def.json` then, but your slice result won't have the correct setting value.

It also can't find the `ultimaker2_extruder_0.def.json` file. It only looks in the same folder as the provided definition and in the working directory, so if the resource structure of Cura's front-end is left intact it will indeed not find this file. Instead it will use `fdmextruder.def.json` which is in the `definitions` folder. In this case this won't do you any harm though since `ultimaker2_extruder_0.def.json` doesn't seem to change any settings away from the defaults. But for other printers this could be problematic.

So in brief, it slices because it falls back to the `default_value`s in fdmprinter.def.json. There's no real need to be concerned, since your settings won't be perfect for the Ultimaker 2 anyway without also applying the profiles for the nozzle, material and quality you want to slice for. But it is something you might want to look at anyway, depending on your application.

**Comment by siamak06** [comment]
https://github.com/Ultimaker/Cura/tree/main/resources/definitions
