### ISSUE TITLE
extra perimeter at even layers for better infill-perimeter-cohesion

### ISSUE THREAD

**Issue by thawkins** [Ultimaker/CuraEngine#146]
CURA currently by neccessity overlaps the perimeter wall shells and the infill to maintain cohesion between the fill and the shell. However this can result in ridging inside the shell as the overlap area is painted twice with plastic on each layer. 

It would be usefull if instead of overlapping, cura added an extra shell loop on alternative layers and shrank the infill inside it, this would result in a one loop overlap between the shell material and the infill verticaly rather than horizontaly. Which would not result in double painting. 

Im have some prints where a pronounced ridge builds up, which either distorts the topfill, or get bulldozed out the sides and results in a messy surface, cutting back overlap to 1% reduces it considerably.

**Comment by BagelOrb** [comment]
The issue is implemented, but not enabled by default.
