### ISSUE TITLE
[4.10.0] Gaps in sliced mode at wall to floor/ceiling seam

### ISSUE THREAD

**Issue by mah115** [Ultimaker/CuraEngine#1472]
**Application Version**

4.10.0
**Platform**

Windows 10
**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

Slice attached project
**Actual Results**

Holes in the sliced model exterior.
**Expected results**

No holes in the sliced model
**Additional Information**

![image](https://user-images.githubusercontent.com/2501918/127038995-4bd7891b-e2ba-4567-96c6-3a3058ece897.png)
![image](https://user-images.githubusercontent.com/2501918/127039023-418d88c6-c02d-4e3b-a42d-2fd1adde972c.png)
Actual print:
![IMG_2009](https://user-images.githubusercontent.com/2501918/127039047-ab85fb84-b7af-4c10-b598-e56aba9c55b2.jpeg)

Comparison to PrusaSlic3r:
![image](https://user-images.githubusercontent.com/2501918/127039139-90cd8de4-ef1a-4ef6-ab33-2e4d9bf1d36b.png)
![image](https://user-images.githubusercontent.com/2501918/127039176-59e6c5b9-3774-433e-8f01-2bd459f61227.png)
[CURA_4.10_Gaps.zip](https://github.com/Ultimaker/CuraEngine/files/6880378/CURA_4.10_Gaps.zip)

**Comment by fvrmr** [comment]
Hi @mah115 if you change the `top removal width` to 0 the gaps will be gone. Let me know if that solves your problem.

**Comment by mah115** [comment]
> Hi @mah115 if you change the `top removal width` to 0 the gaps will be gone. Let me know if that solves your problem.

Confirm works. Thanks!
