### ISSUE TITLE
Documentation for the command line of CuraEngine

### ISSUE THREAD

**Issue by albertoxamin** [Ultimaker/CuraEngine#1480]
Hello I'm wondering if there is a documentation or wiki page with the parameters that can be used in the CuraEngine command line.
I'm familiar with the docs of slic3r that have some form of explanations for the parameters https://manual.slic3r.org/advanced/command-line

For example in my use case I'm looking into the following parameters:

- Rotation in 3D
- layer height
- infill pattern
- copies of the model

Is it possible to pass this parameters via cli?

**Comment by nallath** [comment]
Did you already have a look at https://github.com/Ultimaker/CuraEngine#running

You can provide every setting that is defined in https://github.com/Ultimaker/Cura/blob/master/resources/definitions/fdmprinter.def.json

There are also people that wrote wrappers to make it a bit easier to use: https://xyzdims.com/2021/03/24/3d-printing-cura-cli-wrapper-cura-slicer/
