### ISSUE TITLE
Cura-engine CLI make support with specific extruder and make part with other extruder.

### ISSUE THREAD

**Issue by yayati29** [Ultimaker/CuraEngine#1527]
Cannot make cura-engine slice to make support with specific extruder (extruder-0) and main part with extruder-1. 

Using this:
!CuraEngine slice -v -j "./definitions/ultimaker_s5.def.json" -s extruders_enabled_count="2"  -s support_enable="True" -l "./cad_files/1101311.stl" -o "yaya.gcode"

Although extruder 1 moves around the path but doesnt generate anything.

**Comment by Ghostkeeper** [comment]
Try this:

```
CuraEngine slice -v -j "./definitions/ultimaker_s5.def.json" -s support_enable="True" -e1 -l "./cad_files/1101311.stl" -o "yaya.gcode"
```

The `-e1` makes the model get printed with the second extruder. Since `support_extruder_nr` defaults to 0, that should still get printed with the first extruder.
