### ISSUE TITLE
Problem with min_feature_size

### ISSUE THREAD

**Issue by AlexandreSoete** [Ultimaker/CuraEngine#1549]
Hello,

I try ton use CuraEngine in CLI. I have install it.

Wheen I try to slice my stl, I have this error : Trying to retrieve setting with no value given: 'min_feature_size'

I use this file as configuration : https://github.com/Ultimaker/Cura/blob/master/resources/definitions/fdmprinter.def.json

in this file min_feature_size in defined in line 1246.

And my commande line : ./build_new/CuraEngine slice -p -o test.gcode -j fdmprinter.def.json -v -l "5dde888900639.stl"

What can I do ? Thanks ! 

**Platform**
CentOS Serveur

**Comment by Ghostkeeper** [comment]
Yeah, I found the issue. A `default_value` property was missing. This should always be present. I fixed it! Would you like to try again?
