### ISSUE TITLE
CuraEngine in the command line doesn't work

### ISSUE THREAD

**Issue by floxform** [Ultimaker/CuraEngine#1559]
Hello!

I've tried to use the CuraEngine in the Command line on Ubuntu lts 20.04.

->this is the command is used:
./build/CuraEngine slice -j ./settings.def.json -o output.gcode -l ~/Downloads/3DBenchy.stl 

-> This is the response:
[ERROR] Couldn't find definition file with ID: fdmextruder
[ERROR] Couldn't open JSON file: 
[WARNING] Unrecognized data type in JSON setting machine_disallowed_areas
[WARNING] Unrecognized data type in JSON setting nozzle_disallowed_areas
[WARNING] Unrecognized data type in JSON setting machine_head_with_fans_polygon
[WARNING] Mesh has overlapping faces!
[ERROR] Trying to retrieve setting with no value given: 'extruder_nr'

Has anyone an idea what's wrong with my settings.def.json ?; I've tried different ones, also the ones provided with Cura

Thanks.

**Comment by Ghostkeeper** [comment]
It's working fine for me.

I'm guessing that `settings.def.json` file inherits from `fdmextruder.def.json`, which is not found. When looking for definition files, CuraEngine will look into the directory where the .json file is located, as well as in the directories in the `CURA_ENGINE_SEARCH_PATH` environment variable. I suggest that you get Cura's source code, and set `CURA_ENGINE_SEARCH_PATH` to its [definitions directory](https://github.com/Ultimaker/Cura/tree/master/resources/definitions) if you want to use Cura's definition files. And you probably do want Cura's definition files, lest you have to write all those 588 setting definitions yourself.
