### ISSUE TITLE
Roofing doesn't work

### ISSUE THREAD

**Issue by Piezoid** [Ultimaker/CuraEngine#1568]
Roofing (aka Top Surface Skin) is not working, since (at least) the merge of Arachne in master.

**Steps to Reproduce**
Slice anything with `Top Surface Skin Layers` > 0 and assign different parameters to the roofing layers.

**Actual Results**
Top surface layers are printed the same way than any other top surfaces.

**Expected results**
Topmost surface layers should follow the roofing settings.

**Additional Information**
[When `generateRoofing` is called, `skin_part.skin_fill` is always empty](https://github.com/Ultimaker/CuraEngine/blob/master/src/skin.cpp#L312-L313). I couldn't find any other location where `skin_fill` is assigned/filled. Substituting `skin_part.skin_fill` with `skin_part.skin_fill` with `skin_part.outlines` resolves the issue but introduces others.

**Comment by Ghostkeeper** [comment]
Indeed, we already knew about this one too. See also https://github.com/Ultimaker/Cura/issues/11157. We have this in our backlog before the release.
