### ISSUE TITLE
Missing layer part holes

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/CuraEngine#159]
In the attached STL file, one of the nine holes in the top is missing.
The geometry is correct, and this can also be seen from the x-ray view (see below).
The behaviour is present in at least Cura 14.09 and 15.02.1.

It is no visualization issue.
x-ray) I have verified the geometry by hand and
toolpath) I have printed the object with the specific fault.

Could this be a clipperlib related issue?

![cura_problem](https://cloud.githubusercontent.com/assets/8895761/6326981/60ac04b4-bb57-11e4-8778-ec6280901ac6.png)
https://www.youmagine.com/designs/missing-layerpart-holes

**Comment by daid** [comment]
What happens if you disable "fix horrible type A"?

**Comment by BagelOrb** [comment]
Indeed disabling the option [combine-everything type-A] was the culprit.

The problem is therefore with with that option.
Why would this option break correct geometry?

**Comment by daid** [comment]
Because the normals of the inner cylinder are incorrect then (thus, an incorrect mesh)

**Comment by BagelOrb** [comment]
Is there a way in Cura to see what the normals are?
