### ISSUE TITLE
CuraEngine REST API or gRPC implementation for output data

### ISSUE THREAD

**Issue by 3d-printing-expert** [Ultimaker/CuraEngine#1616]
I want to send the output of the cura engine cli (time, material used etc.) to an external Rest API Server or with gRPC. How would you implement this?
Thanks.

**Comment by Ghostkeeper** [comment]
I would call CuraEngine from Python with the `subprocess` module, obtain the stdout output, and then make a POST request to the API with the g-code output in the body of the request (or in whatever the correct field is in that API). Is that what you mean?

I'm not sure why you'd be asking this here though. We're not here to provide help with your home automation system or anything. Maybe I'm misunderstanding what you meant to ask? Are you asking for a certain feature to be implemented?
