### ISSUE TITLE
 warning: the use of `tmpnam' is dangerous, better use `mkstemp'

### ISSUE THREAD

**Issue by oliv3r** [Ultimaker/CuraEngine#166]
We are currently using tmpnam, which is considered dangerous and the recommended method is mkstemp.

CMakeFiles/CuraEngine.dir/src/commandSocket.cpp.o: In function `cura::CommandSocket::beginGCode()':
commandSocket.cpp:(.text+0xd60): warning: the use of `tmpnam' is dangerous, better use `mkstemp'

**Comment by daid** [comment]
Read all the comments around that code ;-)
