### ISSUE TITLE
[Bug] "Infill Overlap" increases support areas.

### ISSUE THREAD

**Issue by ThomasRahm** [Ultimaker/CuraEngine#1670]
**Application Version**
5.0.0

**Actual Results**
When the support walls are calculated  [in AreaSupport::generateGradualSupport](https://github.com/Ultimaker/CuraEngine/blob/d002c2c331427ef2f0c29eb24541389626328244/src/support.cpp#L211), the support areas will be offset by overlap in `Infill::generateWallToolPaths`.
This causes the support area (not just the support infill area) to become larger.
While this does not matter most of the time, when the overlap is large, or the support area is small that can cause issues.
Examples:

![High Overlap Bugged](https://user-images.githubusercontent.com/67757218/170009908-4faa724c-e430-4f5c-85ab-7d357de7ed8a.PNG)

![Small area bugged](https://user-images.githubusercontent.com/67757218/170010127-a4984304-ac9a-44db-92b0-a7f11075b741.PNG)

**Expected results**

When setting the infill overlap used to calculate the walls in `AreaSupport::generateGradualSupport` to 0, the overlap is still correctly added, but the support area does not increase. See #1671.
This results in the previous examples to look like this instead:

![High Overlap Fixed](https://user-images.githubusercontent.com/67757218/170010659-2adc4e86-be55-46f5-bc18-85e2afb7c422.PNG)

The support infill will still overlap with the support walls:
![High Overlap Fixed lower](https://user-images.githubusercontent.com/67757218/170010670-53a36891-b1c9-485c-8ba0-9aaf3cf92ead.PNG)

![Small area fixed](https://user-images.githubusercontent.com/67757218/170010692-49aa4cdb-2fa6-49cd-8073-2595a3620da1.PNG)

**Comment by ThomasRahm** [comment]
Are there any updates regarding this bug/corresponding pull request?

**Comment by rburema** [comment]
@ThomasRahm Hi, sorry for the extreme delays on our side. Fortunately, we've restarted our efforts to get more of a handle on these recently.
