### ISSUE TITLE
Fix either time travel or negative printing time

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/CuraEngine#17]
It would be awesome if the print time could be negative (it already made a while ago what you're going to want to print?).
```Print time: -2147483648```

For example for the hat (found here):
https://www.youmagine.com/designs/wedding-cake-topper

This negative number could be fixed, or is this bug is an awesome 'foresight' feature? :)

Full output:
```
Loading groom_hat.stl from disk...
Loaded from disk in 0.023s
Analyzing and optimizing model...
  Face counts: 1596 -> 1596 100.0%
  Vertex counts: 4788 -> 800 16.7%
Optimize model 0.004s
Slicing model...
Layer count: 100
Processed all layers in   0.0s
Sliced model in 0.022s
Generating layer parts...
Generated layer parts in 0.005s
Generated inset in 0.051s
Generated up/down skin in 0.079s
Wrote layers in  0.09s.
Wrote 502.3 kilobytes.
Total time elapsed  0.27s.
Print time: -2147483648
Filament: 88
```

**Comment by BagelOrb** [comment]
Does the problem still occur?
