### ISSUE TITLE
Unable to reset/move printer head when print is cancelled.

### ISSUE THREAD

**Issue by tebruno99** [Ultimaker/CuraEngine#171]
Without manual control I'm unable to move the printer head so I can get the failed object off the bed.  I have to keep starting up RepeaterHost to move the head out of the way.

**Comment by BagelOrb** [comment]
You can just move the print head by hand. Sometimes the motors block you from moving the head and platform. In such a case you can just turn the machine off and move all parts where you like.

You talk about manual control, which is an issue with the firmware, not with CuraEngine.

**Comment by tebruno99** [comment]
How can no gui for sending commands to the printer be a firmware problem?

**Comment by BagelOrb** [comment]
Aha. It wasn't clear to me you were talking about GUI controls.
This is not a problem with Ultimaker/CuraEngine, but with daid/Cura.

Perhaps direct control of the printer from the GUI will be worked on in the future; let's hope so.

**Comment by cscott** [comment]
Those buttons are in the Pronterface UI, there's an option to select it.

Still: this is the wrong repository for this bug.

**Comment by tebruno99** [comment]
My apologies, I thought CuraEngine/Cura was the same thing. I will look for the correct repository.
