### ISSUE TITLE
No support under pointy objects.

### ISSUE THREAD

**Issue by cscott** [Ultimaker/CuraEngine#172]
The CuraEngine "Overhang angle for support" neglects to consider that the geometry in question might not be a continuation of a structure underneath it, but rather a pointy bottom.

For example, in http://www.thingiverse.com/thing:351620 there are several "pointy bottomed" areas, which don't get any support at all with Cura's default settings (overhang angle ~60 degrees).  If you reduce the overhang angle to 35 degrees you can get support generated, but then it also generates unnecessary support for several other areas.
![screenshot from 2015-03-16 12 49 12](https://cloud.githubusercontent.com/assets/156080/6671319/ddd79d48-cbda-11e4-8348-7319db9d44a9.png)

CuraEngine should look not only at the inclination of the triangle, but also whether there is any fill in the layer underneath.

A related issue is that the generated fill often doesn't actually have any plastic underneath the pointy-bottomed area (see attached image).  In-filling the "top" area of the support would help a lot here (as was mentioned in issue #61 where unifying rafts and supports was proposed).
![screenshot from 2015-03-16 12 45 58](https://cloud.githubusercontent.com/assets/156080/6671254/7c298246-cbda-11e4-8d5a-631cfd66ab14.png)

**Comment by daid** [comment]
We're working on a new algorithm that fixes these issues.

**Comment by cscott** [comment]
Cool, thanks!

It might be worth leaving this issue open until the new algorithm lands in order to reduce duplicate bug reports.  I searched through the first two pages of open bugs without finding anything similar before I took the time to file this one.
