### ISSUE TITLE
F0 speed in generated GCode

### ISSUE THREAD

**Issue by Fgodi-coriolis** [Ultimaker/CuraEngine#1735]
**Application Version**
I am using the CuraEngine.exe embeded with Cura 5.1.1

**Steps to Reproduce**
I am using the following command line :
`"Ultimaker Cura 5.1.1\CuraEngine.exe" slice -v -p -j "fdmprinter.def.json" -o output.gcode -s infill_line_width=0.8 -s layer_height=0.8 -s infill_pattern=lines -s infill_line_distance=4 -s speed_infill=60 -s speed_travel=0 -s adhesion_type=none -s support_enable=False -s machine_width=100000 -s machine_depth=100000 -s machine_height=100000 -s machine_center_is_zero=true -s center_object=true -l input.stl `

Input file and def.json files are attached below.

**Actual Results**
There are move in GCode with speed = 0
For example line 3 (actually line 9523, just after the start of layer) :
```
G1 X68.447 Y15.025 E157.50111
G1 X68.186 Y14.046 E157.55193
G0 F0 X67.889 Y14.085
G0 X68.226 Y15.126
G0 X68.673 Y16.087
```
The full result is also in the zip below.

**Expected results**
A GCode with appropriate speeds. What would it mean to do a move with speed  = 0 ? It would take an infinite time.

**Comment by Fgodi-coriolis** [comment]
[input output.zip](https://github.com/Ultimaker/CuraEngine/files/9681947/input.output.zip)

**Comment by Fgodi-coriolis** [comment]
[input output.zip](https://github.com/Ultimaker/CuraEngine/files/9681960/input.output.zip)

**Comment by rburema** [comment]
Sorry it took so long to get back.

I see that you have `-s speed_travel=0` in your command-line to call the engine. While an `G0 F0` is wrong, what would you expect to happen in such a case?

**Comment by Fgodi-coriolis** [comment]
Thanks a lot!
I close the ticket.
