### ISSUE TITLE
No support material generated

### ISSUE THREAD

**Issue by sselkirk** [Ultimaker/CuraEngine#175]
When I run my slice CuraEngine isn't generating support material, can you tell me how i fix this? thanks
![curaengine - nosupport1](https://cloud.githubusercontent.com/assets/11322514/6794190/c0e2facc-d222-11e4-9ff3-2e0d1dfd561d.jpg)
![curaengine - nosupport2](https://cloud.githubusercontent.com/assets/11322514/6794189/c0e274da-d222-11e4-8b33-efafa3c12b69.jpg)
![curaengine - nosupport3](https://cloud.githubusercontent.com/assets/11322514/6794191/c0e4e364-d222-11e4-9b5b-d4b5870b7506.jpg)

**Comment by daid** [comment]
First off, due to the closed nature, I'm not giving support for the Repetier version of CuraEngine.

Second, we're well aware of problems with the current support code, and we're working on a huge fix for it.
