### ISSUE TITLE
Retractions between support lines

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/CuraEngine#179]
Retractions between support lines cause the filament to grind to a halt, according to Bas.

**Comment by Bas-van-Deursen** [comment]
I also get retractions in the infill pattern. This, together with the issue described above, causes flattening of the filament.

**Comment by Bas-van-Deursen** [comment]
print was sliced with cura 15.02.1

**Comment by BagelOrb** [comment]
You probably just had combing turned off.
