### ISSUE TITLE
Typo in LayerPlan.cpp

### ISSUE THREAD

**Issue by ckvsoft** [Ultimaker/CuraEngine#1844]
**Application Version**
Main and Branch 5.3

**Platform**
All

**Additional Information**

There seems to be a typo in LayerPlan.cpp
Up to version 5.2 it was

NONMESH

However, 

NOMESH

was written in the current main and branch 5.3. Since then, an exclude_object no longer works

**Comment by jellespijker** [comment]
Fixed, closing this issues
