### ISSUE TITLE
Wanted future, "Save & upload" button

### ISSUE THREAD

**Issue by DragonFlyer007** [Ultimaker/CuraEngine#1845]
Would be nice if in you could upload directly thru Moonraker, but also have it save the file in parent a the stl file folder or similar.

Like a "Save & Upload" button. 

Think it's good to keep the Gcode saved for future use, but the possibility to upload fast and directly thru Cura is also nice, and i think many do it like save, and upload, so why not have the possibility to do both at once.

**Comment by fieldOfView** [comment]
This would be a feature request for Cura, not for CuraEngine. For Cura, there is already a plugin to send the file to Moonraker:
https://marketplace.ultimaker.com/app/cura/plugins/emtrax/MoonrakerConnection
