### ISSUE TITLE
Unable to build CuraEngine.

### ISSUE THREAD

**Issue by kelvin6k** [Ultimaker/CuraEngine#1887]
What is the correct procedure to Build CuraEngine I have been trying to build curaEngine past two week but didn't able to build I'm following curaEngine documentation only but it didn't work.

It showing this error.

cmake --build --preset release
[1/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/FffProcessor.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/FffProcessor.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/FffProcessor.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\FffProcessor.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/FffProcessor.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/FffProcessor.cpp
c++.exe: error: /permissive-: No such file or directory
[2/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/ExtruderTrain.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/ExtruderTrain.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/ExtruderTrain.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\ExtruderTrain.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/ExtruderTrain.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/ExtruderTrain.cpp
c++.exe: error: /permissive-: No such file or directory
[3/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/FffPolygonGenerator.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/FffPolygonGenerator.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/FffPolygonGenerator.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\FffPolygonGenerator.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/FffPolygonGenerator.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/FffPolygonGenerator.cpp
c++.exe: error: /permissive-: No such file or directory
[4/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/gcodeExport.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/gcodeExport.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/gcodeExport.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\gcodeExport.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/gcodeExport.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/gcodeExport.cpp
c++.exe: error: /permissive-: No such file or directory
[5/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/FffGcodeWriter.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/FffGcodeWriter.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/FffGcodeWriter.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\FffGcodeWriter.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/FffGcodeWriter.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/FffGcodeWriter.cpp
c++.exe: error: /permissive-: No such file or directory
[6/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/ConicalOverhang.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/ConicalOverhang.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/ConicalOverhang.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\ConicalOverhang.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/ConicalOverhang.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/ConicalOverhang.cpp
c++.exe: error: /permissive-: No such file or directory
[7/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/layerPart.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/layerPart.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/layerPart.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\layerPart.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/layerPart.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/layerPart.cpp
c++.exe: error: /permissive-: No such file or directory
[8/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/InsetOrderOptimizer.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/InsetOrderOptimizer.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/InsetOrderOptimizer.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\InsetOrderOptimizer.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/InsetOrderOptimizer.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/InsetOrderOptimizer.cpp
c++.exe: error: /permissive-: No such file or directory
[9/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/InterlockingGenerator.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/InterlockingGenerator.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/InterlockingGenerator.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\InterlockingGenerator.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/InterlockingGenerator.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/InterlockingGenerator.cpp
c++.exe: error: /permissive-: No such file or directory
[10/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/infill.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/infill.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/infill.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\infill.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/infill.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/infill.cpp
c++.exe: error: /permissive-: No such file or directory
[11/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/LayerPlan.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/LayerPlan.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/LayerPlan.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\LayerPlan.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/LayerPlan.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/LayerPlan.cpp
c++.exe: error: /permissive-: No such file or directory
[12/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/GCodePathConfig.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/GCodePathConfig.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/GCodePathConfig.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\GCodePathConfig.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/GCodePathConfig.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/GCodePathConfig.cpp
c++.exe: error: /permissive-: No such file or directory
[13/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/bridge.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/bridge.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/bridge.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\bridge.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/bridge.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/bridge.cpp
c++.exe: error: /permissive-: No such file or directory
[14/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/Application.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/Application.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/Application.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\Application.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/Application.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/Application.cpp
c++.exe: error: /permissive-: No such file or directory
[15/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/LayerPlanBuffer.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/LayerPlanBuffer.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/LayerPlanBuffer.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\LayerPlanBuffer.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/LayerPlanBuffer.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/LayerPlanBuffer.cpp
c++.exe: error: /permissive-: No such file or directory
[16/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/mesh.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/mesh.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/mesh.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\mesh.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/mesh.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/mesh.cpp
c++.exe: error: /permissive-: No such file or directory
[17/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/MeshGroup.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/MeshGroup.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/MeshGroup.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\MeshGroup.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/MeshGroup.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/MeshGroup.cpp
c++.exe: error: /permissive-: No such file or directory
[18/184] Building CXX object CMakeFiles/_CuraEngine.dir/src/Mold.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/Mold.cpp.obj
C:\MinGW\bin\c++.exe -DARCUS -DBUILD_TESTS -DCURA_ENGINE_VERSION=\"None\" -DNOMINMAX -DPROTOBUF_USE_DLLS -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -ID:/Ajay/curabuild/CuraEngine/include -ID:/Ajay/curabuild/CuraEngine/build/Release -isystem C:/.conan/adf877/1/include -isystem C:/.conan/a10a5f/1/include -isystem C:/.conan/424683/1/include -isystem C:/.conan/d2ed88/1/include -isystem C:/.conan/913ee1/1/include -isystem C:/.conan/c45e73/1/include -isystem C:/.conan/e2662b/1/include -isystem C:/.conan/c10bfc/1/include -isystem C:/.conan/aabc79/1/include -isystem C:/.conan/412a7a/1/include -isystem C:/.conan/30d72a/1/include -O3 -DNDEBUG -std=c++2a /permissive- -MD -MT CMakeFiles/_CuraEngine.dir/src/Mold.cpp.obj -MF CMakeFiles\_CuraEngine.dir\src\Mold.cpp.obj.d -o CMakeFiles/_CuraEngine.dir/src/Mold.cpp.obj -c D:/Ajay/curabuild/CuraEngine/src/Mold.cpp
c++.exe: error: /permissive-: No such file or directory
ninja: build stopped: subcommand failed.

**Comment by jellespijker** [comment]
it looks like your a building eith mingw, please use MSVC on Windows.  see the build instructions https://github.com/Ultimaker/CuraEngine/wiki/Building-CuraEngine-From-Source

take note of the requirement section.

I will close this issue since I believe this should resolve your problem, feel free to comment or reopen if that didn't resolve it
