### ISSUE TITLE
This design doesn't seem to produce valid GCODE

### ISSUE THREAD

**Issue by CoDanny** [Ultimaker/CuraEngine#191]
This design produces bad GCODE. It works fine when using slic3r:

http://www.thingiverse.com/thing:13505

I tried using version 15.04 of the engine as well as 15.02.1 of the Cura full App

**Comment by daid** [comment]
Reported a few times before, Cura has troubles with the very thin sections, due to the algorithms used.

**Comment by BagelOrb** [comment]
In the new Cura, the gcode is empty...
