### ISSUE TITLE
poligon.cpp is not found.

### ISSUE THREAD

**Issue by jisujisu** [Ultimaker/CuraEngine#194]
poligon.cpp is not found.

**Comment by daid** [comment]
Indeed.

**Comment by raceyi** [comment]
Hello Daid,

polygon.cpp is required as CMakeList.txt has it, right? 

Would you please check CuraEngine repository?

I cloned it as below.
git clone https://github.com/Ultimaker/CuraEngine.git

and looked for polygon.cpp but it doesn’t exist.
find . -name polygon.cpp

How can I get polygon.cpp? or is it unnecessary to build CuraEngine?

Thanks in advance.

**Comment by BagelOrb** [comment]
Note that it's spelled polygon.cpp with a Y instead of an I.
Fixed now.
