### ISSUE TITLE
.skp (skechtup file) support for importing file

### ISSUE THREAD

**Issue by LightBridge16** [Ultimaker/CuraEngine#1970]
hello,

I'm new toot the 3D printing hobby and drawing, but I have a Request for supporting skechtup file importing because I have a .skp file and I have no option too convert it for free.

would it be possible?

thanks for the latest beta version I love it!

**Comment by fieldOfView** [comment]
This should probably be a request for Cura, not CuraEngine.
See https://github.com/ultimaker/cura/issues

Having said that, .skp is a proprietary, undocumented file format, from an application that is known to make models that are horrible for 3d printing, so I would not get my hopes up.
