### ISSUE TITLE
Potentially incorrect function `ceil_divide_signed`

### ISSUE THREAD

**Issue by chungwong** [Ultimaker/CuraEngine#2005]
**Application Version**
Versions including this commit https://github.com/Ultimaker/CuraEngine/commit/3b34b69277

It looks like [this function](https://github.com/Ultimaker/CuraEngine/commit/3b34b69277) is logically incorrect?

```c++
inline unsigned int ceil_divide_signed(int dividend, int divisor) //!< Return dividend divided by divisor rounded up towards positive infinity.
{
    return (dividend / divisor) + (dividend * divisor > 0 ? 1 : 0);
}

// it returns 31 instead of 30
ceil_divide_signed(90, 3);
```
Is this beahviour expected?

**Comment by 0x5844** [comment]
The pr that addresses this issue is now merged!
