### ISSUE TITLE
Material Length not reset between slices

### ISSUE THREAD

**Issue by awhiemstra** [Ultimaker/CuraEngine#201]
Platform: Arch Linux 64-bit

Steps to Reproduce:
* Load a model into the new Cura
* Wait for it to finish slicing, then move it and wait for it to finish slicing again.

Actual Results:
* Reported Material Length is equal to 2x the actual length.

Expected results:
* Reported Material Length provides a reasonably accurate estimation.

Additional Information:
* Verified to be an engine issue, the UI code handling this does barely more than pass it the value from the engine to the UI to display.

**Comment by BagelOrb** [comment]
Did my fix work?

**Comment by awhiemstra** [comment]
Fixed by 01f1568ddacba5eafc3c880456262cd7952d61bb
