### ISSUE TITLE
Can't get this program to work. Neither with apt or building from source. 

### ISSUE THREAD

**Issue by GAMPR** [Ultimaker/CuraEngine#2017]
I am writing a multi pronged issue report for this program on my debian system, as I can't get it to work properly at all. I installed this program from apt cura-engine first, it does not even work with the CuraEngine command. I have to use /usr/bin/CuraEngine calling it directly. I got the jsons for my ender3 printer, from the Cura git itself. Now I get a heavy error: /usr/bin/CuraEngine slice -j /home/trdat/Reese/CuraRedo/Cura/resources/definitions/fdmprinter.def.json -s wireframe_enabled='False' -l /home/trdat/Downloads/20mm_cube.stl -o /home/trdat/Downloads/totem.gcode     
Cura_SteamEngine version 5.0.0
Copyright (C) 2022 Ultimaker

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
[WARNING] Unrecognized data type in JSON setting machine_disallowed_areas
[WARNING] Unrecognized data type in JSON setting nozzle_disallowed_areas
[WARNING] Unrecognized data type in JSON setting machine_head_with_fans_polygon
[WARNING]  -s wireframe_enabled="False" -s mesh_rotation_matrix="[[1,0,0], [0,1,0], [0,0,1]]" -s mesh_position_z="0" -s mesh_position_x="0" -s center_object="false" -s bv_temp_anomaly_limit="10" -s print_temp_warn_limit="3" -s flow_anomaly_limit="25" -s ppr_enable="false" -s material_alternate_walls="false" -s jerk_prime_tower="20" -s retraction_hop="1" -s coasting_enable="false" -s connect_infill_polygons="true" -s acceleration_print_layer_0="3000" -s support_bottom_angles="[ ]" -s jerk_support_roof="20" -s gradual_infill_steps="0" -s speed_wall_0_roofing="30" -s acceleration_support_infill="3000" -s acceleration_travel_layer_0="3000" -s acceleration_travel_enabled="true" -s retraction_prime_speed="25" -s brim_outside_only="true" -s acceleration_enabled="false" -s jerk_topbottom="20" -s brim_gap="0" -s smooth_spiralized_contours="true" -s print_temp_anomaly_limit="7" -s speed_slowdown_layers="2" -s bridge_wall_min_length="5" -s skirt_brim_speed="30" -s speed_topbottom="30" -s support_line_distance="2.66" -s ooze_shield_dist="2" -s switch_extruder_extra_prime_amount="0" -s skin_material_flow_layer_0="100" -s jerk_travel_enabled="true" -s material_flow_layer_0="100" -s speed_wall_x_roofing="60" -s roofing_line_width="0.4" -s top_bottom_pattern_0="lines" -s support_supported_skin_fan_speed="100" -s support_roof_material_flow="100" -s prime_tower_base_curve_magnitude="4" -s infill_mesh_order="0" -s support_material_flow="100" -s bridge_skin_support_threshold="50" -s wall_0_material_flow_roofing="100" -s wall_x_material_flow="100" -s raft_interface_jerk="20" -s acceleration_roofing="3000" -s prime_tower_position_x="200" -s wall_0_material_flow="100" -s extruder_prime_pos_y="0" -s speed_travel_layer_0="60" -s material_end_of_filament_purge_length="20" -s raft_interface_acceleration="3000" -s speed_support_bottom="40" -s raft_surface_layers="2" -s material_break_retracted_position="-50" -s small_feature_max_length="0" -s material_break_preparation_retracted_position="-16" -s material_crystallinity="false" -s material_shrinkage_percentage_z="100" -s speed_prime_tower="60" -s speed_roofing="25" -s material_shrinkage_percentage_xy="100" -s jerk_support_bottom="20" -s retraction_enable="true" -s material_surface_energy="100" -s support_interface_priority="interface_area_overwrite_support_area" -s material_extrusion_cool_down_speed="0.7" -s material_standby_temperature="150" -s machine_nozzle_cool_down_speed="2" -s layer_0_z_overlap="0.22" -s material_adhesion_tendency="10" -s material_initial_print_temperature="200" -s bottom_layers="6" -s anti_overhang_mesh="false" -s infill_material_flow="100" -s jerk_print_layer_0="20" -s lightning_infill_prune_angle="40" -s material_print_temperature="210" -s acceleration_prime_tower="3000" -s skin_edge_support_layers="4" -s ironing_line_spacing="0.1" -s speed_equalize_flow_width_factor="100" -s material_flush_purge_length="60" -s support_conical_angle="30" -s infill_before_walls="true" -s infill_wipe_dist="0.04" -s support_bottom_height="1" -s support_bottom_material_flow="100" -s acceleration_wall_x="3000" -s prime_tower_flow="100" -s infill_overlap_mm="0.04" -s sub_div_rad_add="0.4" -s skin_overlap_mm="0.02" -s small_feature_speed_factor="50" -s infill_multiplier="1" -s infill_randomize_start_location="false" -s acceleration_skirt_brim="3000" -s machine_depth="100" -s material_anti_ooze_retraction_speed="5" -s raft_surface_fan_speed="0" -s extruder_prime_pos_z="0" -s machine_heated_build_volume="false" -s support_enable="false" -s support_bottom_line_distance="0.4" -s zig_zaggify_infill="false" -s initial_layer_line_width_factor="100" -s material_bed_temperature="60" -s infill_pattern="grid" -s min_skin_width_for_expansion="0" -s machine_gcode_flavor="RepRap (Marlin/Sprinter)" -s wall_0_wipe_dist="0.2" -s switch_extruder_prime_speed="20" -s jerk_wall_x_roofing="20" -s top_skin_preshrink="1" -s roofing_pattern="lines" -s machine_max_feedrate_e="2.99792e+11" -s wipe_retraction_amount="1" -s machine_endstop_positive_direction_x="false" -s machine_steps_per_mm_y="50" -s min_infill_area="0" -s bridge_skin_material_flow="60" -s min_even_wall_line_width="0.3" -s material_flush_purge_speed="0.5" -s acceleration_travel="5000" -s support_roof_height="1" -s raft_surface_smoothing="5" -s wall_overhang_speed_factor="100" -s material_break_preparation_temperature="50" -s ironing_enabled="false" -s infill_wall_line_count="0" -s wipe_move_distance="20" -s machine_max_jerk_xy="20" -s support_bottom_extruder_nr="0" -s wall_0_inset="0" -s machine_max_acceleration_y="9000" -s optimize_wall_printing_order="true" -s flow_warn_limit="15" -s machine_max_acceleration_z="100" -s acceleration_topbottom="3000" -s extruder_prime_pos_x="0" -s lightning_infill_overhang_angle="40" -s support_infill_sparse_thickness="0.1" -s material_break_temperature="50" -s machine_max_feedrate_z="2.99792e+11" -s gradual_infill_step_height="1.5" -s infill_support_enabled="false" -s machine_use_extruder_offset_to_offset_coords="true" -s roofing_material_flow="100" -s machine_nozzle_size="0.4" -s material_break_preparation_speed="2" -s skin_line_width="0.4" -s machine_endstop_positive_direction_z="true" -s speed_travel="120" -s machine_shape="rectangular" -s machine_extruders_share_nozzle="false" -s draft_shield_dist="10" -s machine_steps_per_mm_z="50" -s infill_sparse_thickness="0.1" -s machine_max_feedrate_y="2.99792e+11" -s machine_firmware_retract="false" -s support_mesh="false" -s cross_support_density_image="" -s machine_width="100" -s jerk_infill="20" -s retraction_count_max="90" -s interlocking_orientation="22.5" -s machine_name="Unknown" -s layer_height_0="0.3" -s support_join_distance="2" -s machine_height="100" -s extruders_enabled_count="1" -s raft_interface_speed="15" -s infill_support_angle="40" -s bridge_fan_speed_3="0" -s support_tree_angle_slow="50" -s ironing_inset="0.35" -s jerk_wall_x="20" -s machine_always_write_active_tool="false" -s minimum_bottom_area="1" -s bridge_enable_more_layers="true" -s material_diameter="2.85" -s machine_center_is_zero="false" -s roofing_monotonic="true" -s default_material_bed_temperature="60" -s support_xy_distance_overhang="0.2" -s material_no_load_move_factor="0.94086" -s raft_airgap="0.3" -s mold_angle="40" -s machine_steps_per_mm_x="50" -s bridge_skin_speed_3="15" -s z_seam_type="sharpest_corner" -s support_bottom_line_width="0.4" -s machine_end_gcode="M104 S0
M140 S0
;Retract the filament
G92 E1
G1 E-1 F300
G28 X0 Y0
M84" -s machine_max_jerk_z="0.4" -s switch_extruder_retraction_speed="20" -s machine_heat_zone_length="16" -s material_maximum_park_duration="300" -s skin_no_small_gaps_heuristic="false" -s machine_minimum_feedrate="0" -s remove_empty_first_layers="true" -s material_guid="" -s machine_endstop_positive_direction_y="false" -s machine_nozzle_heat_up_speed="2" -s jerk_wall_0="20" -s infill_offset_y="0" -s cool_fan_speed_max="100" -s material_print_temp_prepend="true" -s acceleration_infill="3000" -s machine_extruder_count="1" -s zig_zaggify_support="false" -s support_roof_line_distance="0.4" -s skin_outline_count="1" -s bridge_skin_density="100" -s material_bed_temperature_layer_0="60" -s machine_acceleration="4000" -s initial_bottom_layers="6" -s wipe_retraction_prime_speed="2" -s acceleration_support_roof="3000" -s min_odd_wall_line_width="0.3" -s adhesion_type="brim" -s machine_nozzle_expansion_angle="45" -s multiple_mesh_overlap="0.15" -s skin_material_flow="100" -s wall_x_extruder_nr="-1" -s raft_surface_jerk="20" -s infill_enable_travel_optimization="false" -s machine_nozzle_temp_enabled="true" -s material_flow_temp_graph="[[3.5, 200],[7.0, 240]]" -s machine_min_cool_heat_time_window="50" -s material_end_of_filament_purge_speed="0.5" -s prime_tower_min_volume="6" -s acceleration_ironing="3000" -s machine_max_jerk_e="5" -s meshfix_fluid_motion_shift_distance="0.1" -s top_layers="8" -s material_bed_temp_prepend="true" -s prime_tower_raft_base_line_spacing="1.6" -s wall_line_width_0="0.4" -s speed_ironing="20" -s gantry_height="1e+11" -s bottom_skin_expand_distance="1" -s min_feature_size="0.1" -s machine_extruders_share_heater="false" -s conical_overhang_hole_size="0" -s roofing_extruder_nr="-1" -s minimum_polygon_circumference="1" -s bottom_skin_preshrink="1" -s small_skin_on_surface="false" -s skirt_brim_material_flow="100" -s skirt_brim_line_width="0.4" -s speed_print_layer_0="30" -s speed_support_roof="40" -s support_bottom_wall_count="0" -s roofing_angles="[ ]" -s hole_xy_offset_max_diameter="0" -s cool_fan_full_layer="2" -s infill_line_distance="2" -s jerk_ironing="20" -s support_tree_tip_diameter="0.4" -s bridge_skin_speed="15" -s bridge_fan_speed="100" -s material_anti_ooze_retracted_position="-4" -s raft_base_margin="15" -s layer_height="0.1" -s wipe_retraction_retract_speed="3" -s wall_x_material_flow_roofing="100" -s inset_direction="inside_out" -s z_seam_y="100" -s wall_overhang_angle="90" -s support_tree_angle="60" -s z_seam_corner="z_seam_corner_inner" -s machine_max_acceleration_x="9000" -s support_connect_zigzags="true" -s bridge_skin_density_3="80" -s wall_transition_filter_deviation="0.1" -s meshfix_keep_open_polygons="false" -s machine_steps_per_mm_e="1600" -s gradual_support_infill_step_height="1" -s machine_feeder_wheel_diameter="10" -s alternate_extra_perimeter="false" -s build_volume_temperature="0" -s support_brim_line_count="3" -s jerk_support_infill="20" -s infill_offset_x="0" -s machine_max_feedrate_x="2.99792e+11" -s material_final_print_temperature="195" -s acceleration_wall_0="3000" -s fill_outline_gaps="true" -s acceleration_wall_0_roofing="3000" -s machine_buildplate_type="glass" -s ironing_pattern="zigzag" -s meshfix_extensive_stitching="false" -s min_bead_width="0.2" -s support_tree_limit_branch_reach="true" -s xy_offset_layer_0="0" -s meshfix_maximum_travel_resolution="1" -s support_tower_roof_angle="65" -s raft_interface_fan_speed="0" -s z_seam_x="100" -s hole_xy_offset="0" -s top_skin_expand_distance="1" -s z_seam_relative="false" -s wall_distribution_count="1" -s speed_wall_x="60" -s infill_line_width="0.4" -s support_bottom_offset="0" -s xy_offset="0" -s wall_0_material_flow_layer_0="100" -s material_bed_temp_wait="true" -s raft_surface_remove_inside_corners="false" -s material_break_speed="25" -s top_bottom_extruder_nr="-1" -s material_is_support_material="false" -s jerk_roofing="20" -s jerk_wall_0_roofing="20" -s top_bottom_pattern="lines" -s skin_monotonic="false" -s jerk_travel="30" -s support_tree_top_rate="15" -s ironing_monotonic="false" -s small_skin_width="1" -s speed_support_infill="60" -s retraction_hop_enabled="false" -s wall_0_extruder_nr="-1" -s prime_tower_wipe_enabled="true" -s jerk_travel_layer_0="20" -s raft_base_speed="15" -s jerk_skirt_brim="20" -s support_roof_line_width="0.4" -s retract_at_layer_change="false" -s retraction_amount="6.5" -s bv_temp_warn_limit="7.5" -s retraction_retract_speed="25" -s brim_line_count="20" -s raft_surface_line_spacing="0.4" -s retraction_extra_prime_amount="0" -s retraction_min_travel="1.5" -s machine_extruders_shared_nozzle_initial_retraction="0" -s interlocking_beam_width="0.8" -s support_conical_min_width="5" -s conical_overhang_enabled="false" -s retraction_combing_max_distance="0" -s support_roof_pattern="concentric" -s support_roof_angles="[ ]" -s travel_retract_before_outer_wall="false" -s support_brim_enable="true" -s layer_start_y="0" -s mesh_position_y="0" -s retraction_hop_after_extruder_switch="true" -s retraction_hop_after_extruder_switch_height="1" -s ironing_flow="10" -s cool_fan_enabled="true" -s cool_fan_speed_min="100" -s machine_max_acceleration_e="10000" -s cool_min_layer_time_fan_speed_max="10" -s wall_line_count="2" -s cool_fan_speed_0="0" -s support_wall_count="1" -s raft_base_line_spacing="1.6" -s cool_min_layer_time="5" -s travel_avoid_distance="0.625" -s cool_min_speed="10" -s cool_lift_head="false" -s support_tree_rest_preference="buildplate" -s cool_min_temperature="0" -s travel_avoid_supports="false" -s interlocking_beam_layer_count="2" -s support_infill_extruder_nr="0" -s support_extruder_nr_layer_0="0" -s support_roof_extruder_nr="0" -s interlocking_enable="false" -s support_structure="normal" -s support_tree_branch_reach_limit="30" -s support_tree_branch_diameter="5" -s support_initial_layer_line_distance="2.66" -s retraction_extrusion_window="4.5" -s bridge_fan_speed_2="0" -s support_tree_min_height_to_model="3" -s skin_angles="[ ]" -s support_tree_bp_diameter="7.5" -s support_angle="50" -s support_pattern="zigzag" -s wall_line_width_x="0.4" -s raft_base_acceleration="3000" -s support_roof_wall_count="0" -s support_zag_skip_count="5" -s retraction_combing="all" -s support_infill_angles="[ ]" -s support_top_distance="0.1" -s support_bottom_distance="0.1" -s support_xy_distance="0.7" -s prime_tower_brim_enable="false" -s support_xy_overrides_z="z_overrides_xy" -s support_bottom_stair_step_height="0.3" -s machine_nozzle_id="unknown" -s prime_tower_size="20" -s travel_avoid_other_parts="true" -s small_feature_speed_factor_0="50" -s support_bottom_stair_step_width="5" -s support_offset="0.8" -s machine_heated_bed="false" -s gradual_support_infill_steps="0" -s wall_x_material_flow_layer_0="100" -s minimum_support_area="0" -s acceleration_wall_x_roofing="3000" -s support_roof_enable="false" -s support_bottom_enable="false" -s lightning_infill_straightening_angle="40" -s bridge_wall_material_flow="50" -s machine_nozzle_head_distance="3" -s support_bottom_pattern="concentric" -s raft_base_wall_count="1" -s minimum_roof_area="1" -s bridge_wall_speed="15" -s support_roof_offset="0" -s support_fan_enable="false" -s support_use_towers="true" -s layer_start_x="0" -s support_tower_maximum_supported_diameter="3" -s acceleration_support_bottom="3000" -s bridge_skin_density_2="75" -s support_mesh_drop_down="true" -s prime_tower_position_y="200" -s support_meshes_present="false" -s prime_blob_enable="false" -s skirt_brim_extruder_nr="-1" -s raft_base_extruder_nr="0" -s raft_base_smoothing="5" -s raft_interface_extruder_nr="0" -s material_print_temperature_layer_0="215" -s raft_surface_extruder_nr="0" -s skirt_line_count="1" -s skirt_height="3" -s skirt_gap="3" -s brim_replaces_support="true" -s skirt_brim_minimal_length="250" -s speed_z_hop="10" -s brim_inside_margin="2.5" -s brim_smart_ordering="true" -s raft_interface_margin="15" -s adaptive_layer_height_variation="0.1" -s group_outer_walls="true" -s raft_surface_margin="15" -s support_tree_max_diameter="25" -s raft_base_remove_inside_corners="false" -s raft_interface_remove_inside_corners="false" -s retraction_hop_only_when_collides="false" -s raft_base_thickness="0.3" -s mold_width="5" -s raft_base_line_width="0.8" -s raft_interface_layers="1" -s raft_interface_thickness="0.15" -s support_type="everywhere" -s raft_interface_line_width="0.7" -s draft_shield_enabled="false" -s raft_interface_line_spacing="0.9" -s speed_infill="60" -s raft_surface_thickness="0.1" -s raft_surface_line_width="0.4" -s raft_interface_wall_count="0" -s raft_surface_wall_count="0" -s raft_surface_speed="20" -s raft_surface_acceleration="3000" -s raft_base_jerk="20" -s raft_base_fan_speed="0" -s wipe_hop_speed="10" -s prime_tower_enable="false" -s material_print_temp_wait="true" -s prime_tower_base_size="1.2" -s support_tree_branch_diameter_angle="7" -s prime_tower_base_height="0" -s ooze_shield_enabled="false" -s wipe_retraction_enable="true" -s switch_extruder_retraction_amount="20" -s meshfix_union_all="true" -s meshfix_union_all_remove_holes="false" -s support_tower_diameter="3" -s carve_multiple_volumes="true" -s alternate_carve_order="true" -s meshfix_maximum_resolution="0.5" -s default_material_print_temperature="210" -s meshfix_maximum_extrusion_area_deviation="50000" -s machine_show_variants="false" -s meshfix_fluid_motion_enabled="true" -s prime_tower_line_width="0.4" -s meshfix_fluid_motion_small_distance="0.01" -s speed_wall_0="30" -s meshfix_fluid_motion_angle="15" -s print_sequence="all_at_once" -s infill_mesh="false" -s cutting_mesh="false" -s wall_transition_filter_distance="100" -s magic_spiralize="false" -s raft_interface_smoothing="5" -s machine_nozzle_tip_outer_diameter="1" -s mold_roof_height="0.5" -s magic_fuzzy_skin_point_dist="0.8" -s magic_mesh_surface_mode="normal" -s relative_extrusion="false" -s slicing_tolerance="middle" -s bridge_wall_coast="100" -s interlocking_depth="2" -s interlocking_boundary_avoidance="2" -s coasting_volume="0.064" -s meshfix_maximum_deviation="0.025" -s support_skip_some_zags="false" -s draft_shield_height_limitation="full" -s conical_overhang_angle="50" -s draft_shield_height="10" -s wall_transition_angle="10" -s coasting_min_volume="0.8" -s max_extrusion_before_wipe="10" -s coasting_speed="90" -s cross_infill_pocket_size="2" -s wall_transition_length="0.4" -s ironing_only_highest_layer="false" -s cross_infill_density_image="" -s magic_fuzzy_skin_thickness="0.3" -s support_conical_enabled="false" -s mold_enabled="false" -s magic_fuzzy_skin_enabled="false" -s magic_fuzzy_skin_outside_only="false" -s connect_skin_polygons="false" -s flow_rate_max_extrusion_offset="0" -s flow_rate_extrusion_offset_factor="100" -s adaptive_layer_height_enabled="false" -s adaptive_layer_height_variation_step="0.01" -s adaptive_layer_height_threshold="0.2" -s jerk_enabled="false" -s bridge_settings_enabled="false" -s support_line_width="0.4" -s bridge_sparse_infill_max_density="0" -s ooze_shield_angle="60" -s bridge_skin_speed_2="25" -s infill_angles="[ ]" -s bridge_skin_material_flow_2="100" -s bridge_skin_material_flow_3="110" -s support_tree_max_diameter_increase_by_merges_when_support_to_model="1" -s clean_between_layers="false" -s wipe_retraction_extra_prime_amount="0" -s wipe_pause="0" -s wipe_hop_enable="true" -s wipe_hop_amount="1" -s machine_scale_fan_speed_zero_to_one="false" -s extruder_prime_pos_abs="false" -s machine_start_gcode="G28 ;Home
G1 Z15.0 F6000 ;Move the platform down 15mm
;Prime the extruder
G92 E0
G1 F200 E3
G92 E0" -s support_bottom_stair_step_min_slope="10" -s wipe_brush_pos_x="100" -s infill_extruder_nr="-1" -s wipe_repeat_count="5" -e0 -s extruder_prime_pos_y="0" -s material_diameter="2.85" -s machine_nozzle_offset_x="0" -s machine_nozzle_id="unknown" -s extruder_nr="0" -s extruder_prime_pos_z="0" -s machine_extruder_cooling_fan_number="0" -s machine_extruder_end_code="" -s machine_extruder_end_code_duration="0" -s machine_extruder_start_pos_y="0" -s machine_extruder_start_code="" -s machine_extruder_end_pos_x="0" -s machine_nozzle_size="0.4" -s machine_extruder_end_pos_abs="false" -s machine_extruder_end_pos_y="0" -s machine_nozzle_offset_y="0" -s machine_extruder_start_code_duration="0" -s extruder_prime_pos_x="0" -s machine_extruder_start_pos_x="0" -s machine_extruder_start_pos_abs="false" -g -e0 -l "0" -s extruder_prime_pos_y="0" -s material_diameter="2.85" -s machine_nozzle_offset_x="0" -s machine_nozzle_id="unknown" -s extruder_nr="0" -s extruder_prime_pos_z="0" -s machine_extruder_cooling_fan_number="0" -s machine_extruder_end_code="" -s machine_extruder_end_code_duration="0" -s machine_extruder_start_pos_y="0" -s machine_extruder_start_code="" -s machine_extruder_end_pos_x="0" -s machine_nozzle_size="0.4" -s machine_extruder_end_pos_abs="false" -s machine_extruder_end_pos_y="0" -s machine_nozzle_offset_y="0" -s machine_extruder_start_code_duration="0" -s extruder_prime_pos_x="0" -s machine_extruder_start_pos_x="0" -s machine_extruder_start_pos_abs="false"
[ERROR] Trying to retrieve setting with no value given: 'wall_split_middle_threshold'
[ERROR] Trying to retrieve setting with no value given: 'wall_split_middle_threshold'

I must have tried maybe 20 different combinations and options to try to get it but no luck. I also tried to compile from source, but following the installation instruction it gets stuck at cmake --preset release with this:
CMake Error: Could not read presets from /home/trdat/Reese/CuraRedo/CuraEngine:
File not found: /home/trdat/Reese/CuraRedo/CuraEngine/CMakePresets.json

For source, Further the conan versions are absolutely incorrect, as it expects 1.58 but the install guide says to use 1.56, and another issue happened where it was not finding protobuf. Both things I had to debug to even get this far, with zero experience or knowledge of the program beyond the fact that I just want to make a stl or obj into a gcode to print en masse and without a gui. Using old install guides was a complete flop, as that produced even worse results and compatibility issues. I did not expect such a hard time getting this running, and wanted to use it for a hackathon. I still have tomorrow to make it work, and I will try to install it on a Windows system possibly or fix these issues somehow. If someone knows how to get this to work, please help me.

**Comment by jellespijker** [comment]
looking at this you're probably using newer printer definitions than the Cura engine version you are using

It complains about `wall_split_middle_threshold` trying to retrieve settings with no value given. Make sure that you use the definitions from Cura and CuraEngine from the same release.
