### ISSUE TITLE
use assimp to handle file format import/export.

### ISSUE THREAD

**Issue by thawkins** [Ultimaker/CuraEngine#206]
Assimp is a multiple format importer for mesh and material data, that it reads  a very wide number of file formats, and provides both import and output capability for most. It also provides a number of mesh quality and repair functions that can be used to normalise or fix up meshes. 

It would make a good replacement for the existimg input/output system on CuraEngine. 

http://assimp.sourceforge.net/index.html

.stl and .obj format is fully supported.

**Comment by BagelOrb** [comment]
Might be a good idea. We should take a look into this.

**Comment by Ghostkeeper** [comment]
This is an issue for the front-end, Cura, rather than CuraEngine.
That said, I'm not sure if depending on Boost is a good idea, but it might be a good idea to use this or something similar.

**Comment by nallath** [comment]
I agree with Ghostkeeper, depending on boost should be avoided if possible.

**Comment by daid** [comment]
Boost? That's really something we want to avoid.

Also see #208 for the reason why this does not belong at the engine.

**Comment by awhiemstra** [comment]
In addition, we have been considering implementing a file reader/writer plugin for Cura that uses AssImp since there are also Python bindings available.
