### ISSUE TITLE
[5.8.0] part of product missing using CuraEngine CLI

### ISSUE THREAD

**Issue by MrMonkeyManiac** [Ultimaker/CuraEngine#2066]
**Application Version**
Tested on CuraEngine version 5.7.0 and 5.8.0 with respective Cura versions

**Platform**
Ubuntu, within a docker container

**Qt**
n/a

**PyQt**
n/a

**Display Driver**
n/a

**Steps to Reproduce**
Using this Object; https://www.thingiverse.com/thing:6330588
- Start Cura from CLI with --external-backend and start the Slice process. 
- Connect unmodified version of CuraEngine for the process. 
- On CLI copy the "All settings:" log. 
- Do \<path>/CuraEngine Slice \<All settings> -o \<output path> and change the -l "0" to the same stl object used in the first step. 
- Slice the Object with the specified command

**Actual Results**
The sliced Object is missing most parts
![image](https://github.com/Ultimaker/CuraEngine/assets/166983511/889acf8e-3ed7-4cd9-9769-7ae1893adc70)

**Expected results**
The Object is whole
![image](https://github.com/Ultimaker/CuraEngine/assets/166983511/4aa6eeec-127f-4db4-a3a0-a560acca6845)

**Additional Information**
- I do NOT get this problem, when connecting the external backend to Cura, only when using CuraEngine just from the cli.
- I also used fdmprinter.def.json and fdmextruder.def.json, which gave me some errors, that some variable is not defined. When setting them manually i got the same result. 
- I did some testing and the problem seems to be occurring because of height information baked into stl files. Inside blender the specified file looks like this:
![image](https://github.com/Ultimaker/CuraEngine/assets/166983511/3a83fb70-6b3f-4aee-86cf-f842ae971eb1)
Moving the file inside blender and exporting as stl again, or increasing the height using a python script (numpy-stl) fixed the error for me

**Comment by fieldOfView** [comment]
CuraEngine does not change the origin of the model. Your model is partially placed "under the buildplate". CuraEngine only slices what is above the buildplate. Cura places the model in the center of the buildplate and makes sure the bottom of the model is on top of the buildplate. With CuraEngine, that task is up to you.
