### ISSUE TITLE
The documentation is wrong

### ISSUE THREAD

**Issue by grepwood** [Ultimaker/CuraEngine#2069]
It says on https://github.com/Ultimaker/CuraEngine/wiki/Building-CuraEngine-From-Source:

```
pip install conan==1.56
```

But in https://github.com/Ultimaker/CuraEngine/blob/fde7b79b61794124beb9570d1bd85129a7e4e721/conanfile.py#L15 it says:

```
required_conan_version = ">=1.58.0 <2.0.0"
```

Well then which one is it? As old saying goes,

> Comments can lie, but source code doesn't

**Comment by jellespijker** [comment]
Documentation can get out of sync with changes. I will see if I our one one of my colleagues have time to check all our repos for syncing this one of of these days. But it is a kow prio.

PR welcome.

And when in doubt follow the requirement as specified on Cura wiki
