### ISSUE TITLE
3MF Support

### ISSUE THREAD

**Issue by PatternSpacePrime** [Ultimaker/CuraEngine#208]
Are there any plans in the works to support the new 3MF file formats?

**Comment by Dim3nsioneer** [comment]
+1 for 3MF support (it happens quite rarely that big players agree early on a file format)

**Comment by daid** [comment]
Not directly in the engine. The engine is passed 3D data from the frontend in a uniform way. The STL loader is just to assist in debugging.

So Ultimaker/Cura will most likely get 3MF support at some point (even tough Microsoft initially said it was only an internal exchange format when I got air of it a year ago)

**Comment by PatternSpacePrime** [comment]
Daid, I tried looking for your email to contact you directly, but was unable to find it so I'm going to post this here: If I wanted to contribute to the project by adding 3mf support to Cura, should i do it in the Engine or the front end project? And if front end, what's the difference between the Ultimaker/Cura repo and the Daid/Cura repo? And if I use the Daid repo, what branch should i use? PinkUnicorn? SteamEngine? Master? 

Thanks.

**Comment by daid** [comment]
d.braam@ultimaker.com is my email. But I rather keep most discussions public :-)

Daid/Cura is the legacy (currently released) Cura, and works with the Ultimaker/CuraEngine#Legacy branch. No new development is done on this, only bugfixing.

Ultimaker/Cura is the new development. Currently in beta testing. It uses Ultimaker/CuraEngine#master branch, and new developments should go here.

**Comment by PatternSpacePrime** [comment]
Thank you, Daid. I will close this issue and start looking into contributing to the Ultimaker/Cura Project.

**Comment by BagelOrb** [comment]
This issue might be of interest: https://github.com/Ultimaker/CuraEngine/issues/206
