### ISSUE TITLE
Stutter in spiralized vase

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#214]
When using the spiralize outer feature, and unchecking solid top, on a solid vase model in cura, the output code has bad moves. The layer view looks perfect, but in roughly the same spot on each lap (but not every single lap) Cura makes a little stutter move with the print head. It basically moves backwards 1-2mm then continues forwards. It is almost hard to see with your eye unless you are looking for it, but the print shows a telltale scar. This occurs at the "layer change" area of the code.

![image](https://cloud.githubusercontent.com/assets/12439543/7961301/40b6527c-09cc-11e5-94bc-f85bfd0358f4.png)

![image](https://cloud.githubusercontent.com/assets/12439543/7961304/4664fb24-09cc-11e5-910a-59c3b7c6c090.png)

![image](https://cloud.githubusercontent.com/assets/12439543/7961309/4e10f7f6-09cc-11e5-8dd8-928552198ae9.png)

Gcode:
https://dl.dropboxusercontent.com/u/60958586/Doggy%20Vase.gcode

Forum thread:
https://ultimaker.com/en/cura/view/16189-cura-1504-spiralized-vase-stutter-scar?page=1#reply-108615

**Comment by BagelOrb** [comment]
Did you encounter this problem on the old cura or in the new CuraEngine?

**Comment by CCS86** [comment]
Good point, this is on Cura 15.04, so I'm not sure it applies to the new engine or not. A moderator on the UM forum liked me here to submit it.

**Comment by nallath** [comment]
15.04 is the old engine.

**Comment by BagelOrb** [comment]
I think the Spiralize option is bugged in the new Cura as well.
Can you maybe provide a link to the stl? I am in need of a typical spiralize model.

**Comment by CCS86** [comment]
https://dl.dropboxusercontent.com/u/60958586/Doggy%20Vase.stl

**Comment by CCS86** [comment]
Here is the same model sliced in the new engine. The bug still exists, but now instead of a G1 move backwards ~once per lap, it is a rapid move forwards:

![image](https://cloud.githubusercontent.com/assets/12439543/7985439/609664ea-0a96-11e5-8088-4b2a41fb9779.png)

**Comment by BagelOrb** [comment]
This is a different bug.
The move forward is most probably due to the fact that each layer a new starting point is selected, which is closest to the old one. Perhaps there is no other vertex closer. It would then be an enhancement to find the closest point on a line segment, instead of the closest vertex of a polygon in the next layer. However, such optimization might be a considerable hit on performance, since we need to interpolate on each line segment.

The other possibility is that the wrong point is selected while there is a vertex that is closer. This would be a bug.

I will need to dig into this in order to solve it.

Perhaps you can easily see whether the points in the next layer contain a point which is closer to the end point of the previous layer?
If I would know that I could easily disambiguate between the two cases.

**Comment by CCS86** [comment]
In a spiralized print, there is no need for a true "layer change". I know that Cura wants to segment the print that way, which is fine. In that case, why wouldn't the "layer" start at the same point it ends? It shouldn't need to find different vertices for layer start and end points.

**Comment by daid** [comment]
Because the whole spiralize implenentation is a huge hack.

**Comment by BagelOrb** [comment]
Yes, I am not going to rework the whole slicer engine for a correct way to print spiralized prints.

**Comment by CCS86** [comment]
Why would you have to rewrite the entire engine? 

Spiral vases seem like a pretty legitimate type of print. You guys just don't care?

**Comment by daid** [comment]
> You guys just don't care?
Yes. (Honesty is hard)

**Comment by CCS86** [comment]
That didn't seem very hard for you. If you want to let a relatively simple programming task defeat you, so be it. Others have solved it.

**Comment by daid** [comment]
We hate relatively simple tasks. But you are free to send us a bunch of money so we actually can get paid to fix this for you.

**Comment by BagelOrb** [comment]
Oh that diad.
Spiralize is not a high priority atm. There are more pressing issues.
Moreover, spiralize is working quite fine now.

Note that the issue is still open: 
The layers should have smaller connections; there are vertices closer to the last point on the previous layer. This might just be an issue concerning non-spiralize mode as well.

**Comment by CCS86** [comment]
Hahaha, Daid, I don't remember you being this bitter! I have sent you guys a bunch of money for my printer, supplies, HBK, etc. I would have even bought Cura as well, but you sold me junky-ass netFabb instead!

Thanks Bagel, glad it's still on the radar. How do you figure that it is working "quite fine" though?

**Comment by nallath** [comment]
Cura is not owned by ultimaker, just heavily supported by it.

**Comment by daid** [comment]
And I have a tendency to get grumpy and mean when people act like I haven't done shit for them, while they have been using my software, for free, for years. And then suddenly complain that I won't make major changes for them for a minor feature.

**Comment by CCS86** [comment]
Wow, you sure "read" quite a lot in between the very few lines I wrote. Definitely not sure which part implied to you that I think so little of you, or your contributions.

I have used, on and off, Cura for years, and have tried to be an active member in regards to diagnosis and feature suggestions for that time. Could you really get a piece of software like this fully sorted without any help from users? It seems strange to work hard on a piece of software intended for free distribution, then treat users as if they are freeloading assholes for using it and wanting it to be the best it can be.

Either charge for it, open an official donation system, or distribute it for free and be happy that people appreciate your work.

**Comment by nallath** [comment]
" That didn't seem very hard for you. If you want to let a relatively simple programming task defeat you, so be it. Others have solved it." <- Im going to interupt your train of thought here.

Before that statement, we, as the developers, told you that this was going to be hard. Yet you decided to add an insult. Is it really that strange that people respond like that?

**Comment by BagelOrb** [comment]
This is getting quite out of hand.
Snap out of it! :P
This is not the time nor the place for argue.

Anyway, I am still interested in the bug which is brought to light here: the first vertex on the next layer is not the one closest to the endpoint of the previous layer.

I will have to check whether it also occurs in non-spiralzie mode.

**Comment by BagelOrb** [comment]
PS: the reason I deleted the discussion is that this is an issue tracking system and I don't want this bug to get lost in the discussion.

**Comment by gr5** [comment]
This bug occurrs in non-spiralize also.  I'm 90% sure.  So it's not related to spiralize so much that it's more obvious.

**Comment by gr5** [comment]
I don't think this is a bug.  The vase is broken into triangles and it's possible that none of the lines in these triangles are vertical such that when you pick the "closest point" on the next layer up you probably have to get offset by roughty the amount of layer height (if the triangle is tilted 45 degrees along its edge).  Even if you could tell your CAD to have as many vertical edges as possible in your STL file, when you slice these to lines in a layer, half the points will be on a vertical edge and half on a tilted edge.  Some CAD programs are probably worse about this than others.  The simplest fix I can think of is to predetermine all the layer change points before you slice - try to pick a path up the side of the vase that is as vertical as possible - this is kind of a traveling salesman problem so not easy but not unreasonable either as you can just find "a" good path, not the "best" path.  Still quite a bit of code to write!

**Comment by Ghostkeeper** [comment]
I tried reproducing it in Cura 15.04. For this I made a sphere in OpenSCAD with the command:

    sphere(r=10,$fa=0.5,$fs=0.5);

[Here is the resulting STL file export.](http://dulek.net/Sphere.stl)

When using spiralise, I was able to reproduce the bug CCS86 shown would occur in the *new* engine, with the little G1 move once per lap causing gaps. I couldn't find any of the moves outside of the model as in the original bug report. When not in spiralise mode I didn't get such bugs but I found something that may be related and made a screenshot of it:

![sphereslicing](https://cloud.githubusercontent.com/assets/2448634/8021597/ff9a5e6e-0ca5-11e5-9152-9dba5ef4397e.png)

See the little upwards move on the right there. I also remember seeing this in @BagelOrb's tests of the improved combing. This one occurred in Sphere.stl, layer 224 when slicing with layer height 0.06, shell thickness 0.4, bottom/top thickness 0.6 and no support (the rest of the settings on default).

They are also travel moves, but they seem to be far too long to travel to the next layer.

**Comment by CCS86** [comment]
Other users are finding evidence that this isn't a bug specific to the spiralized option, but with the layer start point logic, it is just much more apparent with that type of print. It would seem that if this is true, improving the layer start point logic could help all types of prints.

If I understand correctly, we have ended a layer at a vertex of a line segment, where a facet intersected with the current XY plane. Now we need to connect that point, with the next slice.

Could we then find the closest vertex on the next layer, which is generally in the same direction as the last print move? You could find the closest two vertices, one should be "ahead" of the nozzle, and the other "behind". Then, look at the average delta X and delta Y over the last 'n' number of print moves, and see which of the two vertices has deltas in the same direction(s). The first move of the next "layer" is then a linear print move from the ending vertex to the closest forward vertex.

**Comment by BagelOrb** [comment]
@Ghostkeeper, what you see there is a retraction.

@CCS86: I should indeed think it would be as simple as that - or even more simple: we should only look at the very last move direction.

**Comment by CCS86** [comment]
@BagelOrb : My thought behind looking at an average was that you may have been moving primarily in say X+, and meandering in Y. Maybe, the Y moves were mostly positive, but the last couple crossed over into Y-. Looking at the average could differentiate between these.

It's hard to say whether this would actually be a benefit or not, as it's hard to picture every possible situation that comes up with the wide variety of models people slice (something I'm sure you guys struggle with regularly). At least writing the code in as such would allow for testing different sample lengths to see any practical benefits/drawbacks, with the ability to set n=1 to look at just the last move.

**Comment by CCS86** [comment]
Hi guys, glad to see the new version made its official release!

I tested the spiralized function again, and found it to be similar to my report above. I don't see any real issue with the identification of the next set of coordinates when "changing layers", which is good because that is the most involved process.

Basically as I see it, the only issue is the replacement of a print move, with a dog legged rapid. Cura posts (in this case) a ~2mm rapid move, followed by a much smaller rapid, then resumes printing. If we could just get it to make a printing move to that final coordinate set instead, I think there would be no issue:

Code with bug:

G1 X87.188 Y140.246 Z2.699 E671.56797
;LAYER:24
G0 F12000 X85.280 Y139.347
G0 X85.246 Y139.441
;TYPE:WALL-OUTER
G1 F1500 X84.361 Y139.015 E671.57413


Fixed:

G1 X87.188 Y140.246 Z2.699 E671.56797
;LAYER:24
G1 X85.246 Y139.441 EXXX.XXXXX
;TYPE:WALL-OUTER
G1 F1500 X84.361 Y139.015 E671.57413

Unfortunately, since the extrusions are being posted in absolute mode here, retroactively fixing this code would be fairly clunky.

Here are a couple pictures to illustrate:

![vase1](https://cloud.githubusercontent.com/assets/12439543/8508661/86060d1a-223e-11e5-8471-5196a46405c9.jpg)

![vase3](https://cloud.githubusercontent.com/assets/12439543/8508662/8ce803a4-223e-11e5-89f2-428d408b6998.jpg)

**Comment by CCS86** [comment]
![vase4](https://cloud.githubusercontent.com/assets/12439543/8508671/e3ee8114-223e-11e5-8725-50b4d3de80f6.jpg)

**Comment by CCS86** [comment]
the latest 11-17 build still has this same behavior.

**Comment by BagelOrb** [comment]
It's not exactly the same in 11-17. As a quick fix, when spiralize is enabled, the travel speed is set to the print speed, so that the hysteresis effects of the bowden tube will cause there to be less of a stutter.

Also you can set the Z seam alignment to [ Back ], so that the distance between the starting points of different layers is very small.

**Comment by CCS86** [comment]
I did some testing in the latest release. 

With Z seam set to shortest: 
[UM34_DoggyVase2-shortest.gcode.txt](https://github.com/Ultimaker/CuraEngine/files/254046/UM34_DoggyVase2-shortest.gcode.txt)

There is a small rapid backwards move after each lap. It looks like just deleting that move could help, but would still probably leave a small artifact, as there appears to be a slight XY shift:

![image](https://cloud.githubusercontent.com/assets/12439543/15099681/cde04dfe-1521-11e6-9d5b-084f1683860d.png)

![image](https://cloud.githubusercontent.com/assets/12439543/15099682/d2301d4e-1521-11e6-8383-7fa62d9bd745.png)

![image](https://cloud.githubusercontent.com/assets/12439543/15099683/d9516ede-1521-11e6-9ede-5acecdba0018.png)

**Comment by CCS86** [comment]
Other layers have a slight forward jump:

![image](https://cloud.githubusercontent.com/assets/12439543/15099702/53b8e3dc-1522-11e6-9170-79f0a9d9cc91.png)



Setting Z seam to back looks very similar.

**Comment by CCS86** [comment]
There is some very bizarre stuff going on in the bottom layer region though. Maybe there is a better setting than I am using:

![image](https://cloud.githubusercontent.com/assets/12439543/15099727/08f96e4c-1523-11e6-9f2d-dcd1631399bd.png)

**Comment by CCS86** [comment]
I tried switching to concentric for the bottom layers, I have all gap filling and wall overlap comp disabled.

In this gcode, it seems to get through the bottom layers, start spiralizing, then jump to printing non-spiral, bad moves at layer 155:

[UM34_Doggy Vase-conc.gcode.txt](https://github.com/Ultimaker/CuraEngine/files/254052/UM34_Doggy.Vase-conc.gcode.txt)


![image](https://cloud.githubusercontent.com/assets/12439543/15099762/86a61a74-1524-11e6-94f2-c020930a2d3b.png)

**Comment by BagelOrb** [comment]
The visualization bug of RepetierHost is llikely due to a bug in the gcode. I've seen this sort of thing happening with negative E-differences from one line to the next. *Please* attach the model and export your profile - preferably in a new github issue. This is quite a serious bug and might occur not only in spiralize vase mode.

**Comment by BagelOrb** [comment]
As for the travel moves: a small move in the XY direction is hard to avoid, but we could try replacing it with an extrusion move.

If you send me your profile I could slice the doggy vase with the option implemented and let you have a sneak peek at how it works.

**Comment by CCS86** [comment]
Sorry, if that wasn't clear. That huge artifact in the background of the last picture is just the header gcode extruding some stock on the way in.

The issue I'm seeing is a transition from bottom layers, to spiral, back to multi-perimeter, non-spiral layers. 

Happy to create a new issue if you'd like though.

**Comment by BagelOrb** [comment]
Ah alright. Yes, strictly speaking that is a separate issue. This thread is already getting quite long ;)

Shouldn't be that hard to fix, though.

**Comment by CCS86** [comment]
Okay, I split off that other bug into a new issue. 

There is still a small "stutter" bug in the spiral regions.

**Comment by CCS86** [comment]
I just wanted to update that with 2.1.1, the behavior is still there.

![image](https://cloud.githubusercontent.com/assets/12439543/15490409/3fec8388-212d-11e6-9d3d-7d72756f6c74.png)

**Comment by CCS86** [comment]
Choosing random seam, is pretty ugly:

![image](https://cloud.githubusercontent.com/assets/12439543/15490441/a45bc84c-212d-11e6-8ec5-c71f93111bc0.png)

**Comment by CCS86** [comment]
It seems to me that this move just represents the accumulated error of the XY positions at one layer versus the next. This means it is governed by overhang angle, and layer height. Thicker layers and larger overhangs exaggerate it.

.1mm layer height:

![image](https://cloud.githubusercontent.com/assets/12439543/15490606/2768cab8-212f-11e6-8d2a-0c93d608d9e5.png)


.2mm layer height:

![image](https://cloud.githubusercontent.com/assets/12439543/15490617/46ae32dc-212f-11e6-8740-d88532133e94.png)



It's hard for me to give a useful suggestion without knowing the algorithm. 

Maybe the front end could get the engine to slice at ~1/10 the commanded layer height, and use that to distribute the error more evenly?

Or compare the closest XY coordinate between subsequent layers, determine an XY distance, then interpolate using current Z height and apply preemptively?

**Comment by CCS86** [comment]
.02 mm layer, in a more vertical section of model: 

![image](https://cloud.githubusercontent.com/assets/12439543/15490768/ad1f88f8-2130-11e6-86d0-7865bec03986.png)

**Comment by CCS86** [comment]
Besides the XY shift, I feel like it should never do a backwards move like this. It should always move forward.

**Comment by BagelOrb** [comment]
The spiralize vase is a dirty hack. It just gradually increases z over each
polygon.

There is no (easy) way to avoid xy moves.

I don't think the backwards moves are high priority enough to put it on our
to-do list right now..
Op 24 mei 2016 04:53 schreef "CCS86" <notifications@github.com>:

**Comment by BagelOrb** [comment]
@gr5 please make a separate issue for that. Could you include some screenshots of what happens and say what you think should happen? 

Note that Cura will try to get the closest point, but also the point which is mostly in the same direction as it was travelling before, so that the first point is most optimal w.r.t. accelerations and jerk.

**Comment by BagelOrb** [comment]
Thanks to Mark Burton, we don't have a stutter in the spiralize mode any more!
:clinking_glasses:

**Comment by mattgit** [comment]
> I just wanted to update that with 2.1.1, the behavior is still there.
> 
> ![image](https://cloud.githubusercontent.com/assets/12439543/15490409/3fec8388-212d-11e6-9d3d-7d72756f6c74.png)

still there on cura 3.6.0
