### ISSUE TITLE
Error in  slicer

### ISSUE THREAD

**Issue by plgarcia** [Ultimaker/CuraEngine#216]
I hope this is the right place to record this issue.
I use cura 15.04. 
The gcode is incorrect that there is an extra face generated in the conduit.
See nozzle.stl and Nozzle.gcode here
https://drive.google.com/folderview?id=0B352dB2b8061UVlJSFRNVGJ1MlE&usp=sharing

**Comment by nallath** [comment]
Have you checked the model in x-ray view?

**Comment by plgarcia** [comment]
I can see that there is nothing in the conduit.
In xray mode they are things appearing in red. Errors in model as noticed daid.
I analyse to identify the cause ou the error and let you know.

**Comment by plgarcia** [comment]
Sorry the errr is mine. With FreeCad I end having faces crossing.
So I close the issue.
