### ISSUE TITLE
Inconsistent fills in Cura 15.06.2

### ISSUE THREAD

**Issue by Phalconheart** [Ultimaker/CuraEngine#223]
There seems to be inconsistent results depending on what value you enter for the infill amount. I had proper results at 30% and 20%, but at 25% the infill lines were randomly spaced and nowhere close to 25%.
![20_infill](https://cloud.githubusercontent.com/assets/13435775/8802113/3837d706-2f8d-11e5-9f7a-844de9e4cc41.jpg)
![25_infill](https://cloud.githubusercontent.com/assets/13435775/8802112/38354838-2f8d-11e5-970a-681590d1dd0c.jpg)
![30_infill](https://cloud.githubusercontent.com/assets/13435775/8802119/424f7c1c-2f8d-11e5-9a86-011a75d6a9db.jpg)

This is not just a display bug as I actually printed a model with these odd random infills and it actually printed with the infills as displayed in Cura.

Any ideas as to why?

**Comment by BagelOrb** [comment]
@Ghostkeeper that issue is not related.

**Comment by BagelOrb** [comment]
I'm sorry I lost track of this issue. 

I've done a lot about the infill in the mean time.

However, I'd like to be sure I solved your bug specifically. Can you send me the STL?
