### ISSUE TITLE
Cura.pb.h generated problem

### ISSUE THREAD

**Issue by dnsgkr2** [Ultimaker/CuraEngine#230]
Questions:
CuraEngine is missing file (Cura.pb.h) in CuraEngine Zip file

in CommandSocket.h
 #include "Cura.pb.h"
------------------------------------------------------------------------------------------
Answer:
Cura.pb.h generated from the cura.proto file

------------------------------------------------------------------------------------------
Dear..
I'm not sure.
Now is the compilation of a visual studio. But the file is not created.
Please tell us the way how to create Cura.pb.h file from cura.proto file..
Perhaps In the Linux environment, What is necessary is generated that you build in cmake?
thanks.

**Comment by nallath** [comment]
Use c-make or look at https://github.com/google/protobuf
