### ISSUE TITLE
Concentric Top/Bottom Pattern Enhancement

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/CuraEngine#235]
The concentric top/bottom pattern is generated from outside to center sometimes and center to outside others. When the pattern starts in the center of a section it has nothing to connect to. It would be best if the concentric "rings" were always built from outside to center.

**Comment by BagelOrb** [comment]
This will not be fixed soon; it sounds like an easier fix than it is.

**Comment by BagelOrb** [comment]
This is a duplicate of https://github.com/Ultimaker/CuraEngine/issues/225
