### ISSUE TITLE
Polygons in json are not recognised 

### ISSUE THREAD

**Issue by nallath** [Ultimaker/CuraEngine#236]
The FDMPrinter.json specifies a number of polygons, which are not recognised by the engine.

Error log;
Unrecognized data type in JSON: machine_disallowed_areas has type 4
Unrecognized data type in JSON: machine_platform_offset has type 4
Unrecognized data type in JSON: machine_head_polygon has type 4
Unrecognized data type in JSON: machine_head_with_fans_polygon has type 4

**Comment by BagelOrb** [comment]
Indeed, they are still only used by the frontend.

The problem is that the backend doesn't know what to do with an array yet.

**Comment by BagelOrb** [comment]
In general a setting value is a single string. The polygons break that rule.

I think for now it's okay to have this unimplemented.

Should I remove the error notice?

**Comment by nallath** [comment]
Yeah, but only for polygon arrays. Other not recognised settings should give an error.

**Comment by BagelOrb** [comment]
Then I would like to see some "type": "polygon" in the JSON.
I will do so.
