### ISSUE TITLE
Cura sets feedrate to 144720 mm/min on brief moves

### ISSUE THREAD

**Issue by gr5** [Ultimaker/CuraEngine#238]
Not a disaster but what gives?  more details here:
https://ultimaker.com/en/community/view/17259-cura-150603-strange-very-high-feedrate-motions-generated?page=1&sort=#reply-117070

**Comment by BagelOrb** [comment]
Some extrusion moves require very little extrusion. For moves extruding half the normal amount, the speed is doubled, so that the flow remains the same.

Apparently some moves required such little extrusion that the speed exploded. The speed is now capped at 9000 mm/min
