### ISSUE TITLE
Lower bed temp after n millimeters

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/CuraEngine#24]
There should be an option to lower the bed temp to a new set point (or a delta of the original set point) after a number of layers, or perhaps even better, a z value in millimeters.

**Comment by BagelOrb** [comment]
The use of the heated bed is for better bed adhesion, which is not something primarily present in the first layers. Indeed, the model should stick to the bed all the way. I don't see the logic behind the idea of lowering the bed temp mid print.
