### ISSUE TITLE
Infill combine: skip every x layers

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/CuraEngine#241]
now 3-layer infill is somehow computed per layer
![multilayer_infill_1](https://cloud.githubusercontent.com/assets/8895761/9785483/0a86a802-57b3-11e5-80ea-5f07bfb11403.png)
![multilayer_infill_2](https://cloud.githubusercontent.com/assets/8895761/9785484/0a8952a0-57b3-11e5-86d9-e1e7f4699765.png)

I would expect it to be computed every 3 layers, so that all 3-layer infill lines are in every third layer and not in layers in between.

**Comment by CCS86** [comment]
I'm having no luck with the combine infill setting in 15.09.85. Seems to just generate infill every layer when using "infill layers" set to 2

**Comment by BagelOrb** [comment]
Perhaps it's not viewing the combined layers. try to export to gcode and load it into the old Cura.

It seems to work at least on the latest version.

**Comment by BagelOrb** [comment]
No the view is also correct...

**Comment by CCS86** [comment]
Tried that.

**Comment by BagelOrb** [comment]
It's really strange it doesn't seem to work at all for you. 
I haven't had any such problems on any 15.10 pre-release...

What version are you testing on right now?
What model are you testing on?

**Comment by CCS86** [comment]
I am on 15.09.85 now. I just tried again on a simpler model, and it was working as expected.

But I still can't get it working with that starfish lampshade model. I scaled it down to 50% and disabled support for faster generation. With infill layers set to 2 and 35% density, I am getting infill every layer.
