### ISSUE TITLE
15.09.85: Duplicate infill on same layer

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#254]
I first noticed this behavior in watching this portion get laid down (not sure the name you have given it):

![image](https://cloud.githubusercontent.com/assets/12439543/10271323/9be7d8e4-6ad1-11e5-8d25-dbd1425a4f29.png)

I saw it repeat that area without changing layers. This obviously lead to over-extrusion. I thought maybe I had been mistaken, but then started a new print and had similar, but worse behavior. Basically, after finishing layer 1, instead of moving on, Cura laid down the exact same infill a second time at the same height. No new perimeter was laid down. This behavior continued and I had to abort the print.

Settings:

![image](https://cloud.githubusercontent.com/assets/12439543/10271378/e907dcae-6ad2-11e5-87d8-b28a092ab82a.png)

Gcode:

https://dl.dropboxusercontent.com/u/60958586/UMO_Controller.gcode

**Comment by Ghostkeeper** [comment]
Oh, maybe this is related to the overextrusion we've been seeing in the bottom layers recently?

**Comment by BagelOrb** [comment]
This issue is already solved. I don't recall if there was already a github issue, though.

The problem was pretty grave. For every next top/bottom skin area all previous skin areas would be reprinted.

Gladly it's now resolved.

**Comment by BagelOrb** [comment]
@awhiemstra When are you going to build another beta?
