### ISSUE TITLE
 Major change without major release bump

### ISSUE THREAD

**Issue by cederom** [Ultimaker/CuraEngine#257]
I just wonder why major rework of code in Cura and CuraEngine is done in the middle of 15 not 16rc1? People that get 15 think they get stable release while recent 15 releases introduced major changes in the code and dramatic bugs amount due to code reorganization.. :-(

**Comment by BagelOrb** [comment]
It's done in 15, because that's the year we live in - 2015.

**Comment by cederom** [comment]
Damn my time machine failed again! :-P

**Comment by daid** [comment]
And there is a "legacy" branch that is made just before all the re-work was merged. That can still be used if the old interfacing is required.

**Comment by BagelOrb** [comment]
Please keep us updated on the status of your machine. We are very interested, might it work some day.
