### ISSUE TITLE
Combing bug

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/CuraEngine#259]
Combing seems not to be optimized at the crossing between going straight and avoiding an object.

![curaengine_combing_bug](https://cloud.githubusercontent.com/assets/8895761/10366536/674874ca-6dcb-11e5-8a66-b4ad300e86ad.png)

**Comment by BagelOrb** [comment]
There is another combing bug which causes the 'avoid other objects' to **fail**.

![curaengine_combing_bug_2](https://cloud.githubusercontent.com/assets/8895761/10370876/23a5e6b0-6de1-11e5-8f40-6ac2d651e733.png)

**Comment by BagelOrb** [comment]
The latter bug is probably caused by faulty line - polyline intersection checks. The 'optimized' travel move crossed the polygon exactly at the crossings.

**Comment by BagelOrb** [comment]
Another bug, possibly related to the first.

slice -v -j ../Cura/resources/machines/ultimaker2.json -s travel_avoid_distance=.1  -o "output/test.gcode" -l "/home/tim/Documents/3D_models/combing/combing_evasion_Cura_out.stl"

![curaengine_combing_bug_3](https://cloud.githubusercontent.com/assets/8895761/10450556/5dab89ce-719b-11e5-8cc4-f07840a8e84d.png)

[combing_evasion_Cura_out.stl.txt](https://github.com/Ultimaker/CuraEngine/files/12326/combing_evasion_Cura_out.stl.txt)

**Comment by BagelOrb** [comment]
This is the model of the other problematic case, if I'm right.
[cube_cm_forrest.stl.txt](https://github.com/Ultimaker/CuraEngine/files/12375/cube_cm_forrest.stl.txt)

**Comment by Ghostkeeper** [comment]
I fixed the original issue (the optimisation of combing paths). The issue was very deep! I could never reproduce the second issue. The third issue, with the move path right through the two circles, still persists.

**Comment by BagelOrb** [comment]
You seem to have solved the second bug as well. I reproduced the bug, pulled your commits, and saw that the problem was solved.

**Comment by Ghostkeeper** [comment]
Perhaps that was dfd3184 then.

**Comment by BagelOrb** [comment]
Most probably!

**Comment by Ghostkeeper** [comment]
Got the third combing bug fixed in c0d22dcf7bf8c8383961520b7fe3d8294ab4e1b5. I should've added a `fixes #259` to that commit message...

More combing bugs remain, but different ones than the ones reported here.
