### ISSUE TITLE
Struggling to fill gaps consistently

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#277]
This model seems to be giving the engine fits. It is totally axisymmetric:

[Sheave.stl.pdf](https://github.com/Ultimaker/CuraEngine/files/40921/Sheave.stl.pdf)

This is with gap filling turned off:

![image](https://cloud.githubusercontent.com/assets/12439543/11320480/feee30d4-905e-11e5-98a2-c70678241c8d.png)

And the same layer with it on, you can see that it is overlapping perimeters badly:

![image](https://cloud.githubusercontent.com/assets/12439543/11320485/237a4988-905f-11e5-95f6-285699c5c189.png)

Another layer:

![image](https://cloud.githubusercontent.com/assets/12439543/11320489/39175f6a-905f-11e5-9f87-676323d23575.png)

**Comment by BagelOrb** [comment]
In the third picture I seem to see double infill, is that correct?

This might be quite a serious bug.

Filling inter perimeter gaps should leave the merged infill lines as they are.

**Comment by BagelOrb** [comment]
Around layer 74 I see double infill.

**Comment by BagelOrb** [comment]
Solved!

**Comment by CCS86** [comment]
Sweet. Is this just in regards to the double infill, or also the sporadic disorder?

**Comment by Ghostkeeper** [comment]
Just the double infill, as far as I can tell from the commits.

**Comment by BagelOrb** [comment]
The sporadic disorder is not going to be fixed any time soon.
Op 27 nov. 2015 09:28 schreef "Ghostkeeper" <notifications@github.com>:
