### ISSUE TITLE
shell thickness / wall thickness doesn't work with surface mode surface

### ISSUE THREAD

**Issue by rooiejoris** [Ultimaker/CuraEngine#284]
It seems that shell thickness / wall thickness doesn't work with surface mode surface
is this only dependend on the nozzle and flat part of nozzle size in the machine settings?

[Is it an idea to rename the flat part size 'shoulder size'...?!]

cheers / joris

**Comment by BagelOrb** [comment]
Shell thickness and wall thickness determine the number of wall perimeters.
What you are looking for is wall line width.
Op 6 dec. 2015 01:12 schreef "rooiejoris" <notifications@github.com>:

**Comment by rooiejoris** [comment]
thanks! I didn't expect that settiing under quality I guess, sorry...!!

[this can be closed or even deleted...]
