### ISSUE TITLE
Missing Support Lines

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#287]
I'm seeing two issues with support generation. One is that some layers are missing portions of the intended support line:

Complete:
![image](https://cloud.githubusercontent.com/assets/12439543/11822209/2021142e-a333-11e5-842b-1342196abcff.png)

Incomplete:
![image](https://cloud.githubusercontent.com/assets/12439543/11822213/256f29d4-a333-11e5-8045-76f89ff8d593.png)
![image](https://cloud.githubusercontent.com/assets/12439543/11822217/289cb022-a333-11e5-8be4-001f772070ae.png)

Also, if you look at the progression. The support in this region is stair stepping outwards, but is doing so in fairly large increments. I'm not sure this would physically work.

Both the gcode file and the model can be found here:

https://github.com/Ultimaker/CuraEngine/issues/286

**Comment by Ghostkeeper** [comment]
Thanks for the report. Seems that at the least the default step size needs to be tweaked, and at the most there is still a bug with the support areas.

**Comment by BagelOrb** [comment]
As for the missing support lines: see https://github.com/Ultimaker/CuraEngine/issues/265 .

The bottom stair step height will create steps which bridge gaps depending on the angle of the model where it sits. If the bottom has a very slight angle, the steps will be quite big. However, the stair step height is quite low by default (0.3mm), so the lines don't really have the chance to sag.

Note that a smaller X/Y distance might also help to make those new steps sit on the model without falling too much.

**Comment by CCS86** [comment]
I'm a little confused, #265 was marked closed because this issue (#287) is a better description. But this issue is marked closed as well.

**Comment by BagelOrb** [comment]
No, this issue is marked as a bug ;)

**Comment by CCS86** [comment]
My bad :)

**Comment by BagelOrb** [comment]
[ SOLVED ]
:D
