### ISSUE TITLE
Wall Wipe

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/CuraEngine#288]
Perform an travel move called 'overshoot' after printing each polygon, so that the start and end of a polygon attach better.

After printing a polygon, make a small move in the direction of the first line segment.

**Comment by CCS86** [comment]
Sweet!

**Comment by CCS86** [comment]
Would this be specific to coast moves?

**Comment by BagelOrb** [comment]
I don't see why.

Actually, now that I think of it, it doesn't really make sense to have this feature. It already ends exactly where it began, so there already is a complete overlap between the nozzle hole area and the already printed start line segment.

What was your idea for requesting this?

**Comment by CCS86** [comment]
Just to minimize seams. Regardless of coast volume, I see a pucker inwards at the seam. By keeping the coast speed at 100%, it avoids bulging out, but I get a small pucker inwards with coast volume very small ( ~.02 mm^3 ), or large (~.23 mm^3).

**Comment by CCS86** [comment]
I am really anxious to get a new beta build with the "coast retract order" bug fixed, so I can keep testing it.

I'm up to .23 mm^3 move-coast volume, and the seams are getting really good. I haven't tried longer coast moves yet.

**Comment by BagelOrb** [comment]
I think the pucker inward is the downside to not having the bulging out. I
think that the problem should be resolved by gradually turning down the
speed, as you mentioned in another issue.
Now, at the end of a coast the pressure is lowest and so the maximal flow
is probably too low for the bleeding off to ooze the correct amount.
Op 16 dec. 2015 23:27 schreef "CCS86" <notifications@github.com>:

**Comment by BagelOrb** [comment]
Implemented
