### ISSUE TITLE
Internal dimensions smaller than model

### ISSUE THREAD

**Issue by karabas** [Ultimaker/CuraEngine#29]
Printing with ABS Nophead's calibrating model cal.stl from his repo shows the same problem as other slicers do. Internal dimentions are smaller and nuts do not fit.
Nophead:
"I had a look at the source code and it appears to assume all extrusions are rectangular, so the outlines will come out thicker than it allows for, hence why holes are too small."

**Comment by BagelOrb** [comment]
You can shrink the print in xy direction by adjusting the Horizontal Expansion - make it negative.
