### ISSUE TITLE
wirePrint in console/Repetier-Host

### ISSUE THREAD

**Issue by klbko3** [Ultimaker/CuraEngine#300]
I was trying wirePrint in CURA 15.06.3 and it look nice, except it doesn't show correctly and then i try load gcode to Repetier-Host and it shows it good.

So I was wondering if there is any possibility to use wirePrint with curaEngine in Repetier-host or console?
And how to do it

Thanks

**Comment by BagelOrb** [comment]
I think Repetier host is working with an outdated version of CuraEngine which doesn't have wireprinting yet.

I'm afraid you will have to save the gcode and visualize load it into repetier-host by hand for now.
http://chilipeppr.com/tinyg also works pretty well.

**Comment by klbko3** [comment]
Thanks for quick answer
