### ISSUE TITLE
build fails, arcus/error.h no such file or directory

### ISSUE THREAD

**Issue by Robertbaelde** [Ultimaker/CuraEngine#301]
I get the following error when i try to build the cura engine. 
I've installed all dependency's. 
``
[  2%] Built target clipper
[  4%] Building CXX object CMakeFiles/_CuraEngine.dir/src/commandSocket.cpp.o
/root/cura/CuraEngine/src/commandSocket.cpp:12:25: fatal error: Arcus/Error.h: No such file or directory
 #include <Arcus/Error.h>
                         ^
compilation terminated.
make[2]: *** [CMakeFiles/_CuraEngine.dir/src/commandSocket.cpp.o] Error 1
make[1]: *** [CMakeFiles/_CuraEngine.dir/all] Error 2
make: *** [all] Error 2
``

**Comment by ynilsiam** [comment]
You need to Install libArcus (see https://github.com/Ultimaker/libArcus).

**Comment by Robertbaelde** [comment]
i've already installed that using the instructions provided..

**Comment by nallath** [comment]
Did you install the right branch? We've been messing around with how libArcus works.

**Comment by Robertbaelde** [comment]
I installed the master branch, should i use another one?

**Comment by Ghostkeeper** [comment]
We should really backmerge those changes, by the way...

You seem to have CuraEngine in the 2.1 branch, Robert. There's a 2.1 branch for libArcus as well.

**Comment by nallath** [comment]
Or use CuraEngine in master and LibArcus in 2.1

**Comment by pietrondo** [comment]
Same problem with archlinux and cura-engine-git

**Comment by pietrondo** [comment]
```
src/CuraEngine/src/commandSocket.cpp:12:25: fatal error: Arcus/Error.h: No such file or directory
compilation terminated.
CMakeFiles/_CuraEngine.dir/build.make:118: recipe for target 'CMakeFiles/_CuraEngine.dir/src/commandSocket.cpp.o' failed
make[2]: *** [CMakeFiles/_CuraEngine.dir/src/commandSocket.cpp.o] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/_CuraEngine.dir/all' failed
make[1]: *** [CMakeFiles/_CuraEngine.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by BagelOrb** [comment]
Did you try building libArcus from the 2.1 branch instead of master?

**Comment by Robertbaelde** [comment]
Tried installing it with the libArcus 2.1 branch and it worked!

**Comment by awhiemstra** [comment]
Everything should now also be in master, so that should be ok now.
