### ISSUE TITLE
Wierd raster through model using default machine templates

### ISSUE THREAD

**Issue by Robertbaelde** [Ultimaker/CuraEngine#305]
Hi,

When i run the engine to slice a simpel test model, i get a wierd raster through the model.
This raster starts at layer 6 and runs arround/through the entire model. 

I used the standard cura machine settings for a prusa i3. 

Is this normal? How can i fix this? See sreenshots from the gcode (cura) for example

![7128cca71c86b4ba042013472e1a4b9f](https://cloud.githubusercontent.com/assets/4356288/13030385/2f9c5620-d2a9-11e5-84d5-dd38f7047958.png)
![7f84e3efc420f630df25c795ecc0f916](https://cloud.githubusercontent.com/assets/4356288/13030386/2f9fb28e-d2a9-11e5-8c0a-56ff5eea6dbb.png)

Gcode (remove .txt) 
[blokje.gcode.txt](https://github.com/Ultimaker/CuraEngine/files/129434/blokje.gcode.txt)

the stl file
[blokje_10_20_30.zip](https://github.com/Ultimaker/CuraEngine/files/129435/blokje_10_20_30.zip)

I've tested it with other stl files, and those have the same issue..

**Comment by BagelOrb** [comment]
Your fdmprinter.json is out of date. Probably your Cura repo is still on
the 2.1 branch while CuraEngine is on the master branch..

What you are seeing is an infill overlap of 10mm instead of 10%
Op 13 feb. 2016 23:28 schreef "Robertbaelde" <notifications@github.com>:

**Comment by BagelOrb** [comment]
Current development is on a 2.1 branch for each repo involved.
Op 14 feb. 2016 15:08 schreef "Tim Kuipers" <t.kuipers@ultimaker.com>:

**Comment by Robertbaelde** [comment]
tnx, switching to 2.1 worked
