### ISSUE TITLE
G code, stl through surface

### ISSUE THREAD

**Issue by Robertbaelde** [Ultimaker/CuraEngine#306]
When i slice a model with cura engine, it appears to go through the floor. and therefore not generating the bottom part of the models gCode. Is this a bug? or is there a build in function to fix this?

Rendered G code from curaengine
![fe4c88a283b16167980e3dc858fc2875](https://cloud.githubusercontent.com/assets/4356288/13060367/221e6e0a-d431-11e5-9f4f-ba42e48ab871.png)

Same stl in cura:
![c1fc4671654d3367c3153364ca999878](https://cloud.githubusercontent.com/assets/4356288/13060371/23d0e926-d431-11e5-925c-b6eaf24e60f1.png)

**Comment by BagelOrb** [comment]
In CuraEngine the origin with which the model was exported is used to
define bed level..
Op 15 feb. 2016 22:12 schreef "Robertbaelde" <notifications@github.com>:
