### ISSUE TITLE
Inconsistent coasting distance

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#308]
Hi guys,

I'm running the 2/20 build and am seeing what appear to be different coasting distances/ volumes between outer and inner perimeters. 

What do you think?

![image](https://cloud.githubusercontent.com/assets/12439543/13241953/896ec346-d9b5-11e5-8614-43efd2a630a5.png)

**Comment by BagelOrb** [comment]
It seems to me that the inner perimeters don't have enough volume to build
up the pressure to coast the full amount.

This is a feature, not a bug ;)
Op 23 feb. 2016 05:42 schreef "CCS86" <notifications@github.com>:

**Comment by CCS86** [comment]
I should have read the new tool tip!

I didn't realized you had implemented linear scaling to the coasted volume. Awesome!

So, now there is no separation of comb/retracted coast moves?

**Comment by BagelOrb** [comment]
nope, both retraction coasting and non-retraction coasting are the same... The retraction is delayed until after the coast move.
