### ISSUE TITLE
How to force concentric pattern all the way through

### ISSUE THREAD

**Issue by ynilsiam** [Ultimaker/CuraEngine#315]
Is there any setting that I can force CuraEngine to use concentric pattern always?
[https://drive.google.com/open?id=0B7Pb9W43cq3lNTY1WjRFcTAtdUU](url)
In the middle it goes zigzag pattern.

Thanks,

**Comment by Ghostkeeper** [comment]
Set the setting "Fill Gaps Between Walls" (under Shell) to Nowhere. It'll be empty then though. It's doing the zigzag pattern there because it's too small to fill it with another wall.
