### ISSUE TITLE
MACH3 Gcode flavor is using wrong parameter prefix in M codes

### ISSUE THREAD

**Issue by kniftar** [Ultimaker/CuraEngine#316]
MACH3/LunuxCNC requires "P" as a prefix for mcode parameters.  CuraEngine is currently using "S" when MACH3 is selected.  Should be:
M109 P#
M104 P#
M190 P#
M140 P#

**Comment by BagelOrb** [comment]
Ok, good to know.

I don't think we will fix this any time soon, cause supporting third party
printers isn't exactly high on our priority list.

However, if you would fix the code, we can incorporate the fix into Cura.
We're always up for considering a pull request.
Op 5 mrt. 2016 20:52 schreef "kniftar" <notifications@github.com>:

**Comment by Ghostkeeper** [comment]
It could also be implemented as a post-processing script in Cura.

The alternative is going through CuraEngine and making the M-codes it writes dependent on the `machine_gcode_flavor` setting.

**Comment by kniftar** [comment]
Right,  if I get some time I would like to try and help fix this but never using github or contributing to a project it seems like a bit of a learning curve.  I have a little C programming experience but no cpp.  That being said it looks like a simple fix. I do see where the Mcodes are written in gcodeExport.cpp and for what it's worth the G04 (Dwell) is also different for mach/machinekit/linuxcnc.  It's parameter is seconds not milliseconds.

**Comment by BagelOrb** [comment]
You should create a fork from this github. In the *fork* you van edit
whatever you want. Then when you're done, create a *pull request* to submit
your code to us.

Google the last step if you don't know how.

There is an option to not depend on arcus, which should make the build
process a lot easier ;)

Good luck!
Op 9 mrt. 2016 05:20 schreef "kniftar" <notifications@github.com>:

**Comment by kniftar** [comment]
errrr, I'm not having much luck building from source and I usually can figure this stuff out.  I've tried cura-build to make a package and also the ubuntu15.04 install script in the cura-build repo. I've tried both on new vanilla installs of ubuntu 15.04, 15,10 and 16.04.  Seems arcus is the spoiler and I don't see the option to remove the dependency.  Could anyone share a recipe for this that works?  Thanks much..

**Comment by BagelOrb** [comment]
Set ENABLE_ARCUS to FALSE and CMAKE_BUILD_TYPE to RELEASE

**Comment by BagelOrb** [comment]
Also you can set BUILD_TESTS to FALSE

**Comment by Renha** [comment]
> There is an option to not depend on arcus, which should make the build
process a lot easier ;)

woooooow! and all would still work?

**Comment by BagelOrb** [comment]
That should work. I don't know if the option is still intact after the
merge from 2.1 to master, but hopteelt it is!

Note that without arcus the engine cannot communicate with the frontend...
Op 13 apr. 2016 12:28 schreef "Renha" <notifications@github.com>:

**Comment by BagelOrb** [comment]
The whole platform is below Z=0...

**Comment by Renha** [comment]
oh, I see. Well, building without arcus works, i've just checked. Package for Arch is cura-engine-noarcus-git at AUR in case if someone need it.

**Comment by BagelOrb** [comment]
outdated
