### ISSUE TITLE
Feature: low infill to allow filling with foam

### ISSUE THREAD

**Issue by AndresBott** [Ultimaker/CuraEngine#319]
my idea is to desing a new and faster way to build strong pieces,
instead of using high infill values (increasing print time)

Add a new low infill pattern that would allow to make a hole in the piece and fill with a sort of foam like Polyurethane.

for example Standart crossed infill but with holes to allow the foam to get to the corners.

**Comment by BagelOrb** [comment]
You could try to get the result by using modifier meshes, a new feature of
cura 2.2
You would have to design a mesh for the places at which you want zero
infill and then supply the right settings to not print everything within
that mesh.

I will provide more info as soon as it's implemented fully..
Op 11 mrt. 2016 12:49 schreef "Andres Bott" <notifications@github.com>:
