### ISSUE TITLE
unknown target CPU 'pentium4' Failed to build CuraEngine 

### ISSUE THREAD

**Issue by donaldding** [Ultimaker/CuraEngine#322]
I tried to build CuraEngine for Windows on Mac OS X 10.10.5, but I  got this error

> g++ -c -Wall -Wextra -Wold-style-cast -Woverloaded-virtual -std=c++11 -DVERSION=\"15.04.6-RC1\" -isystem libs -O3 -fomit-frame-pointer -march=pentium4 -flto src/bridge.cpp -o build/bridge.o
> error: unknown target CPU 'pentium4'
> make: **\* [build/bridge.o] Error 1

Do I miss anything?

**Comment by daid** [comment]
The proper cross compiler?

**Comment by BagelOrb** [comment]
Outdated
