### ISSUE TITLE
Issue When Infill Thickness /= Layer Height

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#327]
I just attempted to slice a model with the 3/18 build, and set the layer height to 0.1mm, and the infill thickness to 0.2mm. The intention being to generate infill every other layer. What Cura generated is code that lays infill every layer.

Using Repetier to visualize, it doesn't seem that the extrusion amount is different for the infill (should be double the volume), the estimated time does not change, and the code is essentially identical, so it appears to be non-functional

![image](https://cloud.githubusercontent.com/assets/12439543/14389838/037517de-fd7a-11e5-9c91-ca85cb8067a9.png)

The only difference in gcode between infill thickness = 0.1 vs 0.2:

![image](https://cloud.githubusercontent.com/assets/12439543/14389993/916ffc5c-fd7a-11e5-8c63-5760582ab9c5.png)

**Comment by BagelOrb** [comment]
The new Cura will be released very soon. Hopefully next week.
I can't reproduce the problem on the current version.

Perhaps it's a rounding problem; what happens if you fill in 0.20001?

**Comment by CCS86** [comment]
No dice:

[0.2001 infill.gcode.txt](https://github.com/Ultimaker/CuraEngine/files/210538/0.2001.infill.gcode.txt)

[0.2 infill.gcode.txt](https://github.com/Ultimaker/CuraEngine/files/210535/0.2.infill.gcode.txt)

[0.1 infill.gcode.txt](https://github.com/Ultimaker/CuraEngine/files/210536/0.1.infill.gcode.txt)

**Comment by CCS86** [comment]
Bug still exists on the open beta build.

**Comment by BagelOrb** [comment]
I've never reproduced this bug. Are _you_ still seeing it?

**Comment by CCS86** [comment]
I think it was squashed in 2.1.2

Thanks!
