### ISSUE TITLE
The cover of clutter, the surface no retraction and z move

### ISSUE THREAD

**Issue by zifengtayu** [Ultimaker/CuraEngine#331]
![01](https://cloud.githubusercontent.com/assets/7849639/14883661/da9b08fc-0d71-11e6-9438-62e197d58028.jpg)
![02](https://cloud.githubusercontent.com/assets/7849639/14883660/da9adf08-0d71-11e6-81ce-84d261b468d8.jpg)

**Comment by Ghostkeeper** [comment]
Looks good, right? When combing is activated it doesn't penetrate the wall any more, so the red line gets shifted over further back to go around. What is the problem we're looking at in these pictures?

**Comment by zifengtayu** [comment]
the red line will destory the surface,need retraction and z hop when travel

**Comment by BagelOrb** [comment]
Then don't enable combing, but enable retraction and zhop
Op 29 apr. 2016 11:27 schreef "zifengtayu" <notifications@github.com>:

**Comment by CCS86** [comment]
This gave me a thought:

Could we have a setting to specifically disable combing on skin surfaces, but leave it enabled everywhere else?

**Comment by BagelOrb** [comment]
That's already implemented for the next release ^^
Op 29 apr. 2016 17:51 schreef "CCS86" <notifications@github.com>:
