### ISSUE TITLE
The surface is not delicate enough

### ISSUE THREAD

**Issue by zifengtayu** [Ultimaker/CuraEngine#334]
![11](https://cloud.githubusercontent.com/assets/7849639/15006510/52c20736-1204-11e6-888d-ed2046b1a4b0.png)

![12](https://cloud.githubusercontent.com/assets/7849639/15006571/c06ff522-1204-11e6-91c3-4294c9e68b74.jpg)

**Comment by zifengtayu** [comment]
the bottom one is sliced by CuraEngine

**Comment by nallath** [comment]
The important question is; Does it even matter? Is there a noticable difference when you actually print it?

**Comment by zifengtayu** [comment]
yes, The printing effect is very different

**Comment by nallath** [comment]
Could you post those pictures? We can't read minds ;)

**Comment by zifengtayu** [comment]
![22](https://cloud.githubusercontent.com/assets/7849639/15009501/39873b1e-1219-11e6-9da3-f0ba48604020.png)
![Uploading 22.png…]()


![Uploading 22.png…]()

**Comment by Ghostkeeper** [comment]
It looks to me like the top slicer actually tries to smooth low-polygon meshes explicitly. It looks like it creates G2/G3 commands to draw arcs.

**Comment by BagelOrb** [comment]
CuraEngine does perform some simplification to optimize the slicing
computation times.

Can you post your model please?

I will try to find out whether this is still problematic in the current
beta release.

2016-05-04 11:30 GMT+02:00 Ghostkeeper <notifications@github.com>:

> It looks to me like the top slicer actually tries to smooth low-polygon
> meshes explicitly. It looks like it creates G2/G3 commands to draw arcs.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Ultimaker/CuraEngine/issues/334#issuecomment-216810405>
>



-- 

Kind regards,



Tim Kuipers

Ultimaker BV



www.ultimaker.com

**Comment by zifengtayu** [comment]
I send you by email 644748251@qq.com

**Comment by zifengtayu** [comment]
In CuraEngine source code,which part i can change, to adjust the simplification, i can't find it.

**Comment by BagelOrb** [comment]
Search for uses of Polygons::simplify(...)

**Comment by zifengtayu** [comment]
thanks

**Comment by BagelOrb** [comment]
Simplify will remove a point if it's less than 5 micron away from a direct line which skips the point...

Do note that the new beta release has many improvements over 15.04. It could very well be that Cura 2.1 beta doesn't have this problem. Please download it from the ultimaker software page and try it out.

**Comment by BagelOrb** [comment]
This doesn't look too bad, right?
![smooth_curbs](https://cloud.githubusercontent.com/assets/8895761/15013047/52053838-11fd-11e6-9289-9b156b17539f.jpg)

**Comment by BagelOrb** [comment]
Hmm the old Cura actually looks better. Here's what 15.04 spits out:
![smooth_curbs_15 04](https://cloud.githubusercontent.com/assets/8895761/15014659/a83b0084-1207-11e6-8795-83068c0150ab.jpg)

**Comment by BagelOrb** [comment]
How did you solve the problem in the end?

What code changes did you make?

Could you make a Pull Request out of those code changes?

**Comment by BagelOrb** [comment]
This has been solved in Cura 2.3
