### ISSUE TITLE
Spiralized: Bug in Bottom Layers

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#337]
In this gcode, it seems to get through the bottom layers, start spiralizing, then jump to printing non-spiral, multi-perimeter moves at layer 155:

[UM34_Doggy Vase-conc.gcode.txt](https://github.com/Ultimaker/CuraEngine/files/254052/UM34_Doggy.Vase-conc.gcode.txt)

![image](https://cloud.githubusercontent.com/assets/12439543/15099762/86a61a74-1524-11e6-94f2-c020930a2d3b.png)

[DoggyVase2.zip](https://github.com/Ultimaker/CuraEngine/files/254081/DoggyVase2.zip)

**Comment by Ghostkeeper** [comment]
For reference, see also the discussion in https://github.com/Ultimaker/CuraEngine/issues/214.

**Comment by BagelOrb** [comment]
Solving this ASAP.

**Comment by BagelOrb** [comment]
There were some other issues which I solved along the way:
1) When there are multiple vases in one mesh, only one of the two layer parts would get spiralized
2) When you have compensate outer wall overlap enabled and there is a very thin piece in the vase, only the very last part of the outer wall would get spiralized.

**Comment by CCS86** [comment]
Great, thanks!

Any idea on the date for the next release?

**Comment by nallath** [comment]
In about 5-6 weeks (Depending on how well things go. We're doing some pretty major refactoring now).

**Comment by Ghostkeeper** [comment]
Actually, this is fixed as a patch in version 2.1. It should be released when it goes out of beta.

**Comment by CCS86** [comment]
Awesome, is that happening sooner?

**Comment by BagelOrb** [comment]
Yes, in a week or two. ^^

**Comment by Ghostkeeper** [comment]
Or whenever the marketing team is ready for it ;)
