### ISSUE TITLE
mm unit to the unit on the buildplate

### ISSUE THREAD

**Issue by sajjadul-wematter** [Ultimaker/CuraEngine#342]
Hello,

Pretty much every unit is mentioned in mm while the user create a CAD model. It seems that the mm unit is mapped to grid space that can only work with integer coordinates. Does this mapping gets started while reading the CAD model and storing into Mesh object or it happens only after the slicing operation ?

**Comment by daid** [comment]
Internally everything is calculated on microns, this conversion happens at the start of the slicing operation.

**Comment by BagelOrb** [comment]
Indeed it happens while building up the internal representation of a Mesh.
