### ISSUE TITLE
The cura language translate po to mo

### ISSUE THREAD

**Issue by zifengtayu** [Ultimaker/CuraEngine#343]
I use python language tool msgfmt.py there will have err,can you send me your translate tools

$ 3msgfmt.py cura.po

  File "./3msgfmt.py", line 236, in <module>
    main()
  File "./3msgfmt.py", line 232, in main
    make(filename, outfile)
  File "./3msgfmt.py", line 184, in make
    l = ast.literal_eval(l)
  File "C:\Python34\lib\ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Python34\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    msgctxt "@title:window"
                          ^
SyntaxError: invalid syntax

**Comment by Ghostkeeper** [comment]
To convert .po files to .mo we have a CMake target. It looks for all .po files in /resources/i18n/*/ and calls 3msgfmt on those. To execute it, try these commands from the Cura directory:

    mkdir build
    cd build
    cmake ..
    make

The CMake script basically calls this:

    ${GETTEXT_MSGFMT_EXECUTABLE} ${po_file} -o ${mo_file} -f

**Comment by zifengtayu** [comment]
thanks
