### ISSUE TITLE
Make Coasting Moves G1?

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#348]
Hi guys,

Am I correct that only G1 moves are modified with the feed override knob? If that's true, it would seem like the G0 coast implementation would cause a speed difference compared to normal printing moves, if the override was not 100%.

**Comment by BagelOrb** [comment]
Feed override knob??

Both the firmware and the slicing engine treat coasting moves wrong. Indeed
the engine should output G1s, but I think Marlin distinguishes between
travel and extrude moves based on the difference in E value.
Op 6 jun. 2016 18:35 schreef "CCS86" <notifications@github.com>:

**Comment by CCS86** [comment]
Whatever you want to call it. The override knob. Know what I mean?

I believe it leverages M220.

**Comment by BagelOrb** [comment]
I genuinely don't know which knob you are referring to, but M220 works on
travel and extrusion moves equally.
Op 6 jun. 2016 20:30 schreef "CCS86" <notifications@github.com>:

**Comment by CCS86** [comment]
![image](https://cloud.githubusercontent.com/assets/12439543/15835117/2aa66760-2bf4-11e6-8545-9291ad7133e6.png)

**Comment by CCS86** [comment]
I know the override functionality isn't enabled on every machine, but I believe it is on all Ultimakers.

**Comment by daid** [comment]
However, the firmware code does not distinguish between different moves with G0 and G1. They are identical for the firmware.

**Comment by CCS86** [comment]
I see, I see. I guess that means this is a non-issue then :)
