### ISSUE TITLE
Combing Disable on Top/Bottom

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#351]
Hi guys,

I remember someone saying that the official release would have at least an option to disable combing on top/bottom layers, to preserve the surface quality. 

I'm not seeing the option, or the behavior in 2.1.2. Is it still in process?

**Comment by BagelOrb** [comment]
It's not still in progress. I have already implemented it, but maybe not on
the 2.1 branch.

The current master branch is already miles different from 2.1.
Op 11 jun. 2016 20:24 schreef "CCS86" <notifications@github.com>:

**Comment by Ghostkeeper** [comment]
Yup, added with 2.2. https://github.com/Ultimaker/Cura/blob/master/resources/definitions/fdmprinter.def.json#L1708
