### ISSUE TITLE
Failed to read config

### ISSUE THREAD

**Issue by Br0xCz** [Ultimaker/CuraEngine#359]
Iam trying to slice with custom profile but when i do it tells me
` Line 1: No key value pair found Failed to read config`
 and uses default profile instead.
[default.txt](https://github.com/Ultimaker/CuraEngine/files/325989/default.txt)

**Comment by Ghostkeeper** [comment]
How did you slice? Via the command line? Or did you slice via Cura? That looks like a profile from a legacy version. 15.04 or earlier.

**Comment by Br0xCz** [comment]
Via command line on raspberry pi.

**Comment by BagelOrb** [comment]
As far as I know the engine doesn't read profiles.
Maybe you should check out the engine of Cura 2.

Cura 15.x isn't supported any more.
