### ISSUE TITLE
how can estimate slicing time or get slicing percent ?

### ISSUE THREAD

**Issue by roboticsexpert** [Ultimaker/CuraEngine#365]
i want to have slicing percent or slicing time to show user how much time he should wait for getting gcode ...

how can i do this ?

**Comment by BagelOrb** [comment]
I suppose you are using command line slicing rather than connecting via
command socket?

Use the argument -p
Op 27 jun. 2016 22:53 schreef "Mahdi Youseftabar" <notifications@github.com

**Comment by roboticsexpert** [comment]
thanks a lot ... 
i didn't find good documentation for using socket . if you know good place to find that please introduce it .

**Comment by BagelOrb** [comment]
Indeed it's not that well documented, but you should have a look at the
.proto file, how the engine works with it in commandSocket.h and you could
have a look at how the frontend sends messages.
Op 28 jun. 2016 01:40 schreef "Mahdi Youseftabar" <notifications@github.com

**Comment by Ghostkeeper** [comment]
Basically, you're going to need to write a program that uses [libArcus](https://github.com/Ultimaker/libArcus) to listen on some port for CuraEngine connecting. Then you can call CuraEngine with `CuraEngine connect -p <port>`.

Cura's front-end does the same here: https://github.com/Ultimaker/Cura/blob/master/plugins/CuraEngineBackend/CuraEngineBackend.py
