### ISSUE TITLE
Extraction of points

### ISSUE THREAD

**Issue by paulsabyasachi** [Ultimaker/CuraEngine#366]
Hi! I am trying to generate a Visualizer which can simulate a 3D printing process. I am using Cura libraries for point extraction. Right now I am confused as to where exactly in CuraEngine, the points are getting stored. writeGCode(GCodeExport& gcode) function in class GCodePlanner seems to generate the GCode by calling the function writemove() of class GCodeExport.

The whole process starts with slice() in main(). Can you please give me an example where I can get the points directly from main().

With best regards
Sabyasachi Paul

**Comment by Ghostkeeper** [comment]
I do advise to take the points from the resulting g-code if you wish to make a transparent print simulator. Cura writes all travel moves and retractions with `G0` commands, and all print moves with `G1` commands. It should be fairly simple to extract the coordinates from there, and you won't be dependent on a specific CuraEngine version or have your program break if CuraEngine changes.

The points in CuraEngine are created on the fly during the writing of the g-code, in various ways, mostly through modifying the vertices of polygons and through line-line intersection tests. They are then stored for a while in LayerPlanBuffer. Perhaps that buffer is somewhere you'd want to look?
