### ISSUE TITLE
MSVC build broken

### ISSUE THREAD

**Issue by sevaa** [Ultimaker/CuraEngine#377]
At some point, CuraEngine was compatible with Microsoft Visual Studio. Now it's not. Here are some of the reasons:
- reliance on unistd.h
- "min"/"max" as variable names (they're #defines in MSVC, unless overridden)
- variable length arrays
- reliance on __WIN32 #define - it's not defined anymore, use WIN32 instead

Notably, libArcus and protobuf build under MSVC fine.

**Comment by awhiemstra** [comment]
This is mostly due to MSVC's lacklustre support of C++11. Now that MSVC 2015 finally supports everything we need we can start looking at supporting MSVC again.

**Comment by sevaa** [comment]
I'm building with MSVC 2015 Update 3; VLAs are still not there, at least not enabled by default. IIRC, it's a C99 feature, not a C++11 one. Anyways, those can be trivially replaced with alloca().

**Comment by BagelOrb** [comment]
I don't think this is currently a problem for us, so I don't we will pick
it up any time soon.

We're always willing accept pull requests though.

Op 4 aug. 2016 16:06 schreef "Seva Alekseyev" <notifications@github.com>:

**Comment by sevaa** [comment]
Addressed, see pull request #383. At least now it builds, I haven't tested properly, since I'm not sure how.

**Comment by BagelOrb** [comment]
I'm sorry, we lost sight of this PR.
We will take a look soon; I've added an issue to our internal issue tracker.

**Comment by jellespijker** [comment]
Fixed #1639 
Tested on Visual Studio 2019 and 2022
