### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [Ultimaker/CuraEngine#38]
The functions "[printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output")" and "[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html "Terminate a process")" do not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/seccode/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function "[signal_FPE](https://github.com/Ultimaker/CuraEngine/blob/744f09eefbc80026e1863887db1ae0e425c75aa1/main.cpp#L362)".

**Comment by BagelOrb** [comment]
Please supply a pull request to remedy the situation.
