### ISSUE TITLE
comb bug

### ISSUE THREAD

**Issue by yushuiqiang** [Ultimaker/CuraEngine#382]
comb not right ,sometimes the travel path just crossing the boundery without retract

**Comment by yushuiqiang** [comment]
![fgfg](https://cloud.githubusercontent.com/assets/18329928/17700252/98e967f0-63f7-11e6-823a-3cf5ca418979.png)
the green path

**Comment by yushuiqiang** [comment]
[test pattern.6.stl.zip](https://github.com/Ultimaker/CuraEngine/files/420329/test.pattern.6.stl.zip)

**Comment by BagelOrb** [comment]
I think this is fixed in the new version of Cura. Soon version 2.3 will come out in a beta release.
