### ISSUE TITLE
Run several CuraEngine at same time

### ISSUE THREAD

**Issue by jiaxiaodong** [Ultimaker/CuraEngine#392]
When I run three CuraEngine at same time, each of them slicing a large stl file about 30MB, each task takes up one hundred percent of cpu resources. Finally there will be a task aborted and given segmentation fault error.
I wonder is this problem caused by my server or the CuraEngine itself. And how to solve it.
Thanks!

here is my profile
system: ubuntu 14.04 LTS (64-bit)
Memory: 8GB
Processor: AMD Phenom II X6 1100T Processor *6

**Comment by Ghostkeeper** [comment]
What aborts the task? The segmentation fault?

**Comment by jiaxiaodong** [comment]
I'm not sure what aborts the task. Maybe the proessor load is too heavy
There is a "segmentation fault" on terminal when the task aborted. And there will be a empty gcode file.

**Comment by Ghostkeeper** [comment]
It's possible you're running into memory problems, too. I can't reproduce it, in any case.

Does the engine write a log, maybe? There's not a whole lot we can deduce without one.

**Comment by jiaxiaodong** [comment]
Thanks for your reply. Here is the step to reproduce it. And there are my screen shot of each step
1. open 4 terminal, one of them enter the top commend watch the use of resource, and the others enter the "CuraEngine -v -o a.gcode aa.stl" 
![screenshot from 2016-09-21 20 48 35](https://cloud.githubusercontent.com/assets/4847371/18711731/dca22ede-803d-11e6-98a5-a9820c5a3fa5.png)
this picture shows that  each task takes up one hundred percent of cpu resources.

2.After few seconds, the task lower left corner of the screen is aborted, and said and given segmentation fault (core dumped)
![screenshot from 2016-09-21 20 48 39](https://cloud.githubusercontent.com/assets/4847371/18711849/589f7014-803e-11e6-8817-cc6e1aba1e0c.png)

**Comment by Ghostkeeper** [comment]
Well, no memory problem either, in any case. Seems to be a bug indeed, though I can't reproduce it yet.

**Comment by jiaxiaodong** [comment]
My version is 14.12. 
How about your resourse condition? You may open more than three slicing tasks to reproduce it.

**Comment by Ghostkeeper** [comment]
> "CuraEngine -v -o a.gcode aa.stl"

This is going to need at least the "slice" command, and a .def.json file. I used a mesh that was a half-sphere to try and reproduce it, but got no segfault.

**Comment by Ghostkeeper** [comment]
> My version is 14.12.
Ah, well there's your problem... That version is two years old. We find and remove a segfault issue in the engine every month or two. I suspect that whatever you're finding has been solved by now.

Perhaps you should try a newer version from software.ultimaker.com. Each Cura version comes with a CuraEngine that can still be run from the command line.

**Comment by jiaxiaodong** [comment]
Thank you very much.
I will try new version and show the result in the issue.
