### ISSUE TITLE
CuraEngine from command line with multiple extruders

### ISSUE THREAD

**Issue by tomwimmenhove** [Ultimaker/CuraEngine#403]
I'm trying to use the CuraEngine from the command-line with multiple extruders. 
The command line command I'm using is:

CuraEngine slice -v -j myMachine.json -o /tmp/data.gcode -e0 -l file1.stl -e1 -l file2.stl

In the settings file I set the "machine_extruder_count" default to 2.

In the gcode file I see no switching between extruders. It seems to print both meshes with the same extruder.

I've done a bit of digging in the source code and loadMeshIntoMeshGroup() is called with a different ExtruderTrain for each of the files, while, further in the code, (inside FffGcodeWriter::processLayer() ) when I check storage.getExtrudersUsed(), it seems that only extruder 0 is being used.

Am I missing something in the command-line or do I need to add things in the settings file for each extra extruder?  

Thanks in advance.

Regards,
 Tom

**Comment by Ghostkeeper** [comment]
I can't reproduce this. It works for me.

Does your definition file `myMachine.json` define any `machine_extruder_trains`, and do you have the extruder definition files that it defines? For an example, take a look at `ultimaker3.def.json`, which specifies that there is `ultimaker3_extruder_left` and `ultimaker3_extruder_right`. These are then loaded from `ultimaker3_extruder_left.def.json` and `ultimaker3_extruder_right.def.json`.

**Comment by BagelOrb** [comment]
This sounds like a bug, but given the fact that it works for the Ultimaker
3, my guess is that you need to make extruder definition files in which you
need to set the setting extruder_nr.
For the extruder files to be found you may have to set some environment
variable. See CuraEngine help.

Alternatively you could set these settings right after -e#
I.e. [...] -e0 -s extruder_nr=0 [...] -e1 -s extruder_nr=1 [...]

Op 21 okt. 2016 20:40 schreef "tomwimmenhove" <notifications@github.com>:

**Comment by tomwimmenhove** [comment]
Hah! I was under the assumption that n in the -e<n> argument defined the extruder number. I didn't realise extruder_nr had to be set. The -e<n> -s extruder_nr=<n> solved everything for me. Thank you guys so much!
