### ISSUE TITLE
writeInt2mm produces unprocessable values

### ISSUE THREAD

**Issue by erwint** [Ultimaker/CuraEngine#410]
Since 2.3.0 release I noticed my printer would not correctly start printing, as the bed would not come back up after the initial homing sequence. It worked with 2.3.0 beta, so I browsed all changes and suspect it got broken by dce8a4629f811f850344acf5c322023633719761,  which will cause low mm values to be formatted like `Z.2`(instead of `Z0.200`). I verified manually changing all those directly in the .gcode by adding a `0` in front of the decimal point (e.g. `Z0.2`) fixes the problem

**Comment by BagelOrb** [comment]
What printer do you have?

Do you know what type of firmware it uses?

Op 9 nov. 2016 20:16 schreef "Erwin Tratar" <notifications@github.com>:

**Comment by erwint** [comment]
A Qidi X-One, I have no idea what firmware it uses.

**Comment by Ghostkeeper** [comment]
It probably has home-cooked firmware. I couldn't find it either. All I found was that a bunch of people tried to put Sailfish on it.

**Comment by Ghostkeeper** [comment]
I wouldn't expect CuraEngine to leave out the initial zero before the radix, though.

**Comment by daid** [comment]
Caused bugs for the UM3 firmware initially as well (have now been fixed)

**Comment by BagelOrb** [comment]
I didn't know this caused problems for Griffin as well.

I've changed it for Cura 2.4
See https://github.com/Ultimaker/CuraEngine/commit/4aa1cc47f4f4f0b1163d27aa1fd1615f6fcf8356

Generally there will now be a stagering 7 more characters in the gcode! :stuck_out_tongue:

**Comment by daid** [comment]
Single wrongly wrote regexp to lift numbers from GCode parameters.

**Comment by BagelOrb** [comment]
@daid I don't understand what you mean

Op 11 nov. 2016 20:41 schreef "daid" <notifications@github.com>:
