### ISSUE TITLE
support bugg

### ISSUE THREAD

**Issue by lahure-c** [Ultimaker/CuraEngine#421]
Hi
I believe that there's bugg in the guessing of supports. Please read the detailed thread in the ultimaker forum:
https://ultimaker.com/en/community/34992-support-error

**Comment by BagelOrb** [comment]
See comments on forum post.

**Comment by lahure-c** [comment]
Sorry I cannot find the forum rules. Only that which should not apply here:
https://github.com/Ultimaker/Uranium/wiki/Bug-Reporting-Template

**Comment by BagelOrb** [comment]
That's no problem.

I just meant: see https://ultimaker.com/en/community/34992-support-error for why this issue is closed.

**Comment by Ghostkeeper** [comment]
For the lazy, the reason is that we already fixed this in version 2.4.
