### ISSUE TITLE
error: expected identifier before ‘...’ token when compiling the master

### ISSUE THREAD

**Issue by GerogeFu** [Ultimaker/CuraEngine#426]
when i try to compile CuraEngine in Centos 7 , after installing libArcus , i got these errors:

[  6%] Building CXX object CMakeFiles/_CuraEngine.dir/src/bridge.cpp.o
In file included from /usr/local/src/CuraEngine/src/pathPlanning/Comb.h:11:0,
                 from /usr/local/src/CuraEngine/src/gcodePlanner.h:8,
                 from /usr/local/src/CuraEngine/src/sliceDataStorage.h:11,
                 from /usr/local/src/CuraEngine/src/bridge.cpp:4:
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h: In constructor ‘cura::LazyInitialization<T, Args>::LazyInitialization(Args ...)’:
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:34:18:error: expected ‘,’ before ‘...’ token
             [args...]()
                  ^
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:34:18:error: expected identifier before ‘...’ token
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:34:21:error: parameter packs not expanded with ‘...’:
             [args...]()
                     ^
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:34:21:note:         ‘args’
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h: In lambda function:
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:36:34:error: expansion pattern ‘args’ contains no argument packs
                 return new T(args...);
                                  ^
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h: In constructor ‘cura::LazyInitialization<T, Args>::LazyInitialization(const std::function<_Res(_ArgTypes ...)>&, Args ...)’:
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:52:21:error: expected ‘,’ before ‘...’ token
             [f, args...]()
                     ^
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:52:21:error: expected identifier before ‘...’ token
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:52:24:error: parameter packs not expanded with ‘...’:
             [f, args...]()
                        ^
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:52:24:note:         ‘args’
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h: In lambda function:
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:54:36:error: expansion pattern ‘args’ contains no argument packs
                 return new T(f(args...));
                                    ^
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h: In constructor ‘cura::LazyInitialization<T, Args>::LazyInitialization(const std::function<T*(Args ...)>&, Args ...)’:
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:68:21:error: expected ‘,’ before ‘...’ token
             [f, args...]()
                     ^
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:68:21:error: expected identifier before ‘...’ token
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:68:24:error: parameter packs not expanded with ‘...’:
             [f, args...]()
                        ^
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:68:24:note:         ‘args’
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h: In lambda function:
/usr/local/src/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:70:30:error: expansion pattern ‘args’ contains no argument packs
                 return f(args...);

**Comment by Ghostkeeper** [comment]
It's breaking over variadic arguments in a lambda function. The code is valid, but your compiler doesn't seem to support it.

I suggest you try with a newer version of the compiler.

**Comment by awhiemstra** [comment]
You are building on CentOS7, this means you'll need to get GCC 4.9 from the devtoolset 3 bundle: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/

**Comment by BagelOrb** [comment]
@awhiemstra perhaps you can elucidate?

Op 28 dec. 2016 09:17 schreef "GerogeFu" <notifications@github.com>:

**Comment by awhiemstra** [comment]
@BagelOrb

That looks to me like trying to compile a fairly old CuraEngine against a fairly new libArcus. It is complaining that registerMessage(int, Message*) does not match with registerMessage(Message*). The int was removed a while ago since we now auto-generate type identifiers.

**Comment by BagelOrb** [comment]
Outdated issue

**Comment by Gaspounet** [comment]
I am having a similar issue, and I have no idea how to fix it.
I'm trying to build on Ubuntu Server and I get this error:

`~/CuraEngine/build$ make
Scanning dependencies of target clipper
[  1%] Building CXX object CMakeFiles/clipper.dir/libs/clipper/clipper.cpp.o
Linking CXX static library libclipper.a
[  1%] Built target clipper
[  2%] Running C++ protocol buffer compiler on Cura.proto
Scanning dependencies of target _CuraEngine
[  4%] Building CXX object CMakeFiles/_CuraEngine.dir/src/bridge.cpp.o
[  5%] Building CXX object CMakeFiles/_CuraEngine.dir/src/commandSocket.cpp.o
In file included from /home/gaspounet/CuraEngine/src/pathPlanning/Comb.h:11:0,
                 from /home/gaspounet/CuraEngine/src/LayerPlan.h:8,
                 from /home/gaspounet/CuraEngine/src/FffGcodeWriter.h:15,
                 from /home/gaspounet/CuraEngine/src/FffProcessor.h:5,
                 from /home/gaspounet/CuraEngine/src/commandSocket.cpp:7:
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h: In constructor ‘cura::LazyInitialization<T, Args>::LazyInitialization(Args ...)’:
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:34:18: error: expected ‘,’ before ‘...’ token
             [args...]()
                  ^
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:34:18: error: expected identifier before ‘...’ token
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:34:21: error: parameter packs not expanded with ‘...’:
             [args...]()
                     ^
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:34:21: note:         ‘args’
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h: In lambda function:
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:36:34: error: expansion pattern ‘args’ contains no argument packs
                 return new T(args...);
                                  ^
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h: In constructor ‘cura::LazyInitialization<T, Args>::LazyInitialization(const std::function<_Res(_ArgTypes ...)>&, Args ...)’:
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:52:21: error: expected ‘,’ before ‘...’ token
             [f, args...]()
                     ^
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:52:21: error: expected identifier before ‘...’ token
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:52:24: error: parameter packs not expanded with ‘...’:
             [f, args...]()
                        ^
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:52:24: note:         ‘args’
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h: In lambda function:
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:54:36: error: expansion pattern ‘args’ contains no argument packs
                 return new T(f(args...));
                                    ^
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h: In constructor ‘cura::LazyInitialization<T, Args>::LazyInitialization(const std::function<T*(Args ...)>&, Args ...)’:
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:68:21: error: expected ‘,’ before ‘...’ token
             [f, args...]()
                     ^
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:68:21: error: expected identifier before ‘...’ token
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:68:24: error: parameter packs not expanded with ‘...’:
             [f, args...]()
                        ^
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:68:24: note:         ‘args’
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h: In lambda function:
/home/gaspounet/CuraEngine/src/pathPlanning/../utils/LazyInitialization.h:70:30: error: expansion pattern ‘args’ contains no argument packs
                 return f(args...);
                              ^
make[2]: *** [CMakeFiles/_CuraEngine.dir/src/commandSocket.cpp.o] Error 1
make[1]: *** [CMakeFiles/_CuraEngine.dir/all] Error 2
make: *** [all] Error 2`

**Comment by Ghostkeeper** [comment]
Still the same answer: You need to get a newer compiler version!
