### ISSUE TITLE
Missing checks when writing bed temperatur

### ISSUE THREAD

**Issue by Ocarthon** [Ultimaker/CuraEngine#428]
In [gcodePlanner.cpp](https://github.com/Ultimaker/CuraEngine/blob/50df40c6c615f83f1e410aedcd22fddac5867b0e/src/gcodePlanner.cpp#L650) and [FffGcodeWriter.cpp](https://github.com/Ultimaker/CuraEngine/blob/2.4/src/FffGcodeWriter.cpp#L299) bed temperature commands get written to the GCode without checking if a heated bed exists like it's done here in [FffGcodeWriter.cpp](https://github.com/Ultimaker/CuraEngine/blob/50df40c6c615f83f1e410aedcd22fddac5867b0e/src/FffGcodeWriter.cpp#L242)

**Comment by Ghostkeeper** [comment]
Indeed, nice find.

**Comment by BagelOrb** [comment]
fixed
