### ISSUE TITLE
scale setting question

### ISSUE THREAD

**Issue by jackyting** [Ultimaker/CuraEngine#441]
In the fdmprinter.json file ,It looks like not scale setting,
How to implement model size scaling in 2.4 version (under the command line Environment)

**Comment by BagelOrb** [comment]
There is no separate scaling option for command line slicing, you can only use the rotation matrix: https://github.com/Ultimaker/Cura/blob/master/resources/definitions/fdmprinter.def.json#L4697

Example:
```
[[2,0,0],
[0,2,0],
[0,0,2]]
```
is a matrix for uniformly scaling by a factor of 2

**Comment by jackyting** [comment]
thx
