### ISSUE TITLE
CuraEngine cannot open JSON file

### ISSUE THREAD

**Issue by aswimmingbison** [Ultimaker/CuraEngine#442]
Sorry if this is a fairly obvious answer but I am rather new to Linux and I am trying to run the CuraEngine and I cannot get CuraEngine to open the json file that I am trying to use which is just the basic demo from the command line.

Here is the command that I am running:
./CuraEngine slice -j ~/prusa_i3.def.json -o output.gcode -l ~/source.stl

This is what CuraEngine is spitting back at me:
Cura_SteamEngine version DEV
Copyright (C) 2014 David Braam

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
[ERROR] Couldn't open JSON file.
[ERROR] Failed to load json file: /home/pi/prusa_i3.def.json

I think that it might be a pathing issue but I have tried everything and I cannot figure it out.
Here is what I have the CURA_ENGINE_SEARCH_PATH set as:
CURA_ENGINE_SEACH_PATH=/home/pi/CuraEngine/build/Cura/resources/definitions

Thanks for the help!

**Comment by BagelOrb** [comment]
Try with -v to get more output.

Op 20 jan. 2017 17:39 schreef "aswimmingbison" <notifications@github.com>:
