### ISSUE TITLE
support setting question

### ISSUE THREAD

**Issue by jackyting** [Ultimaker/CuraEngine#458]
In the setting options，my settings as follow " -s support_enable=true  -s support_type=Everywhere -s support_pattern=lines  -s support_angle=60  -s support_xy_distance=0.7 -s support_z_distance=0.15 ",but printed models not support when printer printing.So how to set up to support effective
 (under the command line Environment  in 2.4 version)

**Comment by BagelOrb** [comment]
`Everywhere` should be lower case
See https://github.com/Ultimaker/Cura/blob/master/resources/definitions/fdmprinter.def.json#L974

The second part is only the user visible string.

**Comment by jackyting** [comment]
oh,thx!
