### ISSUE TITLE
about infill question

### ISSUE THREAD

**Issue by jackyting** [Ultimaker/CuraEngine#462]
In the configuration file, I find the "infill_sparse_density" is a set of filling density, but I set the "-s infill_sparse_density=0" in the code, but the internal model of the printed not hollow, so please, change the fill set apart from something other than the parameter settings?Or how do you want to change the fill density?thanks

**Comment by awhiemstra** [comment]
infill_sparse_density is a setting used to provide a more user-friendly version of the setting used by the engine, which is infill_line_distance . Setting infill_line_distance to 0 instead should make the object hollow.

**Comment by jackyting** [comment]
thank you !
