### ISSUE TITLE
OMP gcode writing badness

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/CuraEngine#478]
Hi Tim, I commented on your closed PR and I don't know if you saw that so I am creating a new issue.

I'm seeing some bad gcode appearing after the OMP gcode writing branch was merged

Gcode before omp merge...

![screenshot_2017-03-13_11-59-48](https://cloud.githubusercontent.com/assets/585618/23853519/e3b35ed0-07e4-11e7-8fb2-a57110d975fd.png)

Gcode after omp merge

![screenshot_2017-03-13_11-50-00](https://cloud.githubusercontent.com/assets/585618/23853489/d353e618-07e4-11e7-8f06-3aa9ba5daed3.png)

It looks like some extrusion moves start or end at the wrong z?

**Comment by BagelOrb** [comment]
That doesn't look too good!

Could you attach your curaproject.3mf and your gcode, please?

Op 13 mrt. 2017 15:17 schreef "Mark Burton" <notifications@github.com>:

**Comment by smartavionics** [comment]
I can get the problem showing up simply by turning off combing. Let me know if you need the model but it seems not to be model specific.

Here's another example...

![screenshot_2017-03-13_18-48-33](https://cloud.githubusercontent.com/assets/585618/23870235/b3c60284-081d-11e7-9ff0-357b4438e3ad.png)

**Comment by smartavionics** [comment]
I don't know if it's the same problem but with combing enabled I still see some weirdness that isn't there when not using the omp code.

In this example, look at the two perimeter lines of the large circular hole and the inset0 line of the smaller hole inside, they are all kinked at one end.

![screenshot_2017-03-14_07-26-04](https://cloud.githubusercontent.com/assets/585618/23890002/a2b5f16a-0887-11e7-8bb0-443bb245cd95.png)

**Comment by BagelOrb** [comment]
The reason I am asking for the gcode is that I can then verify whether this is an actual gcode problem or a problem of your gcode viewer.

I cannot reproduce the problems when looking in RepetierHost.

Please attach your .curaproject.3mf and your gcode.

Please also try to find the problem in the gcode itself, so that you can verify the problem is actually present in the gcode.

**Comment by BagelOrb** [comment]
Ah I can reproduce the problem now.
The problem occurs when you have retraction hop enabled.

This is why it's good to attach your project file: it includes all your settings.

**Comment by smartavionics** [comment]
I can't save the project. It fails with an empty message box in the GUI and the following on stderr...

ERROR - LocalFileOutputDevice.LocalFileOutputDevicePlugin.requestWrite [93]: There are no file types available to write with!

Here's the model and the gcode. I just used the UM3 machine default profile with combing disabled.

[UM3_bracket_bigheli.gcode.txt](https://github.com/Ultimaker/CuraEngine/files/841048/UM3_bracket_bigheli.gcode.txt)
[bracket_bigheli.stl.txt](https://github.com/Ultimaker/CuraEngine/files/841053/bracket_bigheli.stl.txt)

**Comment by BagelOrb** [comment]
Ok thanks. I was testing on the UM2.... :P

**Comment by BagelOrb** [comment]
Fixed it. I should have fixed it ASAP, but ah well...

Thanks for reporting this!

**Comment by BagelOrb** [comment]
I cannot reproduce the weird kinks at the wall of the inside hole. I think is a visualization error.

**Comment by smartavionics** [comment]
The weird kinks have also gone away now.

**Comment by BagelOrb** [comment]
Ok good!

**Comment by BagelOrb** [comment]
About the project saving bug: we are not able to reproduce your problem. It's very mysterious why you get that error. Are you sure you are up to date with all 2.5 branches of all repositories involved?

If so: could you maybe attach your log file?

**Comment by BagelOrb** [comment]
Perhaps it's better to make a new issue in https://github.com/Ultimaker/Cura for that..

**Comment by smartavionics** [comment]
It was because I didn't have the libsavitar stuff installed. OK, now.

**Comment by BagelOrb** [comment]
Ah ok.
