### ISSUE TITLE
Feature request: Gradual infill for support

### ISSUE THREAD

**Issue by Dim3nsioneer** [Ultimaker/CuraEngine#492]
Some prints need large volumes of support material. As especially PVA is not the cheapest material, it would be nice if one could reduce the material consumption by introducing gradual infill also for (soluble) support.

**Comment by Ghostkeeper** [comment]
This came up in our own discussions as well as an option.

**Comment by fieldOfView** [comment]
"Gradual Support Infill Steps" has been implemented, this can be closed (right?)
