### ISSUE TITLE
run curaEngine on server with command line, But Export an empty gcode file. 

### ISSUE THREAD

**Issue by MickeyLeez** [Ultimaker/CuraEngine#496]
However, it works correctly on the local host by using "CuraEngine slice -j xxx.def.json -o xxx.gcode -l xxx.stl." in a java project. And I had double-checked the paths json file and stl file. (The server environment was windows server 2008, while the loca host was windows 7)

**Comment by BagelOrb** [comment]
If you add `-v` then you will get more output.

It might be the case that your model is below the build plate. Try `-s
center_object=True`

Op 10 apr. 2017 09:32 schreef "Amos Lee" <notifications@github.com>:

**Comment by MickeyLeez** [comment]
Thanks for your advice.
What does the '-s center_object=True' mean ? And it still can not explain why it just worked correctly on local host.
Now I am going to add "-v" and "-s center_object=True".

**Comment by Ghostkeeper** [comment]
`-s center_object=True` will cause the model to be centred on the build plate. If it's below the build plate, that would move it to be on top.

**Comment by BagelOrb** [comment]
Not enough info. Issue is outdated.
