### ISSUE TITLE
Question: automatic arrangement of STL models?

### ISSUE THREAD

**Issue by Murloc992** [Ultimaker/CuraEngine#516]
Hello,

is it possible to pass some kind of a parameter to position models across the build plate? For example I would like to print several(more like 20) copies of the same model, but just feeding 20 STL entries to it it generates a single slice. I tried feeding several different STLs and I see that CuraEngine handles several STLs being passed, it just doesn't arrange them.

Hope somebody can help me. :)

**Comment by BagelOrb** [comment]
If you want to arrange models you should try using the frontend!
Cura 2.5 can be downloaded at https://software.ultimaker.com

Otherwise you could pass settins like so: -s mesh_position_x=100 -s mesh_position_z=-5
