### ISSUE TITLE
Retraction not generated

### ISSUE THREAD

**Issue by stokmanis** [Ultimaker/CuraEngine#523]
With retraction settings enabled, Cura 2.5.0 does not generate the retracting.
Here are the settings
![cura_settings](https://cloud.githubusercontent.com/assets/4971219/26343360/68f532e8-3fa4-11e7-86e5-d2892285b516.jpg)
Here is the STL test file, which have 10mm travel moves
[test_missing_retraction.zip](https://github.com/Ultimaker/CuraEngine/files/1021314/test_missing_retraction.zip)
![retraction_missing](https://cloud.githubusercontent.com/assets/4971219/26343605/52814d70-3fa5-11e7-97f2-15a78f66a247.jpg)

Here is the except from g code, which shows that extruder does not retract
G1 X90.6 Y90.6 **E3.75174**
G0 F3600 X90.67 Y90.67
G0 X96.83 Y96.83
G0 X96.9 Y96.9
G1 F1800 X96.9 Y103.1 **E4.06106**

Maybe I am missing some setting :)

**Comment by smartavionics** [comment]
Is combing enabled for skins? That could zap the retract.

**Comment by stokmanis** [comment]
Yes, I had Combing Mode set to All (default). When I set it to "No Skin", the retraction was in place. Thanks a lot, issue solved.
The "combing" in the first layer does not make sense, as the bottom surface will be messy due to the extra travel garbage laying below the normal layer.
