### ISSUE TITLE
Linux 64 bits issue

### ISSUE THREAD

**Issue by mariolpantunes** [Ultimaker/CuraEngine#562]
Hi, in order to compile Cura (and all the libs) I had to patch up the CMakeLists.txt to correctly use Lib_Suffix.
I share my lib64.patch, if you found it acceptable can you add it to the code?
[lib64.txt](https://github.com/Ultimaker/CuraEngine/files/1156562/lib64.txt)

**Comment by Ghostkeeper** [comment]
I've applied this patch with some slight alteration to make sure that the variable exists, which isn't guaranteed by CMake. It still works for me. I hope this fixes it for your system as well!
