### ISSUE TITLE
Unable to run CuraEngine.

### ISSUE THREAD

**Issue by abinashk-inf** [Ultimaker/CuraEngine#598]
I compiled CuraEngine from source but was unable to run through command line. I followed instructions in
 wiki (./build/CuraEngine slice -v -j ../Cura/resources/definitions/dual_extrusion_printer.def.json -o "output/test.gcode" -e1 -s infill_line_distance=0 -e0 -l "/model_1.stl" -e1 -l "fully_filled_model.stl" ) but it failed with following error:
Loading ../Cura/resources/definitions/dual_extrusion_printer.def.json...
[ERROR] Couldn't open JSON file.
[ERROR] Failed to load json file: ../Cura/resources/definitions/dual_extrusion_printer.def.json

How can I run CuraEngine through command line? 
System Specs: Ubuntu 16.04,  32-bit

**Comment by abinashk-inf** [comment]
Hi, I was able to run the CuraEngine executable. The json file mentioned in wiki does not exist hence was causing error.

**Comment by Ghostkeeper** [comment]
> The json file mentioned in wiki does not exist

I'd like to fix it, but there doesn't seem to be a wiki...

**Comment by ArthurKretzer** [comment]
> > The json file mentioned in wiki does not exist
> 
> I'd like to fix it, but there doesn't seem to be a wiki...

It is [here](https://github.com/Ultimaker/CuraEngine) in "Running" topic.
