### ISSUE TITLE
line 192 in mesh.cpp

### ISSUE THREAD

**Issue by jason26a** [Ultimaker/CuraEngine#601]
for (int candidateFace : candidateFaces)
    {
        int candidateVertex;
        {// find third vertex belonging to the face (besides idx0 and idx1)
            for (candidateVertex = 0; candidateVertex<3; candidateVertex++)
                if (faces[candidateFace].vertex_index[candidateVertex] != idx0 && faces[candidateFace].vertex_index[candidateVertex] != idx1)
                    break;
        }

        FPoint3 v1 = vertices[candidateVertex].p -vertices[idx0].p;   // error? 
        FPoint3 n1 = v1.cross(v0);

the candidateVertex is used for find the index vertex of faces[condidateFace], only 0 to 2, the value sholudn't be used in vertices.

I think it should be corrected by likely below: 

int idx_candidate = faces[candidateFace].vertex_index[candidateVertex];
FPoint3 v1 = vertices[idx_candidate].p - vertices[idx0].p;

**Comment by Ghostkeeper** [comment]
Indeed, that seems to be wrong there.

This could've led to some faulty connections if the model file had disconnected faces.
