### ISSUE TITLE
Improving raft?

### ISSUE THREAD

**Issue by Gregwar** [Ultimaker/CuraEngine#61]
Hello,
I guess you've already seen a Makerware raft, it adds a filled layer of plastic before printing the part:
http://www.mak3r.com/wp-content/uploads/2013/06/makerware2.jpg

Do you think this would be doable in CuraEngine?

**Comment by BagelOrb** [comment]
All requests in this thread have been fulfilled.

The main question now is what the default value for the air gap should be. I'm testing 0.4mm atm.
