### ISSUE TITLE
Cura 2.7 3.0.0 beta Error

### ISSUE THREAD

**Issue by qwerty8224** [Ultimaker/CuraEngine#627]
Try to cut this model?
https://www.thingiverse.com/thing:42198/#files
**Differential_Housing_Lower.stl** 

https://ru.files.fm/u/7hetthy3#_

**Comment by smartavionics** [comment]
Turning off the "Ignore Small Z Gaps" stops that weirdness in the skins happening. But it's a weird model anyway, are they using that bottom part for support to print the top part?

**Comment by qwerty8224** [comment]
Yes. 
The problem is solved «Ignore Small Z Gaps» thanks.
