### ISSUE TITLE
Possibly incorrect comment for getExtrudersUsed()

### ISSUE THREAD

**Issue by d235j** [Ultimaker/CuraEngine#638]
At https://github.com/Ultimaker/CuraEngine/blob/c60f21b0d9accb7899b2b32c00bbe26783543c9e/src/sliceDataStorage.h#L337 it appears that the documentation was copied from `SliceDataStorage.getExtrudersUsed(int layer_nr)` as "in this layer" is specified but without a layer context. Does `SliceDataStorage. getExtrudersUsed()` apply to the entire storage? A cursory look at the implementation indicates that it should.

**Comment by Ghostkeeper** [comment]
Yeah, looks like you're right. I've updated the documentation. Thanks.
