### ISSUE TITLE
Layer pointer not show

### ISSUE THREAD

**Issue by mikko70** [Ultimaker/CuraEngine#646]
When open first time View-> "Layer View" ,layer scroll pointer not show.
When go back "Solid View" and again back "Layer View" , pointer appear.
Version 3.03 it happen and  has been long.

**Comment by smartavionics** [comment]
Hi, I think you need to open an issue in the cura repo, as this is the backend slicer repo. The backend does not contain any UI stuff so please close this issue and open a new one at https://github.com/Ultimaker/Cura

**Comment by ChrisTerBeke** [comment]
3.1 will have refactored layer view UI code which also fixes this issue.
