### ISSUE TITLE
I get error when I enable the support.

### ISSUE THREAD

**Issue by mikandaisuki** [Ultimaker/CuraEngine#648]
I'm using CuraEngine3.03 via the command line.
I get the below error when I'm enabling the support:
[ERROR] Trying to retrieve unregistered setting with no value given: 'support_skip_some_zags'
Config file is Cura3.03/resources/definitions/fdmprinter.def.json.

Otherwise, in using CuraEngine2.7 with Cura3.03 config, i get another error:
[ERROR] Trying to retrieve unregistered setting with no value given: 'expand_skins_expand_distance'

**Comment by Ghostkeeper** [comment]
This error message means that you're using a definitions file that is too old. The `support_skip_some_zags` setting was present in 3.0 though: https://github.com/Ultimaker/Cura/blob/d3f583b7a43b4509a0c0d6ef8a83112d96b23a5b/resources/definitions/fdmprinter.def.json#L5013

Could you try to find the `support_skip_some_zags` setting in the definition file you're using?
