### ISSUE TITLE
./autogen.sh: 50: ./autogen.sh: autoreconf: not found

### ISSUE THREAD

**Issue by Totoleheros** [Ultimaker/CuraEngine#667]
When I try to run the ./autogen.sh, I get these lines of error messages:

+ autoreconf -f -i -Wall,no-obsolete
./autogen.sh: 50: ./autogen.sh: autoreconf: not found

Can I get some help please?

Best regards

AN

**Comment by Totoleheros** [comment]
I forgot that I am trying to install it on a Raspberry Pi3 (Jessie).

**Comment by LipuFei** [comment]
Hi @Totoleheros , CuraEngine doesn't use `autoconf` and `automake`, it uses `CMake` to build. Could you try with CMake?

**Comment by Ghostkeeper** [comment]
I wonder where that `autogen.sh` came from then on Totoleheros' computer...
