### ISSUE TITLE
Feature request: Ironing on every or/and N layers

### ISSUE THREAD

**Issue by megablue** [Ultimaker/CuraEngine#674]
I would like to request Ironing not being exclusive to top-most layer but ob every layer or selected interval.

The idea being, ironing fills the microvoids between lines, ironing on every layer will make the parts super strong since the microvoids between extrusion lines are basically eliminated and bond together better.

**Comment by ChrisTerBeke** [comment]
Hi, thanks for your feature request, sounds useful. Could you maybe open an issue on the main Cura repository, it's way more active with contributors and get's more attention in general. On this repo we mainly use issues for bug reports for the CuraEngine specifically.

**Comment by megablue** [comment]
alright, thanks.

**Comment by Ghostkeeper** [comment]
This is a feature request for CuraEngine specifically, right?

**Comment by Ghostkeeper** [comment]
Have you tried setting the "Top Surface Skin Line Width" setting smaller? I'd think that would have a similar effect to what you want.

**Comment by ChrisTerBeke** [comment]
It requires implementation in the engine indeed, but also UI settings, so the broader feature is more for Cura as a whole, which I think we should keep track of in the main repo.

**Comment by Ghostkeeper** [comment]
Nearly all new features of the engine require a setting in the UI, because we can't normally change the default behaviour of the engine without having a test sequence go over the result.

**Comment by ChrisTerBeke** [comment]
That's true. Just trying to keep everything together as many people only look at the issues in the main Cura repo, not following all repositories we have. Personally I'd even go as far as removing the ability to file issues here and redirect all to the main repo, but that's just an opinion :)

**Comment by BagelOrb** [comment]
The idea does indeed change the structural properties of the print, but at the cost of a lot of print time.

I don't think Ultimaker has any time soon to implement this issue. Other issues are more pressing.

Closing this to clean up the amount of open issues.
