### ISSUE TITLE
continuous toolpathing of shells

### ISSUE THREAD

**Issue by jaibooot** [Ultimaker/CuraEngine#683]
Right now, The outer shells of features are discrete. The extruder typically retracts and unretracts when moving between shells. I would propose that it would be nice to have a continuous toolpathing of shells. Picture of what I mean is attached 

![continuous shell toolpathing 1](https://user-images.githubusercontent.com/25693411/34788483-b4a50f36-f608-11e7-96a6-eff0f16ca532.jpg)

This way, total amount of retracts and unretracts will be reduced, hopefully increasing print quality. The outermost shell could end in an unretract, or travel across previously printed shells and begin printing the infill (dotted line)

**Comment by smartavionics** [comment]
Have you tried using the wall print order optimization option that is available in recent Curas? Using that it will print the shells you show above left without any retracts. So if you have a part with multiple holes, it will print all the walls for each hole before moving on to the next hole.

**Comment by jaibooot** [comment]
Thanks for the suggestion! That seems to help quite a bit. How about the end of the outermost wall? Is it possible to travel into the infill instead of retracting on the outer most wall and leaving a blob?

**Comment by smartavionics** [comment]
Actually, the optimization I mention above does do that, it moves the nozzle away from the outer wall. It doesn't go very far, just about a nozzle width. You can see the movement if you zoom into the layer view. In this example, it travels from the outer wall of the hole (red) to the inner wall of the part's perimeter (green), prints the inner wall, then moves to the outer wall (red) then moves inboard again so it's approximately over the inner wall and then scoots off to do the infill.

![screenshot_2018-01-15_17-17-04](https://user-images.githubusercontent.com/585618/34954388-25a3f66c-fa18-11e7-9486-d55bdb8c9aa8.png)

**Comment by jaibooot** [comment]
Just did some testing of this, and it definitely seems to work nicely! Thanks!

**Comment by smartavionics** [comment]
Great, if you're happy, please close this issue. Cheers!
