### ISSUE TITLE
Plans to clone makerbot "minfill"?

### ISSUE THREAD

**Issue by flowchartsman** [Ultimaker/CuraEngine#689]
Was wondering if there were any plans to research the [new "minfill" feature](https://www.makerbot.com/media-center/2017/03/20/introducing-makerbot-minfill) that Makerbot Print has. In short, it supposedly uses only the amount of infill required for any overhang, nothing more. Are there any plans to look into such a sparse infill, or are the existing patterns such as concentric considered good enough?

**Comment by ChrisTerBeke** [comment]
Cura already has gradual infill, which is not the same algorithm but fairly similar. At least it tries to solve the same problem (having too much infill where not needed).

**Comment by Ghostkeeper** [comment]
If you only need the infill to get good overhang, I suggest turning on "Hollow Out Objects" and then turn on support as well, possibly even tree support. With tree support you'll get results that are very similar to Minfill.

**Comment by BagelOrb** [comment]
We're not going to **copy** Makerbot.

Hollow Out Objects along with support does something which comes close.

My new Infill Support setting along with gradual infill does something close: https://github.com/Ultimaker/CuraEngine/pull/711
