### ISSUE TITLE
Unwanted Travel to X0 Y0 when switching the nozzle

### ISSUE THREAD

**Issue by rahuldevikar761** [Ultimaker/CuraEngine#690]
In Cura 2.7 - 3.1, why we have unwanted X0 Y0  travel movement when switching nozzle in the middle of the print.  Please see the attached image. Is there a way to stop this movement, I am using a custom FDM Printer?

G1 X196.335 Y127.826 E16.25601
G1 X196.319 Y127.816 E16.25613
G1 X196.19 Y127.748 E16.25704
G1 X195.885 Y127.635 E16.25908
G1 X195.811 Y127.638 E16.25955
G1 F1500 E9.75955
G0 F7200 X195.645 Y127.456
G0 X0.00 Y0.00
;TIME_ELAPSED:12071.318789
;LAYER:370
**G0 X0.00 Y0.00 Z38.16**
G1 F1200 E0.25955
G92 E0

T0
G92 E0

M109 S220
M104 T1 S175
G1 F1200 E9.5
**G0 F7200 X0.00 Y0.00 Z38.16**
G0 X173.649 Y129.036
G0 X174.733 Y129.722
G0 X174.951 Y129.696
M104 S230
;TYPE:FILL
G1 F1500 E16
G1 F3600 X176.764 Y131.509 E16.01608
G1 X176.834 Y131.579
G0 F7200 X175.957 Y129.512

Thanks

![unwanted travel](https://user-images.githubusercontent.com/19936206/35408069-a90d74d6-01c2-11e8-92b8-b64e99c165e8.JPG)

**Comment by Ghostkeeper** [comment]
See also https://github.com/Ultimaker/Cura/issues/2433.
