### ISSUE TITLE
CuraEngine misreports version, always displays DEV

### ISSUE THREAD

**Issue by onitake** [Ultimaker/CuraEngine#691]
Since 3.1, CuraEngine always identifies itself as `Cura_SteamEngine version DEV` instead of displaying its proper version.

This occurs because the copyright message is constructed in main.cpp, which is not compiled with the proper `VERSION` macro.

A fix is trivial: Add a `set_target_properties` statement to the `CuraEngine` target in CMakeLists.txt, similar to the one for `_CuraEngine`.

**Comment by Ghostkeeper** [comment]
This reproduces and your PR fixed it. Thanks!
