### ISSUE TITLE
the amount of displayed layers is wrong 

### ISSUE THREAD

**Issue by UltiCa** [Ultimaker/CuraEngine#717]
think, I have located a bug in Cura 3.2.1

as you can see in the Pictures, the model has only two layers. The original size is 0.5 mm height. First layer 0.3mm and the next 0.2mm =0.5 mm. In the layerview, there are 3 layers displayed as you can see. 
![bildschirmfoto 2018-03-02 um 16 26 53](https://user-images.githubusercontent.com/37214146/37207601-fed8f37a-239d-11e8-8620-670c25e7b2b0.png)
![bildschirmfoto 2018-03-02 um 16 26 36](https://user-images.githubusercontent.com/37214146/37207615-0dcebaa4-239e-11e8-8c8b-e0b073552709.png)
![bildschirmfoto 2018-03-02 um 16 26 09](https://user-images.githubusercontent.com/37214146/37207619-1427eb1e-239e-11e8-880d-287ad0c081d9.png)
what is going on here?
- Carsten -

**Comment by diegopradogesto** [comment]
Yes, this is a known issue.
However if you see the horizontal slider, the last layer is empty, so actually there are just two layers. The third layer is because at the end we receive a movement in Z and it counts as a new layer in layer view, but nothing is printed.

**Comment by Ghostkeeper** [comment]
This is fixed in version 3.3.
