### ISSUE TITLE
[3.2.1_masterbranch] Griffin gcode Export issues.

### ISSUE THREAD

**Issue by recarens** [Ultimaker/CuraEngine#726]
- No time exported
- With Cura interface the support_z_distance 0.2 is diferent than curaEngine. I had to input 0.6 to get similar result. With 0.2 in CuraEngine is like 0 and is imposible to remove the support.

I'm using Ultimaker 3 Extended with modified ultimaker3_extended.def.json in curaEngine.

Example of Header from Gcode Exported

;START_OF_HEADER
;HEADER_VERSION:0.1
;FLAVOR:Griffin
;GENERATOR.NAME:Cura_SteamEngine
;GENERATOR.VERSION:master
;GENERATOR.BUILD_DATE:2018-03-14
;TARGET_MACHINE.NAME:Ultimaker 3 Extended
;EXTRUDER_TRAIN.0.INITIAL_TEMPERATURE:240
;EXTRUDER_TRAIN.0.MATERIAL.GUID:60636bb4-518f-42e7-8237-fe77b194ebe0
;EXTRUDER_TRAIN.0.NOZZLE.DIAMETER:0.8
;EXTRUDER_TRAIN.0.NOZZLE.NAME:AA 0.8
;BUILD_PLATE.TYPE:glass
;BUILD_PLATE.INITIAL_TEMPERATURE:85
;PRINT.SIZE.MIN.X:0
;PRINT.SIZE.MIN.Y:0
;PRINT.SIZE.MIN.Z:0
;PRINT.SIZE.MAX.X:0.01
;PRINT.SIZE.MAX.Y:0.01
;PRINT.SIZE.MAX.Z:0.01
;END_OF_HEADER

**Comment by Ghostkeeper** [comment]
Hmm, print time should be in there like so:

    ;PRINT.TIME:456
