### ISSUE TITLE
Good afternoon. I'm just starting to explore the 3d world and want to ask a couple of questions about the Cura Engine. Is it possible to get the model data (the file) when you load the model (for example, the weight of the model, the manufacturing model).

### ISSUE THREAD

**Issue by Creativ671** [Ultimaker/CuraEngine#729]
Platform
Windows 10
Good afternoon. I'm just starting to explore the 3d world and want to ask a couple of questions about the Cura Engine. Is it possible to get the model data (the file) when you load the model (for example, the weight of the model, the manufacturing model).

**Comment by ianpaschal** [comment]
Answered on the Cura repository.

**Comment by Ghostkeeper** [comment]
See this issue here: https://github.com/Ultimaker/Cura/issues/3556
