### ISSUE TITLE
Layer Height Parameter Not Changing Number of Layers

### ISSUE THREAD

**Issue by kennethshawfriedman** [Ultimaker/CuraEngine#733]
I am feeding CuraEngine an STL file with the Ultimaker3 json config file, and then sending it the `-s layer_height='0.2'` parameter.

Regardless of what layer_height I give it, it produces GCode with the number of layers as if layer_height=0.1. Are there other settings I also have to change? Other parameters and settings seem to be working just fine.

**Comment by BagelOrb** [comment]
You are probably supplying the setting at the wrong point in the command line call. Try setting that setting at the very start.

Reread the help and try to figure out how the order determines the slicing.

**Comment by BagelOrb** [comment]
As in `CuraEngine help`

**Comment by Ghostkeeper** [comment]
In particular, ensure that the `-s layer_height=0.2` occurs before any -E parameters, otherwise the layer height would only get set for one of the extruders and that isn't supported.
