### ISSUE TITLE
[3.3] When using interface in small z height support areas,  infill prints before skin

### ISSUE THREAD

**Issue by jaibooot** [Ultimaker/CuraEngine#742]
**Application Version** - cura 3.3 beta, although I believe this has been a bug for a while

**Steps to Reproduce**
Upload stl file with a gap that will build a support structure that is <~2mm in z. Enable support interface extruder with E1 

**Actual Results**
The part does not print top/ bottom layers on top of the support structure. Instead, it prints multiple layers of infill before printing the top / bottom layers. 

![small gap](https://user-images.githubusercontent.com/25693411/38507524-c2ec26b0-3bea-11e8-8879-7f90d4cad226.PNG)
**infill printing above support structure**
![small gap 2](https://user-images.githubusercontent.com/25693411/38507529-c5928864-3bea-11e8-8866-330585e3a9e4.PNG)
**top/ bottom layers that print a few layers above the support structures**

[UM3_curatest.gcode.gz](https://github.com/Ultimaker/CuraEngine/files/1890587/UM3_curatest.gcode.gz)
[UM3_curatest.gcode.gz](https://github.com/Ultimaker/CuraEngine/files/1890588/UM3_curatest.gcode.gz)

[cura 3.3 support gap test.zip](https://github.com/Ultimaker/CuraEngine/files/1890590/cura.3.3.support.gap.test.zip)

**Comment by BagelOrb** [comment]
Disabled the setting Ignore Small Z Gaps.

**Comment by BagelOrb** [comment]
I mean: please disable ...

**Comment by jaibooot** [comment]
understood, thank you!
