### ISSUE TITLE
Concentric method leaves gap in top/bottom layer

### ISSUE THREAD

**Issue by midgethoen** [Ultimaker/CuraEngine#743]
**Application Version**
3.2.1

**Platform**
OSX

**Steps to Reproduce**
Slice stl.. 🥁tss 

**Actual Results**
Cura sometimes leaves a gap in the top/bottom layer with the concentric method.
<img width="876" alt="schermafbeelding 2018-04-14 om 13 40 33" src="https://user-images.githubusercontent.com/4599476/38767850-a73c71c4-3fe9-11e8-8565-ea47d82ce4a0.png">
<img width="824" alt="schermafbeelding 2018-04-14 om 13 41 05" src="https://user-images.githubusercontent.com/4599476/38767851-a755ddb2-3fe9-11e8-8f7d-e7bd1b624637.png">
![img_0332](https://user-images.githubusercontent.com/4599476/38767887-91bed340-3fea-11e8-94ac-6a4c6adcacfd.JPG)

**Expected results**
This gap should have been closed

**Additional Information**

sample stl and cura profile:
[Archief.zip](https://github.com/Ultimaker/CuraEngine/files/1910322/Archief.zip)

**Comment by BagelOrb** [comment]
Do you have the setting Fill Small Gaps enabled?

**Comment by midgethoen** [comment]
I did not even know it existed. I will try slicing again tonight and see if that helps.

thanks for the tip

**Comment by midgethoen** [comment]
> Do you have the setting Fill Small Gaps enabled?

I could not find this setting. is this its exact name?

**Comment by BagelOrb** [comment]
Probably not. Just put "gaps" in the setting search bar. I don't have a
computer ATM.

**Comment by BagelOrb** [comment]
It's about the setting above that, but that one is already set to everywhere, so there's a bug.

**Comment by genghisnico13** [comment]
Just in case, here is the first layer of a Benchy, cura V3.2.1 in Linux.
![benchyfirstlayerwidth0 2mmconcentriclinuxcura3 2 1](https://user-images.githubusercontent.com/19802560/39102726-c206080a-467c-11e8-80a7-fc12c564ad5b.png)
I tried changing the 3 mentioned gaps options with no difference in this layer. The printed part has those gaps as expected.
Fill gap between walls should do something similar to the thin segment between the 3 and the D but everywhere?

**Comment by diegopradogesto** [comment]
I think those spaces are there because there is no space enough for another infill line. We don't have a feature to fill tiny gaps in infill, as far as I know. We have it just for the tiny space between walls.

**Comment by BagelOrb** [comment]
`FffGcodeWriter::processSkinPart` calls `processPerimeterGaps`, so this is a bug which is either recently introduced or nobody ever noticed it was introduced.

**Comment by BagelOrb** [comment]
@diegopradogesto This issue is not about infill, but about skin!

**Comment by diegopradogesto** [comment]
Yep, sorry, skin was in my head but I wrote infill.
Devs. CURA-5276

**Comment by AbeFM** [comment]
I'd mentioned this on the forums (but can't find post) - from a user's perspective what I use is "lines" for top/bottom layers, then "top surface skin layers" and "bottom initial pattern" both sent to concentric.

This gives you a nice concentric finish without holes, since the lines one layer beneath doesn't show.

**Comment by Vandrasc** [comment]
Fixed in CURA-5276.

**Comment by midgethoen** [comment]
Awesome. Thnx
