### ISSUE TITLE
Gcode corrupted 

### ISSUE THREAD

**Issue by mogey336** [Ultimaker/CuraEngine#744]
I have a problem with Cura 15.04.6 and Cura 3.2.1
When slicing stl file , the gcode adds delay and the nozzle move outside the model then wait for 1 or 2 seconds then back to the model then continue printing.
The model is correct i tried printing old models i printed before same thing happens!!
I download Cura on my desktop same result also
![cura](https://user-images.githubusercontent.com/17283422/38769637-7d9d995c-4006-11e8-8ec2-5bf6d513b3ef.JPG)

**Comment by diegopradogesto** [comment]
Can you provide more data? Type of printer, settings, model, the gcode itself, ... If you work with Cura you can also provide the project file.

**Comment by mogey336** [comment]
After searching it, i realize i was enabling cool head lift 
That was the proplem
