### ISSUE TITLE
Please can we have new Releases for Gentoo packaging

### ISSUE THREAD

**Issue by mjeveritt** [Ultimaker/CuraEngine#756]
**Application Version**

**Platform**
Gentoo Linux

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

I have requested via IRC that we'd like full releases rather than simply tags for packaging Cura and its dependencies properly in Gentoo Linux. As they are quite inter-dependent, it would be good to make sure these tie up correctly to enable our users to make best use of the latest editions of the package. Thanks!

**Comment by ChrisTerBeke** [comment]
Less than 0.5% of Cura users are on Linux, and only a very small subset of that is on Gentoo I imagine. I'm pretty use that Ultimaker will not work on this, maybe someone in the community will pick it up.

**Comment by rickyzhang82** [comment]
@mjeveritt 
It is built in AppImage. Why do you need a specific Linux distribution?

**Comment by mjeveritt** [comment]
I'll fork it then, automate pulls & releases based on tags. Tedious, but meh.
