### ISSUE TITLE
OBJ file questions

### ISSUE THREAD

**Issue by jackyting825** [Ultimaker/CuraEngine#763]
HI,Using Cura can slicing OBJ type files. Does CuraEngine support the slicing of OBJ type files? When I set the -l parameter to OBJ file path in the way of STL slice at the command line, I directly report error. The error content is "[ERROR] Failed to load model: /home/bz/Desktop/test.obj".So does CuraEngine support slicing of Obj files? If not, what should I do?
Looking forward to your reply.
thx!

**Comment by jackyting825** [comment]
Thank you for your reply @alekseisasin , I went to see and learn the relevant source code

**Comment by Li-rr** [comment]
> 
> 
> Hi @jackyting825 So far as I know Cura sends always .stl format file to CuraEngine. Cura reads .obj files and translate it to .stl type. You can check method loadMeshIntoMeshGroup(...) which checks the file type.

Hi, Do you know how to slicing OBJ type files now?

**Comment by Li-rr** [comment]
> 
> 
> Thank you for your reply @alekseisasin , I went to see and learn the relevant source code

Hi, Do you know how to slicing OBJ type files now?

**Comment by Ghostkeeper** [comment]
CuraEngine still doesn't accept OBJ files via the command line, no. The command line interface of CuraEngine is intended as a debugging tool, so implementing various file formats is for us not a priority or even really a desire.

Cura's front-end accepts OBJ files and will cause CuraEngine to slice them through its socket interface.

**Comment by eskeyaar** [comment]
> CuraEngine still doesn't accept OBJ files via the command line, no. The command line interface of CuraEngine is intended as a debugging tool, so implementing various file formats is for us not a priority or even really a desire.
> 
> Cura's front-end accepts OBJ files and will cause CuraEngine to slice them through its socket interface.

@Ghostkeeper, so there is no other way to slice obj, ( x3d, collada etc.) through CLI? We have to translate them into stl and then slice it?

**Comment by Ghostkeeper** [comment]
Indeed. The command-line interface only accepts binary STL and ASCII STL. The other file formats that you know and love are implemented in Cura's Python front-end as plug-ins, which translate them into Numpy arrays, and those arrays get transferred via Protobuf to CuraEngine. CuraEngine has no knowledge of those file formats.

The STL file format is being maintained here only for debugging purposes.

**Comment by eskeyaar** [comment]
> 
> 
> Indeed. The command-line interface only accepts binary STL and ASCII STL. The other file formats that you know and love are implemented in Cura's front-end as Python plug-ins, which translate them into Numpy arrays, and those arrays get transferred via Protobuf to CuraEngine. CuraEngine has no knowledge of those file formats. It normally just accepts lists of vertices and triangles through a local socket.
> 
> The STL file format is being maintained here only for debugging purposes.

Make sense. Thanks for the input.

**Comment by eskeyaar** [comment]
@Ghostkeeper So if i want to use dual printing with STL, does CLI has the options to do?
