### ISSUE TITLE
[wiki] The term insect in Cura Engine

### ISSUE THREAD

**Issue by rickyzhang82** [Ultimaker/CuraEngine#785]
@Ghostkeeper Insect is a term I got troubled to understand when I read 15.04 Cura engine. It took me a while to figure it out what it means. Why do you remove it from the glossary? 

This is nitty gritty. But it is important to save us time for discussion in future.

PS: I deleted the template due to the fact that none of them apply my issue here.

**Comment by Ghostkeeper** [comment]
Insect is not a term in CuraEngine. It's a type of creature: https://en.wikipedia.org/wiki/Insect

Later I was thinking. Did you mean "inset"? Because that is sort of a term, but it's not equivalent to "wall".

**Comment by rickyzhang82** [comment]
My bad. But your wiki link just cracked me up....

What is difference between wall and inset? I might misunderstand the term `inset` when reading the source. I do want to know what I missed. TIA.

**Comment by ChrisTerBeke** [comment]
wall is the same as inset. inset is just the technical term in the toolpath generation scope.

**Comment by rickyzhang82** [comment]
OK. @Ghostkeeper If there is no objection, I will just add 
 - Inset. a.k.a wall.

**Comment by ianpaschal** [comment]
I would avoid adding these sorts of "aka" or "see" definitions as they're not really definitions. If we're not sure why the term inset is used, don't fill it in. I'm sure there is a reason the term "inset" was chosen and that's what should be listed there.

**Comment by rickyzhang82** [comment]
We do know how inset is used. But @Ghostkeeper doesn't agree with my original proposal that inset = wall. I need his input.

aka and see also is common thing in dictionary. I don't know what other alternative to group all of them together. It is like some say to-mar-to but some say to-make-to. I'm open to your suggestion. But we should not exclude them.

**Comment by ChrisTerBeke** [comment]
To be more precise, we use insets to generate wall lines. It's a shrunken version of the outer perimeter of an island. Source: http://alienryderflex.com/polygon_inset/.

**Comment by rickyzhang82** [comment]
If I may, I'd define the following way for inset:

Inset is a set of closed polygons generated by slicing engine for the outer perimeter and the inner perimeter (if any) of the island.

**Comment by ianpaschal** [comment]
Yes definitely better. As I said, I would avoid "see" or "aka" definitions as it replaces one question "What is an inset?" with a new question "Why not just use the other term then?" Net effect is still having questions.

Pretty much any definition explaining it in more detail, and ideally also how it's related to but different from other, similar terms, is fine by me.

Go for it.

**Comment by DDDirk** [comment]
Are there two types of inset then? 
The first is for the outer wall, which is inset half a road width from the outside of the model. This is what I thought inset meant.
The next walls in are inset a full roadwith (if there is no overlap). This is what I understand that you mean.

**Comment by Ghostkeeper** [comment]
No. Insets are used for many things. Outer walls and inner walls are just two of them. In our current code base there are 165 calls to the function that performs polygon insets! An inset is **not** a wall.
