### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by SwastikSingh0301** [Ultimaker/CuraEngine#786]
version: 2.7.0

**Platform: ubuntu**

cmake ..
-- Building with Arcus
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "FindArcus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Arcus", but
  CMake did not find one.

  Could not find a package configuration file provided by "Arcus" with any of
  the following names:

    ArcusConfig.cmake
    arcus-config.cmake

  Add the installation prefix of "Arcus" to CMAKE_PREFIX_PATH or set
  "Arcus_DIR" to a directory containing one of the above files.  If "Arcus"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/CuraEngine-2.7.0/build/CMakeFiles/CMakeOutput.log".

libArcus and its dependencies are installed properly.

**Comment by Ghostkeeper** [comment]
The solution to this is to open CMake-GUI and set the Arcus library path to where libArcus can be found.
