### ISSUE TITLE
Per-filament first-layer hotend/print temperature

### ISSUE THREAD

**Issue by VanessaE** [Ultimaker/CuraEngine#796]
Different filaments don't just need different print temperatures, they need different first-layer temperatures as well.  Just setting a global first-layer temperature via the chosen quality profile is not good enough, as it would require a quality profile for each filament (and perhaps several per, if one has multiple general quality settings they might otherwise wish to use).

Getting the first-layer temp "close enough" might be okay when printing on plain glass or on glue-stick- or hairspray-covered glass, but one especially needs to be able to fine-tune that first layer temperature properly per-filament if the bed has something a little more advanced on it like Printbite, PEI, BuildTak, etc.  What works for one filament may cause too much adhesion for another, or perhaps it might not stick at all.

Compare with Slic3r (it also allows a first-layer bed temperature; I have no use for that, but I know others do).

(this issue opened at @BagelOrb's suggestion :smiley: )

**Comment by ChrisTerBeke** [comment]
Although it's probably an engine issue, it's better to post this in the Cura repository as there is a lot more traffic there (also from the core devs).

**Comment by VanessaE** [comment]
OOps!  I actually meant to do just that.  

https://github.com/Ultimaker/Cura/issues/3957
