### ISSUE TITLE
[3.3.1] Experimental Bridging with Dual Extrusion

### ISSUE THREAD

**Issue by Galfinite** [Ultimaker/CuraEngine#799]
**Application Version**
3.3.1

**Platform**
Windows, 64bit

**Display Driver**
N/A

**Steps to Reproduce**
Enable bridging with dual extruders.
I used the benchy dual extruder model files.
Export sliced gcode

**Actual Results**
First layer of second color (with Benchy, it's the deck layer) is considered to be a bridge due to no support from the model for the same extruder.

**Expected results**
First layer should be printed normally, since there is in fact no bridge due to being supported by the model for the other extruder.

**Additional Information**
Sliced gcode/stl's attached.
See line 38124 in the gcode to see the bridge.

[3DBenchy Dualprint.zip](https://github.com/Ultimaker/CuraEngine/files/2124964/3DBenchy.Dualprint.zip)

**Comment by smartavionics** [comment]
Thanks for the report, I will investigate.

**Comment by smartavionics** [comment]
Could you please attach a project file as I am not familiar with setting up dual extruder prints, thanks.

**Comment by smartavionics** [comment]
Don't worry about the project file as I have worked out how to slice dual extruder parts and have already fixed the problem. The change has been incorporated into a pending PR (#738). Thanks again for the report.

Here's the first deck layer no longer being printed as a bridge:

![screenshot_2018-06-22_09-17-57](https://user-images.githubusercontent.com/585618/41765858-3c0c2b5c-75fd-11e8-93f8-7ec1c9a6d471.png)

Here's the roof that is being printed as a bridge:

![screenshot_2018-06-22_09-18-19](https://user-images.githubusercontent.com/585618/41765896-557485bc-75fd-11e8-87f3-d330d962dd85.png)

**Comment by Galfinite** [comment]
Awesome, thanks for the quick response!

**Comment by Vandrasc** [comment]
Thank you for reporting it, and thanks @smartavionics for fixing it! 

Cura-5240.
