### ISSUE TITLE
How to use command line to resize the model?

### ISSUE THREAD

**Issue by RezaFeng** [Ultimaker/CuraEngine#813]
Hi，I am using the CuraEngine to slice a stl file throung command lines. 
such as CuraEngine slice -v -p -s infill_distance=0 -f "fdmpriter.def.json" -o "output.gcode" -l "test.stl"
But I can not find the  parameter to resize the model.
You konw, in Cura3.4.1, I can resize the stl model like this:

![_20180726205648](https://user-images.githubusercontent.com/18794642/43263812-f01ca6ec-9116-11e8-8323-ca2e8793016c.png)
Can anyone tell me how to resize the modele through command lines? Thank you!

**Comment by BagelOrb** [comment]
You need to calculate and set the transformation matrix setting. See the command line settings section of fdmprinter.def.json

**Comment by RezaFeng** [comment]
@BagelOrb Thank you ！
