### ISSUE TITLE
[master] - optimising paths produces weird thin lines between infill

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/CuraEngine#847]
**Application Version**

master

**Platform**

Linux

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

Just noticed these thin extrusions occurring between some infill lines when I would have expected travel moves instead.

With LayerPlan::optimizePaths(const Point& starting_position) being called you get...

![screenshot_2018-09-12_21-32-22](https://user-images.githubusercontent.com/585618/45451606-6d207b00-b6d3-11e8-9fb1-b99100c51055.png)

Comment the call to that out and you get...

![screenshot_2018-09-12_21-32-46](https://user-images.githubusercontent.com/585618/45451609-71e52f00-b6d3-11e8-8d94-197041fc0862.png)

**Comment by smartavionics** [comment]
![screenshot_2018-09-13_08-08-59](https://user-images.githubusercontent.com/585618/45472517-5e19e700-b72c-11e8-8efa-722725ec3c85.png)

**Comment by rburema** [comment]
Hi @smartavionics, Which type of infill are you using? It might help (also to decide whether to work on it) if we could reproduce it with one of the 'standard' infill types. If this is only reproducible with non-'standard' types, chances are we might skip on this one. cheers, Remco.

**Comment by smartavionics** [comment]
Hi @rburema , I'm using an experimental gyroid infill. I'll close this issue now and re-open it when the gyroid infill gets incorporated into Cura.

**Comment by Ghostkeeper** [comment]
Does this still occur with Gyroid infill?

**Comment by smartavionics** [comment]
It's still badly broken but it looks to be in a different way as shown below. Those gyroid waves should not be connected and also notice how the relatively smooth waves turn into thinner, straighter lines.

BTW, for my own Cura, I have completely disabled the called to optimizePaths() as it breaks so much stuff.

![screenshot_2018-11-13_13-30-43](https://user-images.githubusercontent.com/585618/48416619-9c418000-e748-11e8-91ef-0d8446833ff5.png)

**Comment by Ghostkeeper** [comment]
The thinner, straighter lines is probably the MergeInfillLines class doing badly. We've also seen this and have a bug in our sprint for it.
