### ISSUE TITLE
Dev Feature Request: Clang format configuration

### ISSUE THREAD

**Issue by bjude** [Ultimaker/CuraEngine#871]
For those who haven't used it, ClangFormat is an automatic code formatting tool that can be run from your dev environment to keep code consistent with a projects style, defined in a `.clang-format` file placed in the root of the project. This file is then loaded by ClangFormat when run on that project by the plugin for your chosen editor/IDE.

Having a project .clang-format file would help keep code formatting consistent across the project without having to manually ensure that written code conforms with the project standards. There are ways to automatically run ClangFormat on commits or to include it in CI builds, though i haven't used it that way before.

Based on some quick toying around with https://zed0.co.uk/clang-format-configurator/, it looks like the current conventions are close to the WebKit style (select from BasedOnStyle). I also suggest that a column limit is decided on, it doesnt have to be some thing tiny like 80 but 100 or 120 could be reasonable. I have a 4k monitor but even on that, dealing with 300+ character lines is a real drain.

**Comment by Ghostkeeper** [comment]
I added that file. Hopefully it'll make it easier to configure your IDE to something that approximates the style that we're using and concurs with our code style defined in https://github.com/Ultimaker/Meta .

We've not defined a character limit on purpose.
