### ISSUE TITLE
Prime tower does not prime second extruder before use

### ISSUE THREAD

**Issue by notnyt** [Ultimaker/CuraEngine#894]
**Application Version**
3.5.1

**Platform**
win 64

**Steps to Reproduce**
setup a print with two extruders using a prime tower

**Actual Results**
prime tower only primes first extruder on first layer

**Expected results**
prime tower should prime second nozzle before use, but it does not

**Additional Information**
You can see the prime tower on the left only primed the first extruder, and not the second.

![image](https://user-images.githubusercontent.com/1365428/47619673-f3442580-dab7-11e8-8af3-572ea41c360e.png)

**Comment by rburema** [comment]
Hi @notnyt,
Could you attach the model for which this happens?
cheers, Remco.

**Comment by notnyt** [comment]
[test.zip](https://github.com/Ultimaker/CuraEngine/files/2564560/test.zip)
attached

**Comment by Ghostkeeper** [comment]
I've sliced your 3MF file using default settings of the UM3, but enabling the prime tower and support and setting the support extruder to the second extruder. This produced a file with two G280 commands, one at the beginning and the other just after the first switch to T1. So that seems to work fine.

Maybe "Enable Prime Blob" was disabled for the second extruder?

**Comment by notnyt** [comment]
> 
> 
> I've sliced your 3MF file using default settings of the UM3, but enabling the prime tower and support and setting the support extruder to the second extruder. This produced a file with two G280 commands, one at the beginning and the other just after the first switch to T1. So that seems to work fine.
> 
> Maybe "Enable Prime Blob" was disabled for the second extruder?

It's not an option that even shows up when you add a custom printer.

![image](https://user-images.githubusercontent.com/1365428/51578006-e605bf80-1e89-11e9-8dbb-858550650dc1.png)

**Comment by Ghostkeeper** [comment]
Ah, sorry. I'm so used to working with UM3 and UMS5 that it slipped my mind.

Reading through your original issue report though I find that your expected result doesn't match mine. The prime tower is meant to prime an extruder after being on stand-by. The first layer should have a skirt or a brim to prime for you, but that is not visible in your screenshot. Maybe you disabled platform adhesion?

**Comment by notnyt** [comment]
Of course I can't remember now since this was months ago, but I think there was some trouble using skirts to prime at that time.  Looking at how it slices now, it looks fine, though.
