### ISSUE TITLE
zigzag skin does not always function properly

### ISSUE THREAD

**Issue by notnyt** [Ultimaker/CuraEngine#914]
**Application Version**
3.5.1

**Platform**
ubuntu

**Steps to Reproduce**
select zig zag for top and bottom skin.  5 star gear bearing pictured

**Actual Results**

![image](https://user-images.githubusercontent.com/1365428/48581804-d3eb2c00-e8f0-11e8-88c6-889ade7348d7.png)

**Expected results**
The skin should cover the entire layer

**Comment by smartavionics** [comment]
Hello @notnyt , I think that is a regression introduced in 3.5. As far as I am aware, it's still not been addressed even in 3.6 (may be wrong about that). My Cura builds have the naughty code disabled so they should work OK. If you want to try, use the latest release at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0

**Comment by rburema** [comment]
Hi all, This is related to the 'fat infill' (casued by spurious merging) fixes, we'll try to keep this in mind as well as we're working on that. (Devs: see CURA-5776) cheers, Remco.

**Comment by alekseisasin** [comment]
I close the ticket because it is duplicated issue: https://github.com/Ultimaker/Cura/issues/4524

**Comment by notnyt** [comment]
> 
> 
> I close the ticket because it is duplicated issue: [Ultimaker/Cura#4524](https://github.com/Ultimaker/Cura/issues/4524)

That's ironing, though, this is infill

**Comment by rburema** [comment]
It may not be clear from the descriptions, but the underlying issue is the same in all of these cases: too agressive merging.
