### ISSUE TITLE
List of all -s <setting> for command line control

### ISSUE THREAD

**Issue by iasj** [Ultimaker/CuraEngine#916]
Is there a  place with a list of all the setting names for the -s control flag o CuraEngine. I couldn't find it anywhere.

Typing `CuraEngine --help` in the command line shows one of the flags of `slice` option as `-s <setting>=<value>`. So where do I find the list of all `<setting>`, and with theirr default values if it is not too much to ask?

My goal is to slice an object without using the GUI, because this way I can create scripts for some tasks.

**Comment by alekseisasin** [comment]
You can find all settings here:
https://github.com/Ultimaker/Cura/blob/master/resources/definitions/fdmprinter.def.json

**Comment by iasj** [comment]
Thank you very much. This will definitely do the job.
