### ISSUE TITLE
build tests fail

### ISSUE THREAD

**Issue by lod** [Ultimaker/CuraEngine#920]
Running `cmake -DBUILD_TESTS=ON ./`

Issue 1: cmake can't find cppunit

Fixing issue 1 by providing a Findcppunit.cmake file allows the cmake command to succeed.

Running the tests with `make; make test`

Leads to ArcusCommunicationPrivateTest failing

Examining the test this is caused by the test relying on relative paths which assume the test is executed from CuraEngine/tests/.

**Comment by Ghostkeeper** [comment]
The tests were not failing when I ran them from CuraEngine/build. But I agree that your fix is an improvement.
