### ISSUE TITLE
Slice error infill_hollow

### ISSUE THREAD

**Issue by mrobotmaker** [Ultimaker/CuraEngine#929]
Hello, 
I compile the last CuraEngine on linux ubuntu and when I want to slice like this: 
" CuraEngine slice -v -j fdmprinter.def.json -o TestSlice.gcode -l 3DBenchy.stl --next"
I have this error:
[ERROR] Trying to retrieve unregistered setting with no value given: 'infill_hollow'

Where do I have to put this setting in the definition file ?

Thank for all

**Comment by mrobotmaker** [comment]
![cura](https://user-images.githubusercontent.com/37457018/49823499-1ed95180-fd80-11e8-8009-b30c25c6c3f8.png)

**Comment by smartavionics** [comment]
Hello @mrobotmaker , that setting has been replaced by infill_support_enabled.

````
                "infill_support_enabled":
                {
                    "label": "Infill Support",
                    "description": "Print infill structures only where tops of the model should be supported. Enabling this reduces print time and material usage, but leads to ununiform object strength.",
                    "type": "bool",
                    "default_value": false,
                    "enabled": "infill_sparse_density > 0",
                    "limit_to_extruder": "infill_extruder_nr",
                    "settable_per_mesh": true
                },
````
Sounds like you are not using the latest source code for the engine?

**Comment by mrobotmaker** [comment]
Thank for your answer, but I take the link from your last git.
![git_2](https://user-images.githubusercontent.com/37457018/49927409-21da5c00-febe-11e8-8ce6-9071fc17cc4d.png)

**Comment by smartavionics** [comment]
If you are using the smartavionics repo my latest usable branch is called mb-master not master.

**Comment by smartavionics** [comment]
And please raise issues on the smartavionics github repo and not the ultimaker repo, thanks.

**Comment by Vandrasc** [comment]
If understood correctly, not an issue as the issue was posted on the wrong repo, please re-open if I misunderstood, thanks!
