### ISSUE TITLE
Allow parameters to be specified with "automation" curves

### ISSUE THREAD

**Issue by brennancheung** [Ultimaker/CuraEngine#934]
The user should be able to selectively control print parameters using "automation" curves.  While this is more of an interface, it requires the underlying functionality in the engine first so I figured I would file the feature request here.

Certain features for mechanical parts might need more precision.  Examples would be sockets, joints, and other contact points.  It would be nice to specify the places where precision matters while speeding up prints where quality doesn't matter.

Adapter layer height is the most similar feature but it is only for the layer height and you can't specify which layers to target more selectively.

For an example of what "automation" curves are, have a look at most creative software that use a timeline (video editing, digital audio workstations, animation software).  You can vary parameters over time.

In the case of 3D printing, the X axis would be the layer number, and the Y axis will be the parameter value.

Here's a photo of a quick interface I mocked up.

![img_20181222_130706](https://user-images.githubusercontent.com/289156/50378648-2274a000-05ec-11e9-9981-260167d78e4f.jpg)

Layer number might not be all that useful as a number, so it might be useful to allow markers (keyframes) to be placed at key locations and then used when specifying the automation curves.

**Comment by rburema** [comment]
Hi @brennancheung,
While this could be useful, this would require a _major_ changes and additions to the UI (amongst other things). We've decided that -given where're we're currently at- the effort to implement this outweighs the percieved utility of this new feature.
Feel free to make a P.R. though!
cheers, Remco.
