### ISSUE TITLE
CuraEngine: undefined symbol: _ZN6google8protobuf8internal17AssignDescriptorsEPNS1_22AssignDescriptorsTableE

### ISSUE THREAD

**Issue by electrocoder** [Ultimaker/CuraEngine#983]
**Application Version**
Cura latest

**Platform**
Ubuntu 18.04

CuraEngine: undefined symbol: _ZN6google8protobuf8internal17AssignDescriptorsEPNS1_22AssignDescriptorsTableE

**Comment by LipuFei** [comment]
This seems to be linking issue. Do you have protobuf installed?

**Comment by Ghostkeeper** [comment]
Was Protobuf built with the same compiler as CuraEngine?

**Comment by electrocoder** [comment]
I have python3 protobuf 3.6.1. I've reinstalled the protobuf but still not.

**Comment by electrocoder** [comment]
protobuf and libArcus remake reinstall problem solved.
