### ISSUE TITLE
[3.6.0] Problem Printing Mold in PVA

### ISSUE THREAD

**Issue by ElleEmDee** [Ultimaker/CuraEngine#988]
Hi! I'm trying to print a mold in PVA, but I keep running into trouble. When I slice in mold mode with PLA, the results look correct:

<img width="1916" alt="screen shot 2019-02-04 at 11 16 46 am" src="https://user-images.githubusercontent.com/47334137/52231745-94890780-286f-11e9-887b-d9f9534136df.png">

However, when I change the settings to: Print selected model with Extruder 2: PVA - BB 04 and keep mold mode selected, it simply slices a positive version of the model instead of the mold:

<img width="1907" alt="screen shot 2019-02-04 at 11 17 18 am" src="https://user-images.githubusercontent.com/47334137/52231845-cef2a480-286f-11e9-9f5d-cd15010271a7.png">

<img width="1916" alt="screen shot 2019-02-04 at 11 17 29 am" src="https://user-images.githubusercontent.com/47334137/52231865-d87c0c80-286f-11e9-9aa8-b3b038f5bb2b.png">

I've tried this with multiple models and keep running into the same problem.

**Application Version**
Cura Version 3.6.0

**Platform**
MacOS Mojave Version 10.14.2

**Comment by Ghostkeeper** [comment]
Mold is a per-extruder setting. You need to click on the second extruder and then enable Mold again, if you want stuff that was printed with the second extruder to also print as a mold.
