### ISSUE TITLE
def.json set mesh_rotation_matrix

### ISSUE THREAD

**Issue by city8208** [Ultimaker/CuraEngine#997]
Hi,when I use the powershell call CuraEngine and JSON.
I got a problem.

[ERROR] Trying to retrieve setting with no value given: `'mesh_rotation_matrix'`

But  I didn't found any sample from [`Cura`](https://github.com/Ultimaker/Cura/tree/master/resources/definitions) definitions.

I also found some old data say write in "overrides" can be work like this:
       ` "mesh_rotation_matrix": [[1,0,0],[0,-1,0],[0,0,-1]]`
But after try,I got this
`JSON setting mesh_rotation_matrix is not an object!`

How should I write?

**Comment by city8208** [comment]
Has been resolved

**Comment by Ghostkeeper** [comment]
Needed to wrap it in quotes, I think?
