### ISSUE TITLE
Input Default  Value not found

### ISSUE THREAD

**Issue by city8208** [Ultimaker/CuraEngine#999]
Hi,I try to use old example from [CuraEngine 3.4.1, 3.5 flat models: 0 print time, 0 filament used ](https://github.com/Ultimaker/CuraEngine/issues/873)

But I got the lost by these parameter.
1.minimum_support_area
2.material_guid
3.machine_extruder_cooling_fan_number
4.support_brim_enable
5.support_brim_line_count

And I use CuraEngine-master in newest version.
What is these parameter default  value ?

**Comment by Ghostkeeper** [comment]
> But I got the lost by these parameter.

I don't really understand this phrase of English, sorry :disappointed: 

> What is these parameter default value ?

You can find all the global default values in this file: https://github.com/Ultimaker/Cura/blob/master/resources/definitions/fdmprinter.def.json In the case of those five settings, the default values are:

* minimum_support_area: 0
* material_guid: ""
* machine_extruder_cooling_fan_number: 0
* support_brim_enable: false
* support_brim_line_count: 20

Of course if you select a particular printer other than Custom FDM Printer, different defaults could be selected. But these are good starting points anyway.

**Comment by city8208** [comment]
Thanks
